### ISSUE TITLE
Unicode Error when reading from file

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#1018]
### OS / Environment
ubuntu 18.04

### Manticore version
0d843457a9d00127607d5adb06395a280b643662

### Python version
3.6

### Step to reproduce the behavior

related to #986 

get this zip: https://github.com/trailofbits/manticore/files/2224564/return0.zip

run `manticore a.out`

### Actual behavior
```
[I] (py3) vagrant ubuntu-bionic /v/m/9/return0 ❯ manticore a.out
2018-08-02 20:15:33,453: [21046] m.manticore:INFO: Loading program a.out
2018-08-02 20:15:39,992: [21046] m.c.executor:ERROR: Exception: 'utf-8' codec can't decode byte 0xb0 in position 24: invalid start by
Traceback (most recent call last):
  File "/vagrant/manticore/manticore/platforms/linux.py", line 2217, in execute
    self.current.execute()
  File "/vagrant/manticore/manticore/core/cpu/abstractcpu.py", line 851, in execute
    raise e
  File "/vagrant/manticore/manticore/core/cpu/abstractcpu.py", line 841, in execute
    implementation(*insn.operands)
  File "/vagrant/manticore/manticore/core/cpu/abstractcpu.py", line 938, in new_method
    return old_method(cpu, *args, **kw_args)
  File "/vagrant/manticore/manticore/core/cpu/x86.py", line 5331, in SYSCALL
    raise Syscall()
manticore.core.cpu.abstractcpu.Syscall: CPU Syscall

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/manticore/manticore/core/executor.py", line 467, in run
    if not current_state.execute():
  File "/vagrant/manticore/manticore/core/state.py", line 127, in execute
    result = self._platform.execute()
  File "/vagrant/manticore/manticore/platforms/linux.py", line 2224, in execute
    self.syscall()
  File "/vagrant/manticore/manticore/platforms/linux.py", line 2070, in syscall
    return self._syscall_abi.invoke(implementation)
  File "/vagrant/manticore/manticore/core/cpu/abstractcpu.py", line 398, in invoke
    ret = super().invoke(model, prefix_args)
  File "/vagrant/manticore/manticore/core/cpu/abstractcpu.py", line 349, in invoke
    result = model(*arguments)
  File "/vagrant/manticore/manticore/platforms/linux.py", line 2544, in sys_read
    return super().sys_read(fd, buf, count)
  File "/vagrant/manticore/manticore/platforms/linux.py", line 1249, in sys_read
    data = self._get_fd(fd).read(count)
  File "/vagrant/manticore/manticore/platforms/linux.py", line 112, in read
    return self.file.read(*args)
  File "/home/vagrant/.virtualenvs/py3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 24: invalid start byte

2018-08-02 20:15:40,008: [21046] m.manticore:INFO: Results in /vagrant/manticore-play/986/return0/mcore_sr9c4xer
2018-08-02 20:15:40,008: [21046] m.manticore:INFO: Total time: 6.2406721115112305

```

**Comment by mossberg** [comment]
I think `mode_from_flags` needs to return a string with a 'b' in it.

https://github.com/trailofbits/manticore/blob/0d843457a9d00127607d5adb06395a280b643662/manticore/platforms/linux.py#L64
