### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_metadata'

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#1025]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (0d843457a9d00127607d5adb06395a280b643662)

### Python version

Python 3.6.6

### Summary of the problem

Manticore fails to call `finalize()` with the error: `AttributeError: 'NoneType' object has no attribute 'get_metadata'`

### Step to reproduce the behavior

This is a solidity contract to reproduce this issue:

```solidity
contract C {
  function f(uint x) returns (uint) {
    return x;
  }
  function g(uint x) returns (bool) {
    return true;
  }
}
```

To reproduce, run this python script:

```python
from manticore.ethereum import ManticoreEVM, FilterFunctions
m = ManticoreEVM(procs=1)
m.verbosity(4)

solidity_filename = "test.sol"

deepstate_check = FilterFunctions(regexp=r"g", depth='human', mutability='both', include=True)
m.register_plugin(deepstate_check)
m.multi_tx_analysis(solidity_filename, contract_name='C', tx_limit=1, tx_use_coverage=False, tx_account="attacker")
m.unregister_plugin(deepstate_check)

contract_account = m.accounts["contract0"]
contract_account.f(1, value=0)

m.finalize()
```

### Expected behavior

It shouldn't fail.

### Actual behavior

```
2018-08-03 14:24:35,541: [11721] m.c.executor:INFO: load state 0
2018-08-03 14:24:35,848: [11721] m.c.executor:INFO: Forking. Policy: ALL. Values: 0x0, 0x1
2018-08-03 14:24:35,861: [11721] m.c.executor:INFO: Forking current state into states [3, 4]
2018-08-03 14:24:35,867: [11721] m.c.executor:INFO: load state 3
2018-08-03 14:24:36,390: [11721] m.c.executor:INFO: Forking. Policy: ALL. Values: 0x93, 0x97
2018-08-03 14:24:36,403: [11721] m.c.executor:INFO: Forking current state into states [5, 6]
2018-08-03 14:24:36,408: [11721] m.c.executor:INFO: load state 4
2018-08-03 14:24:36,515: [11721] m.c.executor:INFO: load state 6
2018-08-03 14:24:36,885: [11721] m.c.executor:INFO: load state 5
2018-08-03 14:24:36,967: [11721] m.c.executor:ERROR: Exception: 'NoneType' object has no attribute 'get_metadata'
Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/core/executor.py", line 451, in run
    self._publish('did_load_state', current_state, current_state_id)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/utils/event.py", line 117, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/utils/event.py", line 125, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/ethereum.py", line 2009, in _load_state_callback
    world.transaction(address=address, caller=caller, data=data, value=value, price=price)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/platforms/evm.py", line 1906, in transaction
    self._process_pending_transaction()
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/platforms/evm.py", line 2022, in _process_pending_transaction
    self._open_transaction(sort, address, price, data, caller, value, gas=gas)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/platforms/evm.py", line 1554, in _open_transaction
    self._publish('will_open_transaction', tx)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/utils/event.py", line 117, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/utils/event.py", line 133, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/utils/event.py", line 131, in _publish_impl
    sink._publish_impl(_name, self, *args, **kwargs)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/utils/event.py", line 133, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/utils/event.py", line 125, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/gustavo/.local/lib/python3.6/site-packages/manticore-0.1.10-py3.6.egg/manticore/ethereum.py", line 145, in will_open_transaction_callback
    md = self.manticore.get_metadata(tx.address)
AttributeError: 'NoneType' object has no attribute 'get_metadata'
```

**Comment by defunctio** [comment]
`Eventful` currently has no way to unsubscribe so when `Manticore.unregister_plugin` is called the callbacks are never removed. 

When `contract_account.f(1, value=0)` is called this callback is still invoked.

**Comment by defunctio** [comment]
temporary solution;
This will force GC on the plugin and invoke `Eventful._unref` as originally intended removing it from the callback list.
 
```
...

m.multi_tx_analysis(solidity_filename, contract_name='C', tx_limit=1, tx_use_coverage=False, tx_account="attacker")
m.unregister_plugin(deepstate_check)
del deepstate_check

contract_account = m.accounts["contract0"]

...
```
