### ISSUE TITLE
"ValueError: Name already used" crash on simple contract

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#1065]
### OS / Environment
ubuntu 18.04

### Manticore version
8247dc66fbae3b5422b1467fe03cf6866596d42e

 

### Summary of the problem
```
[I] (py3) vagrant ubuntu-bionic /v/m/suicide-detector ❯ cat minimal.sol
//pragma solidity ^0.4.17;

contract con {
  mapping (address => uint) balances;
  address owner;

  modifier onlyOwner {
    assert(msg.sender == owner);
    _;
  }
  function _con() {
    owner = msg.sender;
  }
  function kill() public onlyOwner {
        suicide(msg.sender);
  }
}
[I] (py3) vagrant ubuntu-bionic /v/m/suicide-detector ❯ manticore minimal.sol
2018-08-21 22:30:11,773: [24915] m.main:INFO: Beginning analysis
2018-08-21 22:30:11,776: [24915] m.ethereum:INFO: Starting symbolic create contract
2018-08-21 22:30:12,046: [24915] m.ethereum:INFO: Starting symbolic transaction: 0
2018-08-21 22:30:13,430: [24915] m.ethereum:INFO: 1 alive states, 5 terminated states
2018-08-21 22:30:13,739: [24915] m.ethereum:INFO: Starting symbolic transaction: 1
2018-08-21 22:30:15,478: [24915] m.ethereum:INFO: 2 alive states, 9 terminated states
2018-08-21 22:30:15,822: [24915] m.ethereum:INFO: Starting symbolic transaction: 2
2018-08-21 22:30:16,035: [24915] m.c.executor:ERROR: Exception: Name already used
Traceback (most recent call last):
  File "/vagrant/manticore/manticore/core/executor.py", line 451, in run
    self._publish('did_load_state', current_state, current_state_id)
  File "/vagrant/manticore/manticore/utils/event.py", line 117, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/vagrant/manticore/manticore/utils/event.py", line 125, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/vagrant/manticore/manticore/ethereum.py", line 2102, in _load_state_callback
    world.transaction(address=address, caller=caller, data=data, value=value, price=price)
  File "/vagrant/manticore/manticore/platforms/evm.py", line 1901, in transaction
    self._process_pending_transaction()
  File "/vagrant/manticore/manticore/platforms/evm.py", line 1991, in _process_pending_transaction
    self.create_account(address=address)
  File "/vagrant/manticore/manticore/platforms/evm.py", line 1874, in create_account
    storage = self.constraints.new_array(index_bits=256, value_bits=256, name='STORAGE_{:x}'.format(address))
  File "/vagrant/manticore/manticore/core/smtlib/constraints.py", line 344, in new_array
    raise ValueError("Name already used")
ValueError: Name already used

2018-08-21 22:30:18,296: [24915] m.ethereum:INFO: 3 alive states, 13 terminated states
2018-08-21 22:30:18,665: [25324] m.ethereum:INFO: Generated testcase No. 0 - SELFDESTRUCT
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/vagrant/manticore/manticore/ethereum.py", line 2433, in worker_finalize
    finalizer(q.get_nowait())
  File "/vagrant/manticore/manticore/ethereum.py", line 2428, in finalizer
    self._generate_testcase_callback(st, 'test', '')
  File "/vagrant/manticore/manticore/ethereum.py", line 2320, in _generate_testcase_callback
    address_name = self.account_name(address_solution)
  File "/vagrant/manticore/manticore/ethereum.py", line 1401, in account_name
    if account.address == address:
  File "/vagrant/manticore/manticore/ethereum.py", line 1141, in __getattribute__
    self._init_hashes()
  File "/vagrant/manticore/manticore/ethereum.py", line 1126, in _init_hashes
    self.add_function(signature)
  File "/vagrant/manticore/manticore/ethereum.py", line 1109, in add_function
    raise EthereumError("Sorry function name is used by the python wrapping")
manticore.ethereum.EthereumError: Sorry function name is used by the python wrapping
2018-08-21 22:30:19,172: [24915] m.ethereum:INFO: Results in /vagrant/manticore-play/suicide-detector/mcore_ehw2cx72
```

**Comment by mossberg** [comment]
i feel like our tests should have caught something like this 😞

**Comment by mossberg** [comment]
> manticore.ethereum.EthereumError: Sorry function name is used by the python wrapping

this is because the contract had a method with the name `_con`
