### ISSUE TITLE
TypeError: unsupported format string passed to BitVecOr.__format__

### ISSUE THREAD

**Issue by NeatMonster** [trailofbits/manticore#1236]
### OS / Environment

Ubuntu 17.10

### Manticore version

0.2.2

### Python version

3.7.0

### Summary of the problem

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/manticore/core/executor.py", line 488, in run
    self.generate_testcase(current_state, str(e))
  File "/usr/local/lib/python3.7/site-packages/manticore/core/executor.py", line 358, in generate_testcase
    self._publish('will_generate_testcase', state, 'test', message)
  File "/usr/local/lib/python3.7/site-packages/manticore/utils/event.py", line 117, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/manticore/utils/event.py", line 134, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/manticore/utils/event.py", line 125, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/manticore/manticore.py", line 546, in _generate_testcase_callback
    testcase_id = self._output.save_testcase(state, name, message)
  File "/usr/local/lib/python3.7/site-packages/manticore/core/workspace.py", line 491, in save_testcase
    self.save_summary(state, message)
  File "/usr/local/lib/python3.7/site-packages/manticore/core/workspace.py", line 528, in save_summary
    summary.write(f"CPU:\n{cpu}")
  File "/usr/local/lib/python3.7/site-packages/manticore/core/cpu/abstractcpu.py", line 925, in __str__
    result += '\n'.join(self.render_registers())
  File "/usr/local/lib/python3.7/site-packages/manticore/core/cpu/abstractcpu.py", line 901, in render_register
    aux = f"{reg_name:3s}: {value:16s}"
TypeError: unsupported format string passed to BitVecOr.__format__
```

### Step to reproduce the behavior

Not so sure about this, but I guess having Manticore print a register value which is an instance of `BitVecOr`. I believe the issue was introduced by commit https://github.com/trailofbits/manticore/commit/5c44a34374c90cc96db4b0a9ff6c49593dc63c03 but I'm unable to figure out a fix that doesn't involve reverting the change made on the related lines (which seems to get rid of it).

**Comment by disconnect3d** [comment]
@NeatMonster can you share the program you used that triggers it?

**Comment by NeatMonster** [comment]
@disconnect3d Here is a minimal example:

```python
from manticore.core.cpu.arm import Armv7Cpu as Cpu
from manticore.core.memory import Memory32
from manticore.core.smtlib import BitVecVariable

from capstone import *
from keystone import *

#####
import logging
from manticore.utils.log import all_loggers

for logger_name in all_loggers:
    logger = logging.getLogger(logger_name)
    if logger_name == "manticore.manticore" \
            or logger_name.startswith("manticore.core.smtlib"):
        logger.setLevel(logging.INFO)
    else:
        logger.setLevel(logging.DEBUG)
#####

ks = Ks(KS_ARCH_ARM, KS_MODE_THUMB)


def assemble(asm):
    ords = ks.asm(asm)[0]
    if not ords:
        raise Exception(f'bad assembly: {asm}')
    return ''.join(map(chr, ords))


def setup_cpu(cpu, asm):
    code = cpu.memory.mmap(0x1000, 0x1000, 'rwx')
    data = cpu.memory.mmap(0xd000, 0x1000, 'rw')
    stack = cpu.memory.mmap(0xf000, 0x1000, 'rw')
    cpu.memory.write(code, assemble(asm))
    cpu.regfile.write('PC', code)
    cpu.regfile.write('SP', stack + 0x1000)

cpu = Cpu(Memory32())
asm = 'cmp r0, 0'
setup_cpu(cpu, asm)
cpu.R0 = BitVecVariable(32, 'r0')
cpu.execute()
```

and its output:

```
2018-11-02 15:27:00,733: [10817] m.c.memory:DEBUG: New memory map @1000 size:1000
2018-11-02 15:27:00,733: [10817] m.c.memory:DEBUG: New memory map @d000 size:1000
2018-11-02 15:27:00,733: [10817] m.c.memory:DEBUG: New memory map @f000 size:1000
2018-11-02 15:27:00,734: [10817] m.c.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000001000:	andeq	r2, r0, r0, lsl #16
2018-11-02 15:27:00,734: [10817] m.c.c.a.registers:DEBUG: APSR: 0x0000000000000000
Traceback (most recent call last):
  File "/tmp/script.py", line 43, in <module>
    cpu.execute()
  File "/usr/local/lib/python3.7/site-packages/manticore-0.2.2-py3.7.egg/manticore/core/cpu/abstractcpu.py", line 834, in execute
    for l in self.render_registers():
  File "/usr/local/lib/python3.7/site-packages/manticore-0.2.2-py3.7.egg/manticore/core/cpu/abstractcpu.py", line 901, in render_register
    aux = f"{reg_name:3s}: {value:16s}"
TypeError: unsupported format string passed to BitVecVariable.__format__
```
