### ISSUE TITLE
Not enough gas error

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#1322]
It appears that https://github.com/trailofbits/manticore/pull/1160 may have caused some errors with the gemini contracts (approve.py and others).

```
2019-01-02 19:24:32,205: [28246] m.c.manticore:INFO: Verbosity set to 3.
[+] Created an owner account 0x5da83cffb5bab1cd888417a5ecefe37b9e250d67
2019-01-02 19:24:34,872: [28413] m.c.executor:INFO: load state 0
2019-01-02 19:24:40,660: [28682] m.c.executor:INFO: load state 2
2019-01-02 19:24:50,144: [29138] m.c.executor:INFO: load state 4
2019-01-02 19:24:51,632: [29138] m.p.evm:INFO: Found a concrete SHA3 example b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05' -> 36b6384b5eca791c62761152d0c79bb0604c104a5fb6f4eb0703f3154bb3db0
2019-01-02 19:24:53,094: [29138] m.p.evm:INFO: Found a concrete SHA3 example b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06' -> f652222313e28459528d920b65115c16c04f3efc82aaedc97be59f3f377c0d3f
2019-01-02 19:24:54,090: [29138] m.p.evm:DEBUG: Not enough gas for instruction
Traceback (most recent call last):
  File "scripts/approve.py", line 8, in <module>
    mock_custodian, oberon_store, oberon_proxy, oberon_impl = h.create_all_the_things(m, owner_account)
  File "/home/mark/big2/workloads/gemini-dollar/scripts/helpers.py", line 69, in create_all_the_things
    args=(oberon_proxy.address, oberon_store.address, mock_custodian.address, owner_account))
AttributeError: 'NoneType' object has no attribute 'address'
```

**Comment by disconnect3d** [comment]
Now that we changed the default gas to 3000000 and added a configuration option for it, the bug is not there anymore, so I am closing the issue.

However, this still can be improved: e.g. by raising an exception if create_contract fails for whatever reason. This is going to be addressed soon.
