### ISSUE TITLE
m.c.executor:ERROR: Exception: /proc/self is largely unsupported

### ISSUE THREAD

**Issue by Pl0414141** [trailofbits/manticore#1411]
### OS / Environment
Ubuntu 18.04.2 LTS

### Manticore version
0.2.5

### Python version
Python 3.6.7

### Summary of the problem

A binary compiled with ASAN crash manticore analysis

root@peto-virtual-machine:~/Escritorio/challenges# g++ -fsanitize=address -ggdb -o stack stack.c

root@peto-virtual-machine:~/Escritorio/challenges# file stack
stack: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=a3a90e8585fd0441269dcc18c693d13759442940, with debug_info, not stripped

### Step to reproduce the behavior

manticore --procs 10 ./stack --file B.txt

### Expected behavior
Analysis should finish successfully

### Actual behavior
Unexpected error

### Any relevant logs

2019-04-22 10:46:10,916: [7222] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdbf650:	0f 16 04 24	movhps	xmm0, qword ptr [rsp]
2019-04-22 10:46:10,959: [7222] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc646:	0f ae 4c 24 40	fxrstor	[rsp + 0x40]
2019-04-22 10:46:11,329: [7222] m.c.executor:ERROR: Exception: /proc/self is largely unsupported
Traceback (most recent call last):
  File "/home/peto/manticore/manticore/platforms/linux.py", line 2284, in execute
    self.current.execute()
  File "/home/peto/manticore/manticore/native/cpu/abstractcpu.py", line 947, in execute
    raise e
  File "/home/peto/manticore/manticore/native/cpu/abstractcpu.py", line 938, in execute
    implementation(*insn.operands)
  File "/home/peto/manticore/manticore/native/cpu/abstractcpu.py", line 1065, in new_method
    return old_method(cpu, *args, **kw_args)
  File "/home/peto/manticore/manticore/native/cpu/x86.py", line 5463, in SYSCALL
    raise Syscall()
manticore.native.cpu.abstractcpu.Syscall: CPU Syscall

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/peto/manticore/manticore/core/executor.py", line 454, in run
    if not current_state.execute():
  File "/home/peto/manticore/manticore/native/state.py", line 18, in execute
    result = self._platform.execute()
  File "/home/peto/manticore/manticore/platforms/linux.py", line 2291, in execute
    self.syscall()
  File "/home/peto/manticore/manticore/platforms/linux.py", line 2140, in syscall
    return self._syscall_abi.invoke(implementation)
  File "/home/peto/manticore/manticore/native/cpu/abstractcpu.py", line 407, in invoke
    ret = super().invoke(model, prefix_args)
  File "/home/peto/manticore/manticore/native/cpu/abstractcpu.py", line 358, in invoke
    result = model(*arguments)
  File "/home/peto/manticore/manticore/platforms/linux.py", line 2683, in sys_open
    rv = super().sys_open(buf, flags, mode)
  File "/home/peto/manticore/manticore/platforms/linux.py", line 1458, in sys_open
    f = self._sys_open_get_file(filename, flags)
  File "/home/peto/manticore/manticore/platforms/linux.py", line 2573, in _sys_open_get_file
    f = super()._sys_open_get_file(filename, flags)
  File "/home/peto/manticore/manticore/platforms/linux.py", line 1441, in _sys_open_get_file
    raise EnvironmentError("/proc/self is largely unsupported")
manticore.platforms.linux.EnvironmentError: /proc/self is largely unsupported

**Comment by ehennenfent** [comment]
Thanks for submitting! Unfortunately, Manticore doesn't support procfs right now. Adding support is not currently on our six-month roadmap, and while it _could_ eventually happen, it's unlikely for a number of reasons. The most important one is that since Manticore only _emulates_ a target binary, it never creates a process on the underlying operating system. That means that we would need to emulate procfs in its entirety and keep it up to date in real time.

As a workaround, you might consider replacing the function that looks at `/proc/self` with a [model](https://manticore.readthedocs.io/en/latest/models.html)

**Comment by Pl0414141** [comment]
Thanks for the info
