### ISSUE TITLE
Using the latest version of z3

### ISSUE THREAD

**Issue by SunBeomSo** [trailofbits/manticore#1426]
### OS / Environment
host: Ubuntu 18.04.2 , used provided Manticore docker image

### Manticore version
0.2.5 (from docker image)

### Python version
3.6.7 (from docker image)

### Summary of the problem
I would like to use Manticore with the latest version of z3, but I failed to do so.

### Step to reproduce the behavior
In the docker image, I installed the latest z3 (v 4.8.4) through source building. I checked that I successfully installed the latest z3.
```
root@9b4fd9fbc9fd:/usr/local/lib/python3.6/dist-packages# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import z3
>>> z3.get_version_string()
'4.8.4'
```

However, when I typed "manticore" after the installation of the latest z3, I encountered the following message:
```
root@9b4fd9fbc9fd:/usr/local/lib/python3.6/dist-packages# manticore
Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'z3-solver' distribution was not found and is required by manticore
```

### Expected behavior
I checked other tools such as Oyente worked without additional efforts after the installation of the latest z3. But for Manticore, it seems I have to do something that I don't know.

**Comment by SunBeomSo** [comment]
In addition, the z3 version currently installed in the docker image is 4.8.0, which is not the official release version. Wouldn't it be a problem?

**Comment by ehennenfent** [comment]
@SunBeomSo Thanks for submitting. The docker image is built by pulling the requirements directly from pypi. The `z3-solver` package on PyPi was updated to z3 4.8.5 yesterday, so that should be included in the next docker build.

**Comment by SunBeomSo** [comment]
@ehennenfent Thanks for the answer.

**Comment by noraj** [comment]
I have the last z3-solver `4.11.2` installed and I still get this launching manticore.

```
Traceback (most recent call last):
  File "/usr/bin/manticore", line 33, in <module>
    sys.exit(load_entry_point('manticore==0.3.7', 'console_scripts', 'manticore')())
  File "/usr/bin/manticore", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/manticore/__init__.py", line 10, in <module>
    from .ethereum.manticore import ManticoreEVM
  File "/usr/lib/python3.10/site-packages/manticore/ethereum/__init__.py", line 3, in <module>
    from .manticore import ManticoreEVM, config
  File "/usr/lib/python3.10/site-packages/manticore/ethereum/manticore.py", line 34, in <module>
    from ..platforms import evm
  File "/usr/lib/python3.10/site-packages/manticore/platforms/evm.py", line 40, in <module>
    import rlp
  File "/usr/lib/python3.10/site-packages/rlp/__init__.py", line 1, in <module>
    from . import sedes  # noqa: F401
  File "/usr/lib/python3.10/site-packages/rlp/sedes/__init__.py", line 4, in <module>
    from .big_endian_int import BigEndianInt, big_endian_int  # noqa: F401
  File "/usr/lib/python3.10/site-packages/rlp/sedes/big_endian_int.py", line 1, in <module>
    from eth_utils import (
  File "/usr/lib/python3.10/site-packages/eth_utils/__init__.py", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'z3-solver' distribution was not found and is required by manticore
```

**Comment by noraj** [comment]
By looking at https://github.com/pypa/setuptools/issues/1495, it looks like it's because python-z3-solver is built with `setup.py` instead of `pyproject.toml` in AL [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/z3/trunk/PKGBUILD).

**Comment by noraj** [comment]
I was able to workaround this issue by providing a PEP517 version of python-z3-sovler: https://github.com/BlackArch/blackarch/pull/3683/files#diff-9348c39078adba11f3b2283076e2fcdc9c3350827982e2fbb7ba1fe7568babe7
