### ISSUE TITLE
Manticore crashes if the contract to analyze produces no bytecode

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#1533]
Latest manticore revision fails to analyze this valid contract:

```
contract OnlyYou {

    address you;
    constructor (
        address _you
    )
        public
    {
        you = _you;
    }
    modifier OnlyYou(address from) {
       require(you == from); 
       _;
    }
}

contract Test is OnlyYou {
    constructor ()
    public
    OnlyYou(msg.sender)
    {}

}
```

If you try to analyze `Test`, manticore crashes:

```
$ manticore test.sol --contract Test 
2019-10-09 18:30:52,801: [4437] m.main:INFO: Registered plugins: DetectUninitializedMemory, DetectInvalid, DetectManipulableBalance, DetectIntegerOverflow, DetectSuicidal, DetectReentrancyAdvanced, DetectExternalCallAndLeak, DetectDelegatecall, DetectEnvInstruction, DetectReentrancySimple, DetectUninitializedStorage, <class 'manticore.ethereum.plugins.KeepOnlyIfStorageChanges'>, DetectUnusedRetVal
2019-10-09 18:30:52,802: [4437] m.main:INFO: Beginning analysis
2019-10-09 18:30:52,806: [4437] m.e.manticore:INFO: Starting symbolic create contract
--- Logging error ---
Traceback (most recent call last):
  File "/home/g/.local/lib/python3.6/site-packages/manticore-0.3.1-py3.6.egg/manticore/ethereum/manticore.py", line 741, in solidity_create_contract
    md = SolidityMetadata(*compile_results)
  File "/home/g/.local/lib/python3.6/site-packages/manticore-0.3.1-py3.6.egg/manticore/ethereum/solidity.py", line 90, in __init__
    self.srcmap_runtime = self.__build_source_map(self.runtime_bytecode, srcmap_runtime)
  File "/home/g/.local/lib/python3.6/site-packages/manticore-0.3.1-py3.6.egg/manticore/ethereum/solidity.py", line 118, in __build_source_map
    md.get(0, 0)
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/g/.local/bin/manticore", line 11, in <module>
    load_entry_point('manticore==0.3.1', 'console_scripts', 'manticore')()
  File "/home/g/.local/lib/python3.6/site-packages/manticore-0.3.1-py3.6.egg/manticore/__main__.py", line 41, in main
    ethereum_main(args, logger)
  File "/home/g/.local/lib/python3.6/site-packages/manticore-0.3.1-py3.6.egg/manticore/ethereum/cli.py", line 111, in ethereum_main
    crytic_compile_args=vars(args),
  File "/home/g/.local/lib/python3.6/site-packages/manticore-0.3.1-py3.6.egg/manticore/ethereum/manticore.py", line 1181, in multi_tx_analysis
    crytic_compile_args=crytic_compile_args,
  File "/home/g/.local/lib/python3.6/site-packages/manticore-0.3.1-py3.6.egg/manticore/ethereum/manticore.py", line 792, in solidity_create_contract
    logger.info("Failed to compile contract", str(e))
Message: 'Failed to compile contract'
Arguments: ("invalid literal for int() with base 10: ''",)
2019-10-09 18:30:52,836: [4482] m.c.manticore:INFO: Generated testcase No. 0 - NO STATE RESULT (?)(0 txs)
2019-10-09 18:30:52,907: [4437] m.c.manticore:INFO: Results in /tmp/mcore_u96vav_e
```

However, if you specify the `OnlyYou` contract, it will work as expected.

**Comment by feliam** [comment]
For some reason the crytic-compile lib fail to return srcmap-runtime

```$ solc test.sol --combined-json srcmap,srcmap-runtime
test.sol:1:1: Warning: Source file does not specify required compiler version!Consider adding "pragma solidity ^0.4.25;"
contract OnlyYou {
^ (Relevant source part starts here and spans across multiple lines).
test.sol:11:5: Warning: This declaration shadows an existing declaration.
    modifier OnlyYou(address from) {
    ^ (Relevant source part starts here and spans across multiple lines).
test.sol:1:1: The shadowed declaration is here:
contract OnlyYou {
^ (Relevant source part starts here and spans across multiple lines).

{"contracts":{"test.sol:OnlyYou":{"srcmap":"0:213:0:-;;;41:87;8:9:-1;5:2;;;30:1;27;20:12;5:2;41:87:0;;;;;;;;;;;;;;;;;;;;;;;;;;;;;117:4;111:3;;:10;;;;;;;;;;;;;;;;;;41:87;0:213;;;;;;","srcmap-runtime":"0:213:0:-;;;;;"},"test.sol:Test":{"srcmap":"","srcmap-runtime":""}},"sourceList":["test.sol"],"version":"0.4.25+commit.59dbf8f1.Linux.g++"}
```

**Comment by montyly** [comment]
The shadowing here makes `Test` an abstract contract, with no bytecode.
My understanding is that in:
```solidity
    constructor ()
    public
    OnlyYou(msg.sender)
    {}
```

`OnlyYou(msg.sender)` is a call to the modifier and not the `OnlyYou` constructor. As a result, `Test`'s constructor is missing a call to a father's constructor and `solc` cannot generate bytecode for it.

You can try with `solc test.sol --bin`, you will see that no bytecode is generated for `Test`.

**Comment by ggrieco-tob** [comment]
Right. I changed the title to reflect that Manticore crashes if the contract to analyze does not produce bytecode.
