### ISSUE TITLE
Feature request: support for ELF binaries produced by rustc/cargo

### ISSUE THREAD

**Issue by tomtau** [trailofbits/manticore#1607]
Thanks for the awesome work on Manticore!
I tried to rewrite `basic.c` in Rust as:

```
use std::io::{self, Read};

fn main() {
    let stdin = io::stdin();
    let mut handle = stdin.lock();
    let mut r = [0u8];
    match handle.read(&mut r) {
        Err(_) => {
            println!("Error reading stdin!");
            std::process::exit(1);
        }
        Ok(_) => {
            if r[0] > 0x41 {
                println!("Message: It is greater than 0x41");
            } else {
                println!("Message: It is less than or equal to 0x41");
            }
        }
    }
    
}
```

I compiled it using `cargo build` with default settings in the latest stable version (1.41.0). When I load it with manticore 0.3.3, this is what happens:

```
2020-02-01 12:02:52,960: [10592] m.n.manticore:INFO: Loading program basic
2020-02-01 12:04:18,409: [10622] m.p.platform:WARNING: Unimplemented system call at 0x7fffff78ff17: sys_set_robust_list(0x7ffffffccf20, 0x18)
2020-02-01 12:04:18,455: [10622] m.p.linux:WARNING: SIGACTION, Ignoring changing signal handler for signal 32
2020-02-01 12:04:18,479: [10622] m.p.linux:WARNING: SIGACTION, Ignoring changing signal handler for signal 33
2020-02-01 12:04:18,488: [10622] m.p.linux:WARNING: SIGACTION, Ignoring changing signal mask set cmd:140737488354728
2020-02-01 12:04:18,503: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc631:      0f ae 44 24 40  fxsave  [rsp + 0x40]
2020-02-01 12:04:19,171: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc646:      0f ae 4c 24 40  fxrstor [rsp + 0x40]
2020-02-01 12:04:19,216: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc631:      0f ae 44 24 40  fxsave  [rsp + 0x40]
2020-02-01 12:04:19,699: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc646:      0f ae 4c 24 40  fxrstor [rsp + 0x40]
2020-02-01 12:04:19,752: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc631:      0f ae 44 24 40  fxsave  [rsp + 0x40]
2020-02-01 12:04:20,167: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc646:      0f ae 4c 24 40  fxrstor [rsp + 0x40]
2020-02-01 12:04:20,380: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc631:      0f ae 44 24 40  fxsave  [rsp + 0x40]
2020-02-01 12:04:20,821: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc646:      0f ae 4c 24 40  fxrstor [rsp + 0x40]
2020-02-01 12:04:21,667: [10622] m.n.c.x86:WARNING: CPUID with EAX=80000000 not implemented @ 7fffff574d47
2020-02-01 12:04:21,991: [10622] m.p.linux:WARNING: SIGACTION, Ignoring changing signal handler for signal 13
2020-02-01 12:04:22,056: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc631:      0f ae 44 24 40  fxsave  [rsp + 0x40]
2020-02-01 12:04:22,445: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc646:      0f ae 4c 24 40  fxrstor [rsp + 0x40]
2020-02-01 12:04:22,497: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc631:      0f ae 44 24 40  fxsave  [rsp + 0x40]
2020-02-01 12:04:22,868: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc646:      0f ae 4c 24 40  fxrstor [rsp + 0x40]
2020-02-01 12:04:22,943: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc631:      0f ae 44 24 40  fxsave  [rsp + 0x40]
2020-02-01 12:04:23,392: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc646:      0f ae 4c 24 40  fxrstor [rsp + 0x40]
2020-02-01 12:04:42,105: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc631:      0f ae 44 24 40  fxsave  [rsp + 0x40]
2020-02-01 12:04:42,549: [10622] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdcc646:      0f ae 4c 24 40  fxrstor [rsp + 0x40]
2020-02-01 12:04:43,183: [10622] m.c.worker:ERROR: Exception in state 0: EnvironmentError('/proc/self is largely unsupported',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/linux.py", line 2436, in execute
    self.current.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/native/cpu/abstractcpu.py", line 1019, in execute
    raise e
  File "/usr/local/lib/python3.6/dist-packages/manticore/native/cpu/abstractcpu.py", line 1005, in execute
    implementation(*insn.operands)
  File "/usr/local/lib/python3.6/dist-packages/manticore/native/cpu/abstractcpu.py", line 1148, in new_method
    return old_method(cpu, *args, **kw_args)
  File "/usr/local/lib/python3.6/dist-packages/manticore/native/cpu/x86.py", line 5664, in SYSCALL
    raise Syscall()
manticore.native.cpu.abstractcpu.Syscall: CPU Syscall

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/native/state.py", line 29, in execute
    result = self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/linux.py", line 2443, in execute
    self.syscall()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/linux.py", line 2270, in syscall
    return self._syscall_abi.invoke(implementation)
  File "/usr/local/lib/python3.6/dist-packages/manticore/native/cpu/abstractcpu.py", line 425, in invoke
    ret = super().invoke(model, prefix_args)
  File "/usr/local/lib/python3.6/dist-packages/manticore/native/cpu/abstractcpu.py", line 367, in invoke
    result = model(*arguments)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/linux.py", line 3086, in sys_openat
    return super().sys_openat(dirfd, buf, flags, mode)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/linux.py", line 1574, in sys_openat
    return self.sys_open(buf, flags, mode)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/linux.py", line 3058, in sys_open
    rv = super().sys_open(buf, flags, mode)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/linux.py", line 1550, in sys_open
    f = self._sys_open_get_file(filename, flags)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/linux.py", line 2916, in _sys_open_get_file
    f = super()._sys_open_get_file(filename, flags)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/linux.py", line 1533, in _sys_open_get_file
    raise EnvironmentError("/proc/self is largely unsupported")
manticore.platforms.linux.EnvironmentError: /proc/self is largely unsupported
```

It'll be nice to have a support for Linux binaries produced by Rust tooling -- if that's possible in the current version (0.3.3), it'll be good to document the needed workaround how the binary should be built with rustc / cargo.

**Comment by arun0930** [comment]
@wmason86
