### ISSUE TITLE
Mishandling of ARM modified immediate constants

### ISSUE THREAD

**Issue by bradlarsen** [trailofbits/manticore#1621]
### OS / Environment
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

### Manticore version
```
$ pip show manticore | grep Version
Version: 0.3.3
```

### Python version
```
$ python --version
Python 3.8.0
```

### Dependencies
```
$ pip freeze
alabaster==0.7.12
apipkg==1.5
appdirs==1.4.3
attrs==19.3.0
Babel==2.8.0
black==19.3b0
capstone==4.0.1
certifi==2019.11.28
chardet==3.0.4
Click==7.0
coverage==5.0.3
crytic-compile==0.1.6
cytoolz==0.10.1
docutils==0.16
eth-hash==0.2.0
eth-typing==2.2.1
eth-utils==1.8.4
execnet==1.7.1
future==0.18.2
idna==2.9
imagesize==1.2.0
Jinja2==2.11.1
keystone-engine==0.9.1.post3
manticore==0.3.3
MarkupSafe==1.1.1
more-itertools==8.2.0
mypy==0.740
mypy-extensions==0.4.3
packaging==20.1
pkg-resources==0.0.0
pluggy==0.13.1
ply==3.11
prettytable==0.7.2
py==1.8.1
pyelftools==0.26
pyevmasm==0.2.0
Pygments==2.5.2
pyparsing==2.4.6
pysha3==1.0.2
pytest==5.3.0
pytest-cov==2.8.1
pytest-forked==1.1.3
pytest-xdist==1.30.0
pytz==2019.3
PyYAML==5.3
requests==2.23.0
rlp==1.2.0
six==1.14.0
snowballstemmer==2.0.0
Sphinx==2.4.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
toml==0.10.0
toolz==0.10.0
typed-ast==1.4.1
typing-extensions==3.7.4.1
unicorn==1.0.2rc1
urllib3==1.25.8
wasm==1.2
wcwidth==0.1.8
wrapt==1.12.0
z3-solver==4.8.7.0
```

### Summary of the problem
In a nontrivial ARM binary, Manticore crashes when it encounters certain ADD instructions.

### Step to reproduce the behavior
```
$ python -mmanticore -vv wc
```
(I've attached a gzipped version of GNU coreutils `wc` for ARMv7: [wc.gz](https://github.com/trailofbits/manticore/files/4289250/wc.gz))

### Expected behavior
Manticore succeeds in its normal operation

### Actual behavior
Manticore crashes:
```
2020-03-04 14:11:04,560: [7824] m.n.manticore:INFO: Loading program /home/blarsen/coreutils-armv7-install/bin/wc
2020-03-04 14:11:04,562: [7824] m.p.linux:DEBUG: Opening file descriptors (0,1,2) (STDIN, STDOUT, STDERR)
2020-03-04 14:11:04,562: [7824] m.p.linux:DEBUG: Loading /home/blarsen/coreutils-armv7-install/bin/wc as a armv7 elf
2020-03-04 14:11:04,562: [7824] m.p.linux:DEBUG: Loading /home/blarsen/coreutils-armv7-install/bin/wc as a armv7 elf
2020-03-04 14:11:04,562: [7824] m.p.linux:INFO: Interpreter filename: b'/lib/ld-linux.so.3'
2020-03-04 14:11:04,563: [7824] m.p.linux:DEBUG: Loading elf offset: 00000000 addr:00010000 0001a000 r x
2020-03-04 14:11:04,563: [7824] m.p.linux:DEBUG: Loading elf offset: 00009000 addr:00029000 0002b000 rw
2020-03-04 14:11:04,564: [7824] m.p.linux:DEBUG: Zeroing main elf fractional pages. From bss(2a188) to brk(2b000), 3704 bytes.
2020-03-04 14:11:04,607: [7824] m.p.linux:DEBUG: Entry point: 00000000000113f8
2020-03-04 14:11:04,607: [7824] m.p.linux:DEBUG: Stack start: 00000000c0000000
2020-03-04 14:11:04,607: [7824] m.p.linux:DEBUG: Brk: 000000000002b000
2020-03-04 14:11:04,607: [7824] m.p.linux:DEBUG: Mappings:
2020-03-04 14:11:04,607: [7824] m.p.linux:DEBUG:   0000000000010000-000000000001a000  r x 00000000 /home/blarsen/coreutils-armv7-install/bin/wc
2020-03-04 14:11:04,607: [7824] m.p.linux:DEBUG:   0000000000029000-000000000002b000  rw  00009000 /home/blarsen/coreutils-armv7-install/bin/wc
2020-03-04 14:11:04,607: [7824] m.p.linux:DEBUG:   00000000bffdf000-00000000c0000000  rwx 00000000
2020-03-04 14:11:04,608: [7824] m.p.linux:DEBUG: Setting argv, envp and auxv.
2020-03-04 14:11:04,608: [7824] m.p.linux:DEBUG:        Arguments: ['/home/blarsen/coreutils-armv7-install/bin/wc']
2020-03-04 14:11:04,608: [7824] m.p.linux:DEBUG:        Auxv:
2020-03-04 14:11:04,608: [7824] m.p.linux:DEBUG:                AT_PHDR: 0x10034
2020-03-04 14:11:04,608: [7824] m.p.linux:DEBUG:                AT_PHENT: 0x20
2020-03-04 14:11:04,608: [7824] m.p.linux:DEBUG:                AT_PHNUM: 0x9
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_PAGESZ: 0x1000
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_BASE: 0x0
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_FLAGS: 0x5000200
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_ENTRY: 0x113f8
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_UID: 0x3e8
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_EUID: 0x3e8
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_GID: 0x3e8
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_EGID: 0x3e8
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_CLKTCK: 0x64
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_HWCAP: 0x0
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_RANDOM: 0xbffffff0
2020-03-04 14:11:04,609: [7824] m.p.linux:DEBUG:                AT_EXECFN: 0xbfffffc3
2020-03-04 14:11:04,677: [7824] m.u.helpers:INFO: Serializing /home/blarsen/manticore.pristine/mcore_2pj9b6wk/state_00000000.pkl
2020-03-04 14:11:04,690: [7824] m.u.helpers:INFO: Deserializing /home/blarsen/manticore.pristine/mcore_2pj9b6wk/state_00000000.pkl
2020-03-04 14:11:04,692: [7824] m.u.helpers:INFO: Serializing /home/blarsen/manticore.pristine/mcore_2pj9b6wk/state_00000000.pkl
2020-03-04 14:11:04,764: [7854] m.u.helpers:INFO: Deserializing /home/blarsen/manticore.pristine/mcore_2pj9b6wk/state_00000000.pkl
2020-03-04 14:11:04,774: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x00000000000113f8:       mov     fp, #0
2020-03-04 14:11:04,776: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x00000000000113fc:       mov     lr, #0
2020-03-04 14:11:04,777: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011400:       pop     {r1}
2020-03-04 14:11:04,778: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011404:       mov     r2, sp
2020-03-04 14:11:04,779: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011408:       str     r2, [sp, #-4]!
2020-03-04 14:11:04,781: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x000000000001140c:       str     r0, [sp, #-4]!
2020-03-04 14:11:04,782: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011410:       ldr     ip, [pc, #0x10]
2020-03-04 14:11:04,782: [7854] m.n.c.arm:DEBUG: ARM mode PC relative addressing: PC + offset: 0x11414 + 0x4
2020-03-04 14:11:04,782: [7854] m.n.c.arm:DEBUG: ARM mode PC relative addressing: PC + offset: 0x11414 + 0x4
2020-03-04 14:11:04,784: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011414:       str     ip, [sp, #-4]!
2020-03-04 14:11:04,786: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011418:       ldr     r0, [pc, #0xc]
2020-03-04 14:11:04,786: [7854] m.n.c.arm:DEBUG: ARM mode PC relative addressing: PC + offset: 0x1141c + 0x4
2020-03-04 14:11:04,786: [7854] m.n.c.arm:DEBUG: ARM mode PC relative addressing: PC + offset: 0x1141c + 0x4
2020-03-04 14:11:04,787: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x000000000001141c:       ldr     r3, [pc, #0xc]
2020-03-04 14:11:04,788: [7854] m.n.c.arm:DEBUG: ARM mode PC relative addressing: PC + offset: 0x11420 + 0x4
2020-03-04 14:11:04,788: [7854] m.n.c.arm:DEBUG: ARM mode PC relative addressing: PC + offset: 0x11420 + 0x4
2020-03-04 14:11:04,789: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011420:       bl      #0x11254
2020-03-04 14:11:04,790: [7854] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011254:       add     ip, pc, #0, #12
2020-03-04 14:11:04,792: [7854] m.c.worker:ERROR: Exception in state 0: TypeError('ADD() takes from 3 to 4 positional arguments but 5 were given')
Traceback (most recent call last):
  File "/home/blarsen/manticore.pristine/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/home/blarsen/manticore.pristine/manticore/native/state.py", line 29, in execute
    result = self._platform.execute()
  File "/home/blarsen/manticore.pristine/manticore/platforms/linux.py", line 2438, in execute
    self.current.execute()
  File "/home/blarsen/manticore.pristine/manticore/native/cpu/abstractcpu.py", line 1005, in execute
    implementation(*insn.operands)
  File "/home/blarsen/manticore.pristine/manticore/native/cpu/abstractcpu.py", line 1148, in new_method
    return old_method(cpu, *args, **kw_args)
  File "/home/blarsen/manticore.pristine/manticore/native/cpu/arm.py", line 44, in instruction_implementation
    ret = body(cpu, *args, **kwargs)
TypeError: ADD() takes from 3 to 4 positional arguments but 5 were given

2020-03-04 14:11:04,793: [7854] m.u.helpers:INFO: Serializing /home/blarsen/manticore.pristine/mcore_2pj9b6wk/state_00000000.pkl
2020-03-04 14:11:04,891: [7824] m.c.plugin:INFO: Instructions executed: 0
2020-03-04 14:11:04,892: [7824] m.c.plugin:INFO: Coverage: 0 different instructions executed
2020-03-04 14:11:04,900: [7824] m.c.manticore:INFO: Results in /home/blarsen/manticore.pristine/mcore_2pj9b6wk
2020-03-04 14:11:04,901: [7824] m.n.manticore:INFO: Total time: 0.2118089199066162
```

**Comment by bradlarsen** [comment]
Some info on the attached `wc` binary:

```
$ arm-linux-gnueabi-readelf -h ~/coreutils-armv7-install/bin/wc
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x113f8
  Start of program headers:          52 (bytes into file)
  Start of section headers:          55692 (bytes into file)
  Flags:                             0x5000200, Version5 EABI, soft-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         9
  Size of section headers:           40 (bytes)
  Number of section headers:         30
  Section header string table index: 29
```

It's ARMv7 Thumb-2 code:
```
$ arm-linux-gnueabi-readelf -a -W ~/coreutils-armv7-install/bin/wc | tail -15
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7"
  Tag_CPU_arch: v7
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_CPU_unaligned_access: v6
```

**Comment by bradlarsen** [comment]
The particular code in the `wc` binary that Manticore is crashing on is this bit, very early in the analysis:
```
00011254 <__libc_start_main@plt>:
   11254:   e28fc600    add ip, pc, #0, 12
   11258:   e28cca18    add ip, ip, #24, 20 ; 0x18000
   1125c:   e5bcfe3c    ldr pc, [ip, #3644]!    ; 0xe3c
```

I obtained this courtesy of `objdump` and some cross-referencing of Manticore log output:
```
$ arm-linux-gnueabi-objdump -D ~/coreutils-armv7-install/bin/wc
```

**Comment by bradlarsen** [comment]
**Aside:**

It would be helpful in the future if Manticore emitted in its log output some breadcrumbs about what code it's looking at, when it has that information.  This would help a human better understand where in a binary Manticore is currently working.  For example, it would be helpful if Manticore would emit a message like this in this example:
```
2020-03-03 17:55:33,520: [3556] m.n.c.abstractcpu:DEBUG: Executing <__libc_start_main@plt>
2020-03-03 17:55:33,530: [3586] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011254:       add     ip, pc, #0, #12
```
Currently, that second line _is_ emitted, but nothing like the first line is.

Alternatively, the `INSTRUCTION` debug output might be modified so that the addresses included there are mapped to labels if they are known. For example, instead of this:
```
2020-03-03 17:55:33,530: [3586] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011254:       add     ip, pc, #0, #12
```
What if Manticore could say this?
```
2020-03-03 17:55:33,530: [3586] m.n.c.abstractcpu:DEBUG: INSTRUCTION: 0x0000000000011254 (<__libc_start_main@plt>):       add     ip, pc, #0, #12
```
This might be able to be generalized to a label+offset format.

**Comment by bradlarsen** [comment]
Regarding the troublesome ADD instructions in `wc`:
```
00011254 <__libc_start_main@plt>:
   11254:   e28fc600    add ip, pc, #0, 12
   11258:   e28cca18    add ip, ip, #24, 20 ; 0x18000
   1125c:   e5bcfe3c    ldr pc, [ip, #3644]!    ; 0xe3c
```
It _looks_ like that first `add ip, pc, #0, 12` instruction is [this ADD (immediate) form](http://infocenter.arm.com/help/topic/com.arm.doc.100069_0609_00_en/pge1427897643454.html), where the `12` is actually an `LSL 12` shift applied to the `#0` immediate.

That second `add ip, ip, #24, 20` instruction I'm really not sure about.  It doesn't sound like it's the same ADD (immediate) form, since what would be the shift value (`20`) is neither `LSL #0` nor `LSL #12`, which the documentation says are the valid options.

**Comment by bradlarsen** [comment]
Some possibly helpful references for understanding what's going on here:

- https://reverseengineering.stackexchange.com/questions/16154/arm-add-instruction-with-shift
- http://www.davespace.co.uk/arm/introduction-to-arm/barrel-shifter.html
- https://stackoverflow.com/questions/17763582/how-to-encode-immediate-value-in-arm
- https://reverseengineering.stackexchange.com/questions/1992/what-is-plt-got

**Comment by bradlarsen** [comment]
Note, the particular crash in Manticore is from trying to call `Armv7Cpu.ADD` with too many arguments for the Python function:
https://github.com/trailofbits/manticore/blob/f79d0c34b45191f4b8aa2bb117819055c8e57dcb/manticore/native/cpu/arm.py#L1027-L1035
You can see, a 5-argument version is not currently supported.

**Comment by bradlarsen** [comment]
It turns out that the problem here doesn't actually seem to be an unsupported ADD instruction form; it's a more general problem that so-called _modified immediates_ on ARM aren't properly supported.

In [The ARM Architecture Reference Manual, ARMv7-A and ARMv7-R edition(https://static.docs.arm.com/ddi0406/c/DDI0406C_C_arm_architecture_reference_manual.pdf), we see in section A4.4.1 ("Standard data-processing instructions") that many instructions support a second operand that can be an immediate constant; additionally, an immediate constant can be encoded directly in the instruction, or encoded as a _modified immediate constant_ that uses 12 bits.

Later, in section A5.2.4 ("Modified immediate constants in ARM instructions") on page A5-200, we see encoding details for these modified immediate constants for ARM (thumb is different).  In particular, the 12 least-significant bits encode the immediate constant, with bits [8 .. 11] indicating a circular right rotation amount, and bits [0 .. 7] indicating the bits to be rotated.  A screenshot:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1483920/76783075-9964fe00-6787-11ea-8d67-fb73a3dab07b.png">

A page later, the manual explains what the confusing syntax like we see in `add ip, ip, #24, 20 ; 0x18000` actually means:

    An alternative syntax is available for a modified immediate constant that permits the programmer to specify the encoding directly. In this syntax, #<const> is instead written as #<byte>, #<rot>, where:

         <byte>     is the numeric value of abcdefgh, in the range 0-255
         <rot>      is twice the numeric value of rotation, an even number in the range 0-30.

    This syntax permits all ARM data-processing instructions with modified immediate constants to be disassembled to assembler syntax that assembles to the original instruction.

(Thanks to @artemdinaburg for pointing me to this reference material!)

So, `add ip, ip, #24, 20` actually means `add ip, ip, (the bitstring for 24 rotated right 20 places)`, or `add ip, ip, #98304`, or in prose, "increment the ip register by 98304."  (98304 is the same as 0x18000, as the disassembler helpfully noted in a comment.)

It's a bit strange that Manticore ends up seeing this kind of modified immediate (e.g., `#24, 20`) split into a couple values.  I'll try to figure out exactly where it's going wrong.  Is it an issue with Capstone, or something on top of that?
