### ISSUE TITLE
Better log invalid instructions from unicorn

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#163]
Make it print the problematic instruction when it's not handled even at unicorn.

$ manticore some_app
2017-04-21 10:30:55,198: [28132] MAIN:INFO: Loading program: ['some_app']
2017-04-21 10:30:55,199: [28132] MAIN:INFO: Workspace: ./mcore_ViYAIf
2017-04-21 10:33:28,328: [28182][0] EXECUTOR:ERROR: Exception: Invalid instruction (UC_ERR_INSN_INVALID)
Traceback (most recent call last):
  File "/home/user/Projects/manticore/manticore/core/executor.py", line 669, in run
    if not current_state.execute():
  File "/home/user/Projects/manticore/manticore/core/state.py", line 88, in execute
    result = self.model.execute()
  File "/home/user/Projects/manticore/manticore/models/linux.py", line 1702, in execute
    self.current.execute()
  File "/home/user/Projects/manticore/manticore/core/cpu/abstractcpu.py", line 444, in execute
    implementation(*instruction.operands)
  File "/home/user/Projects/manticore/manticore/core/cpu/abstractcpu.py", line 435, in fallback_to_emulate
    self.emulate(instruction)
  File "/home/user/Projects/manticore/manticore/core/cpu/abstractcpu.py", line 459, in emulate
    emu.emulate(instruction)
  File "/home/user/Projects/manticore/manticore/utils/emulate.py", line 184, in emulate
    self._step(instruction)
  File "/home/user/Projects/manticore/manticore/utils/emulate.py", line 230, in _step
    self._emu.emu_start(self._cpu.PC, self._cpu.PC+instruction.size, count=1)
  File "build/bdist.linux-x86_64/egg/unicorn/unicorn.py", line 288, in emu_start
    raise UcError(status)
UcError: Invalid instruction (UC_ERR_INSN_INVALID)

**Comment by simon-bourne** [comment]
It already does this if you run in verbose mode. e.g. `manticore --verbose EXE`, you'll get a log line like:

    2017-04-28 08:29:41,174: [30945][0] CPU:INFO: Unimplemented instruction: 0x00000000005547c0:	c4 e3 7d 38 c0 01	vinserti128	ymm0, ymm0, xmm0, 1

**Comment by roachspray** [comment]
Is there a sample case available for this?

**Comment by mossberg** [comment]
I created a nonsensical binary using the insn simon-bourne pointed out which triggers this issue.

[helloworld2.zip](https://github.com/trailofbits/manticore/files/1483968/helloworld2.zip)

I get info on the particular unimplemented instruction if I use `manticore -vv`, but not `-v`. Even still, I think there is still work to be done here, it is a little unsightly to just totally crash there. 

we should
- do a logger.error and log the instruction if unicorn has an error like that
- while we're at it, we can remove this line https://github.com/trailofbits/manticore/blob/35d8fce9df21f3fa645f24174589df84061fe0c1/manticore/core/executor.py#L502 which is resulting in double printing of exceptions

**Comment by roachspray** [comment]
Question: is the desire to just log? Or pretty print and raise exception still?

**Comment by mossberg** [comment]
sorry for being ambiguous; let's both log an error and raise an exception. the error log should look something like this

```
2017-04-28 08:29:41,174: [30945][0] CPU:ERROR: Unimplemented instruction: 0x00000000005547c0:	c4 e3 7d 38 c0 01	vinserti128	ymm0, ymm0, xmm0, 1
```
currently when it raises the exception, it automatically logs that an error occurred, but it would be nice for it to also error log what the instruction is 

```
2017-11-22 16:34:59,591: [127218] m.c.executor:ERROR: Exception: Invalid instruction (UC_ERR_INSN_INVALID)
Traceback (most recent call last):
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 460, in run
    if not current_state.execute():
  File "/mnt/hgfs/code/manticore/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/mnt/hgfs/code/manticore/manticore/platforms/linux.py", line 2058, in execute
    self.current.execute()
  File "/mnt/hgfs/code/manticore/manticore/core/cpu/abstractcpu.py", line 764, in execute
    self.emulate(insn)
  File "/mnt/hgfs/code/manticore/manticore/core/cpu/abstractcpu.py", line 793, in emulate
    raise InstructionEmulationError(str(e))
InstructionEmulationError: Invalid instruction (UC_ERR_INSN_INVALID)

```

**Comment by roachspray** [comment]
OK, thank you -- you were fine, so it goes. I have a patch, but will wait to submit tomorrow when I am sure I am thinking properly.

**Comment by roachspray** [comment]
Sorry for lag for simple PR; submitted: https://github.com/trailofbits/manticore/pull/599

I note I did not use format() to be consistent.
