### ISSUE TITLE
Solc Support Problem

### ISSUE THREAD

**Issue by Miller-kk** [trailofbits/manticore#1643]
# Summary of the problem

When compiling with solc by adding ABIEncoderV2 in Solidity, there was no problem. However, when using code in manticore, I had the following problem. What version of solc does the opcode currently supported by manticore support? And I wonder if it does not support abiV2.

Detection Code
```
pragma solidity ^0.5.5;
pragma experimental ABIEncoderV2;
contract SimpleSuicide {
    mapping(address => uint) balanceOf;

        constructor() public {
        }
    
    function sudicideAnyone() public {
            selfdestruct(msg.sender);
    }
}
```

Error Console
```
2020-03-31 11:09:30,432: [5220] m.c.worker:ERROR: Exception in state 0: TypeError("'BitVecConstant' object cannot be interpreted as an integer",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2783, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1242, in execute
    result = self._handler(*arguments)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1115, in _handler
    return implementation(*arguments)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1864, in MSTORE
    self._store(address, value, 32)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1338, in _store
    self._publish("did_evm_write_memory", offset, value, size)
  File "/usr/local/lib/python3.6/dist-packages/manticore/utils/event.py", line 146, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/utils/event.py", line 163, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/utils/event.py", line 163, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/utils/event.py", line 161, in _publish_impl
    sink._publish_impl(_name, self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/utils/event.py", line 154, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/detectors.py", line 683, in did_evm_write_memory_callback
    for offset_i in range(offset, offset + size):
TypeError: 'BitVecConstant' object cannot be interpreted as an integer
```

**Comment by feliam** [comment]
ManticoreEVM is only passing tests for Frontier. Solidity 0.4.25 normally does not give any trouble. There is a way to make newer solidity to produce Frontier EVM opcodes. McoreEVM does not support ABIEncoderV2 (It will just not pretty print any of it).

The problem you have encountered looks like a bug in the uninitialized memory usage detection. `--exclude-all` will disable all canned issue detection. I have failed to reproduce it with manticore master and solidity 0.5.5

(Quick workaround? Just use solc 0.4.25 for now)

**Comment by Miller-kk** [comment]
Thank you @feliam  :)
