### ISSUE TITLE
ERROR: SyscallNotImplemented('Syscall index "140" (sys_llseek) not implemented.',)

### ISSUE THREAD

**Issue by Tigerzuo** [trailofbits/manticore#1658]
### OS / Environment
ubuntu 18.04

### Manticore version
0.3.3

### Python version
3.6.9

### Summary of the problem
When running a binary called turkey, this error shows up. Not really sure what this means. I thought sys_llseek is implemented from a previous pull request. I can provide the source of the turkey binary. 

### Actual behavior
```
System calls should be copied and pasted into linux.py, not implemented within the stub file. If you're seeing this message, you may have forgotten to do that.
2020-04-06 21:34:44,395: [12674] m.c.worker:ERROR: Exception in state 3: SyscallNotImplemented('Syscall index "140" (sys_llseek) not implemented.',)
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.6/site-packages/manticore/platforms/linux.py", line 2436, in execute
    self.current.execute()
  File "/home/tiger/.local/lib/python3.6/site-packages/manticore/native/cpu/abstractcpu.py", line 1019, in execute
    raise e
  File "/home/tiger/.local/lib/python3.6/site-packages/manticore/native/cpu/abstractcpu.py", line 1005, in execute
    implementation(*insn.operands)
  File "/home/tiger/.local/lib/python3.6/site-packages/manticore/native/cpu/abstractcpu.py", line 1148, in new_method
    return old_method(cpu, *args, **kw_args)
  File "/home/tiger/.local/lib/python3.6/site-packages/manticore/native/cpu/x86.py", line 3245, in INT
    raise Interruption(op0.read())
manticore.native.cpu.abstractcpu.Interruption: CPU Software Interruption 00000080

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.6/site-packages/manticore/platforms/linux.py", line 2263, in syscall
    implementation = getattr(self.stubs, name)
  File "/home/tiger/.local/lib/python3.6/site-packages/manticore/platforms/linux_syscall_stubs.py", line 27, in __getattr__
    return getattr(self.parent, item)
AttributeError: 'SLinux' object has no attribute 'sys_llseek'

During handling of the above exception, another exception occurred:




```

**Comment by bradlarsen** [comment]
@Tigerzuo: Yes, that is surprising behavior.

Did you use the latest version of Manticore from `master`?  How exactly did you invoke `manticore` on the `turkey` binary?

**Comment by Tigerzuo** [comment]
Hey @bradlarsen I installed manticore from pip, all I know is that its version 0.3.3. How can I check if its master? I ran the command "manticore turkey".

**Comment by ehennenfent** [comment]
We released 0.3.3 at the very end of January, so some of the commits from the `master` branch [haven't made it out yet](https://github.com/trailofbits/manticore/compare/0.3.3...HEAD).  We'll probably have another release out in the next few weeks, but in the meantime, you can use the following commands to install from `master`:
```
git clone https://github.com/trailofbits/manticore.git && cd manticore
pip install -e .[native]
```
[Further developer installation instructions](https://github.com/trailofbits/manticore/wiki/Hacking-on-Manticore#developer-installation)

**Comment by Tigerzuo** [comment]
Yeah, the current master fixed it. Thanks for the help and sorry for the trouble.

**Comment by bradlarsen** [comment]
Happy to help!
