### ISSUE TITLE
AttributeError: Can't pickle local object 'ManticoreEVM.finalize.<locals>.worker_finalize'

### ISSUE THREAD

**Issue by anhdungle93** [trailofbits/manticore#1713]
### Summary of the problem
I installed Manticore in a conda environment successfully. When I tried to run `manticore` on my contract I get the following error
```
2020-05-19 10:48:08,688: [46846] m.c.manticore:WARNING: Manticore is only supported on Linux. Proceed at your own risk!
2020-05-19 10:48:08,984: [46846] m.main:INFO: Registered plugins: <class 'manticore.ethereum.plugins.KeepOnlyIfStorageChanges'>, DetectIntegerOverflow, DetectEnvInstruction, DetectInvalid, DetectReentrancyAdvanced, DetectManipulableBalance, DetectSuicidal, DetectReentrancySimple, DetectUninitializedStorage, DetectUninitializedMemory, DetectUnusedRetVal, DetectDelegatecall, DetectExternalCallAndLeak
2020-05-19 10:48:08,985: [46846] m.main:INFO: Beginning analysis
2020-05-19 10:48:08,988: [46846] m.e.manticore:INFO: Starting symbolic create contract
2020-05-19 10:48:10,871: [46846] m.e.manticore:INFO: Starting symbolic transaction: 0
2020-05-19 10:48:13,487: [46846] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x000\xc9\x876\x96\xd0\x19\x07\xc6\x19\\\x9b\xcc\n\xa1\xe1\x0b\xc2\x1e^\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' -> 37870910923366812978174481120969973927961717676482637691130062068585317403513
2020-05-19 10:48:13,885: [46846] m.e.manticore:INFO: 0 alive states, 10 terminated states
2020-05-19 10:48:14,299: [46846] m.e.manticore:INFO: Starting symbolic transaction: 1
Traceback (most recent call last):
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/bin/manticore", line 8, in <module>
    sys.exit(main())
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/site-packages/manticore/__main__.py", line 42, in main
    ethereum_main(args, logger)
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/site-packages/manticore/ethereum/cli.py", line 123, in ethereum_main
    m.finalize(only_alive_states=args.only_alive_testcases)
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/site-packages/manticore/core/manticore.py", line 128, in newFunction
    return func(self, *args, **kw)
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/site-packages/manticore/ethereum/manticore.py", line 1645, in finalize
    proc.start()
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/anhdungle/opt/anaconda3/envs/manticore_env/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ManticoreEVM.finalize.<locals>.worker_finalize'
```
### Manticore version

0.3.3
### Python version

3.8.2
### OS / Environment

MacOS Catalina
### Dependencies

result from pip freeze
```
certifi==2020.4.5.1
crytic-compile==0.1.8
cytoolz==0.10.1
eth-hash==0.2.0
eth-typing==2.2.1
eth-utils==1.9.0
future==0.18.2
manticore==0.3.3
ply==3.11
prettytable==0.7.2
pyevmasm==0.2.0
pysha3==1.0.2
PyYAML==5.3.1
rlp==1.2.0
toolz==0.10.0
wasm==1.2
wrapt==1.12.1
z3-solver==4.8.8.0
```

**Comment by bradlarsen** [comment]
Thanks for the report, @anhdungle93. Is there an input program you can share that reproduces this issue?

Alternatively, you could check on your end if the problem happens with the latest version of Manticore from `master` from git (rather than the version from PyPI).

**Comment by anhdungle93** [comment]
@bradlarsen Thanks for the answer. Unfortunately I am not allowed to disclose the code. I will try to install the latest version of Manticore from git.

**Comment by anhdungle93** [comment]
@bradlarsen I still get the same problem. I also used the tool on a simple example 

```
pragma solidity >=0.4.24 <0.6.0;
contract Simple {
    function f(uint a) payable public{
        if (a == 65) {
            revert();
        }
    }
}
```

and still got errors, but I will create a new issue #1715 for it.

**Comment by Jovonni** [comment]
> @bradlarsen Thanks for the answer. Unfortunately I am not allowed to disclose the code. I will try to install the latest version of Manticore from git.

Did this solution work, to install from source? instead of pip?
