### ISSUE TITLE
minimal_bytecode_only.py throws "TypeError: address invalid type"

### ISSUE THREAD

**Issue by iliastsa** [trailofbits/manticore#1821]
### Summary of the problem
Running `examples/evm/minimal_bytecode_only.py` throws an exception: `TypeError: address invalid type`

### Manticore version
0.3.5

### Python version
Python 3.8.5

### OS / Environment
Ubuntu 20.04.1 LTS

### Dependencies
```
certifi==2020.6.20
chardet==3.0.4
crytic-compile==0.1.9
cytoolz==0.11.0
eth-hash==0.2.0
eth-typing==2.2.2
eth-utils==1.9.5
future==0.18.2
greenlet==0.4.17
idna==2.10
manticore==0.3.4
msgpack==1.0.0
numpy==1.19.4
pandas==1.1.4
ply==3.11
prettytable==1.0.1
py-solc-x==1.0.0
pyevmasm==0.2.3
pynvim==0.4.2
pysha3==1.0.2
python-dateutil==2.8.1
pytz==2020.4
PyYAML==5.3.1
requests==2.24.0
rlp==2.0.0
semantic-version==2.8.5
six==1.15.0
toolz==0.11.1
urllib3==1.25.11
wasm==1.2
wcwidth==0.2.5
z3-solver==4.8.9.0
```

### Step to reproduce the behavior
While at the manticore root folder, run: `python examples/evm/minimal_bytecode_only.py`

### Expected behavior
The example to run successfully.

### Actual behavior
The example fails to complete.

### Any relevant logs
```
Traceback (most recent call last):
  File "examples/evm/minimal_bytecode_only.py", line 27, in <module>
    m.transaction(
  File "/home/iliastsa/.local/lib/python3.8/site-packages/manticore/ethereum/manticore.py", line 773, in transaction
    self._transaction(
  File "/home/iliastsa/.local/lib/python3.8/site-packages/manticore/ethereum/manticore.py", line 918, in _transaction
    raise TypeError("address invalid type")
TypeError: address invalid type
```

**Comment by iliastsa** [comment]
Small update: I checked older versions of manticore, and it run fine up to 0.3.3; some change in 0.3.4 must have introduced this regression.

**Comment by erivas** [comment]
Maybe you can check if modifying the initial balance works?
```
-user_account = m.create_account(balance=1000)
+user_account = m.create_account(balance=10000000)
```

**Comment by iliastsa** [comment]
Yeah that works

**Comment by feliam** [comment]
Apparently from o 0.3.3 to 0.3.4 the caller started to pay for the tx.

**Comment by rickbeeloo** [comment]
Other examples have this too, still no fix for this?
