### ISSUE TITLE
Exception in state 2: EVMException('Symbolic size not supported',)

### ISSUE THREAD

**Issue by enderphan94** [trailofbits/manticore#2455]
### Summary of the problem
EVMException('Symbolic size not supported',)

### Manticore version
Using docker version

### Step to reproduce the behavior
1. Run "manticore B.sol  --contract BContract"

### Actual behavior
2021-05-18 03:09:00,628: [130] m.e.manticore:INFO: Starting symbolic create contract
2021-05-18 03:09:06,165: [130] m.e.manticore:INFO: Starting symbolic transaction: 0
2021-05-18 03:09:15,521: [130] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00&\x8b$B\xa4\xa9\x87\x92\xfb|X\x1d\xd9W\x9e\xc5\x1a\xda\xe1\x89\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x98' -> 63144388591595042788283566883113364993274285799127754433391853881262481619377
2021-05-18 03:21:38,051: [130] m.e.detectors:WARNING: Potentially reading uninitialized storage
2021-05-18 03:26:21,522: [130] m.c.worker:ERROR: Exception in state 2: EVMException('Symbolic size not supported',)
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/platforms/evm.py", line 3093, in execute
    self.current_vm.execute()
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/platforms/evm.py", line 1313, in execute
    result = self._handler(*arguments)
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/platforms/evm.py", line 1179, in _handler
    return implementation(*arguments)
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/platforms/evm.py", line 2284, in REVERT
    data = self.read_buffer(offset, size)
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/platforms/evm.py", line 1398, in read_buffer
    raise EVMException("Symbolic size not supported")
manticore.platforms.evm.EVMException: Symbolic size not supported

**Comment by aayanqazi** [comment]
any update ? I'm also facing same error. @enderphan94
