### ISSUE TITLE
when execute test whole directory, manticore stop unexpected.

### ISSUE THREAD

**Issue by luuuuo** [trailofbits/manticore#2483]
### Summary of the problem

manticore .   
when execute test whole directory, manticore stop unexpected.
### Manticore version

Version: 0.3.6
### Python version

Python 3.6.4
### OS / Environment

centos7
### Dependencies

capstone==4.0.2
certifi==2021.5.30
charset-normalizer==2.0.4
crytic-compile==0.2.1
cytoolz==0.11.0
dataclasses==0.8
eth-hash==0.3.1
eth-typing==2.2.2
eth-utils==1.10.0
future==0.18.2
idna==3.2
importlib-metadata==4.6.4
intervaltree==3.1.0
manticore==0.3.6
ply==3.11
prettytable==2.1.0
protobuf==3.17.3
py-solc==3.2.0
py-solc-x==1.1.0
pyelftools==0.27
pyevmasm==0.2.3
pysha3==1.0.2
PyYAML==5.4.1
requests==2.26.0
rlp==2.0.1
semantic-version==2.8.5
six==1.16.0
solc-select==0.2.1
sortedcontainers==2.4.0
toolz==0.11.1
typing-extensions==3.10.0.0
unicorn==1.0.2
urllib3==1.26.6
wasm==1.2
wcwidth==0.2.5
z3-solver==4.8.12.0
zipp==3.5.0
### Any relevant logs

Process Process-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/manticore/ethereum/manticore.py", line 1756, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/python3/lib/python3.6/site-packages/manticore/ethereum/manticore.py", line 1747, in finalizer
    if only_alive_states and last_tx.result in {"REVERT", "THROW", "TXERROR"}:
AttributeError: 'NoneType' object has no attribute 'result'
2021-08-25 14:51:26,072: [2626] m.c.manticore:INFO: Results in /etc/profile.d/mcore_qsxevhqf
2021-08-25 14:51:26,075: [2626] m.c.manticore:WARNING: Manticore failed to run

**Comment by xp007123** [comment]
This may be a problem with your Python version, but use version 3.7 or higher
