### ISSUE TITLE
constructor with arg crashes manticore script

### ISSUE THREAD

**Issue by vaioco** [trailofbits/manticore#2520]
### Summary of the problem
manticore script crashes with a very trivial contract with constructor args.

### Manticore version
Version: 0.3.6

### Python version
Python 3.6.9

### OS / Environment
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

### Dependencies
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.2.0
base58==2.1.0
bitarray==1.2.2
certifi==2021.5.30
chardet==4.0.0
charset-normalizer==2.0.6
click==8.0.1
crytic-compile==0.2.1
cytoolz==0.11.2
dataclasses==0.8
eth-abi==2.1.1
eth-account==0.5.6
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
etheno==0.2.4
Flask==2.0.1
future==0.18.2
hexbytes==0.2.2
idna==3.2
idna-ssl==1.1.0
importlib-metadata==4.8.2
importlib-resources==5.2.2
intervaltree==3.1.0
ipfshttpclient==0.8.0a2
itsdangerous==2.0.1
Jinja2==3.0.1
jsonschema==3.2.0
lru-dict==1.1.7
manticore==0.3.6
MarkupSafe==2.0.1
multiaddr==0.0.9
multidict==5.1.0
netaddr==0.8.0
parsimonious==0.8.1
ply==3.11
prettytable==2.4.0
protobuf==3.19.1
ptyprocess==0.7.0
pycryptodome==3.10.1
pyevmasm==0.2.3
pygobject==3.26.1
pyrsistent==0.18.0
pysha3==1.0.2
python-apt==1.6.5+ubuntu0.7
PyYAML==6.0
requests==2.26.0
rlp==2.0.1
six==1.16.0
slither-analyzer==0.8.1
solc-select==1.0.0b1
sortedcontainers==2.4.0
toolz==0.11.2
typing-extensions==4.0.0
urllib3==1.26.7
varint==1.0.2
wasm==1.2
wcwidth==0.2.5
web3==5.23.1
websockets==9.1
Werkzeug==2.0.1
yarl==1.6.3
z3-solver==4.8.12.0
zipp==3.6.0

### Step to reproduce the behavior
given the following contract 
```
contract C {

  function C(bool x) {
      return;
  }
}
```
and the following manticore script
```
from manticore.ethereum import ManticoreEVM
from manticore.ethereum.abi import ABI
from manticore.core.smtlib import Operators

ETHER = 10**18

m = ManticoreEVM() # initiate the blockchain
# Init
user_account = m.create_account(1*ETHER)
with open('error.sol', 'r') as f:
    contract_account = m.solidity_create_contract(f, owner=user_account, contract_name="C")

```
the tool fails with `python3 error.py`

```
Traceback (most recent call last):
  File "error.py", line 11, in <module>
    contract_account = m.solidity_create_contract(f, owner=user_account, contract_name="C")
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/ethereum/manticore.py", line 586, in solidity_create_contract
    constructor_data = ABI.serialize(constructor_types, *args)
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/ethereum/abi.py", line 105, in serialize
    result, dyn_result = ABI._serialize(parsed_ty, values)
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/ethereum/abi.py", line 136, in _serialize
    sub_result, sub_dyn_result = ABI._serialize_tuple(ty[1], value, dyn_offset)
  File "/home/ethsec/.local/lib/python3.6/site-packages/manticore/ethereum/abi.py", line 165, in _serialize_tuple
    f"The number of values to serialize is {'less' if len(value) < len(types) else 'greater'} than the number of types"
ValueError: The number of values to serialize is less than the number of types
```
### Expected behavior
 should not crash

### Actual behavior
crash

**Comment by DaniWppner** [comment]
The `m.solidity_create_contract()` method checks for `args is None` before automatically making symbolic arguments, but the default value of `args` appears to be `()`

**Comment by stefanandy** [comment]
Having the same problem in 0.3.7, is there any fix or workaround for this ?
