### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by Lokizzle** [trailofbits/manticore#2589]
### Summary of the problem
Unable to use manticore

### Manticore version
Version: 0.3.7

### Python version
3.10.6

### OS / Environment
Ubuntu 22.04

### Dependencies
apturl==0.5.2
bcrypt==3.2.0
blinker==1.4
Brlapi==0.8.3
capstone==5.0.0rc2
certifi==2020.6.20
chardet==4.0.0
cliapp==1.20180812.1
click==8.0.3
cmdtest==0.32+git
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
crytic-compile==0.2.3
cupshelpers==1.0
cytoolz==0.12.0
dbus-python==1.2.18
defer==1.0.6
distlib==0.3.5
distro==1.7.0
distro-info===1.1build1
duplicity==0.8.21
eth-hash==0.3.3
eth-typing==3.2.0
eth-utils==2.0.0
fasteners==0.14.1
filelock==3.7.1
future==0.18.2
gpg===1.16.0-unknown
gyp==0.1
httplib2==0.20.2
idna==3.3
importlib-metadata==4.6.4
intervaltree==3.1.0
jeepney==0.7.1
keyring==23.5.0
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lockfile==0.12.2
louis==3.20.0
macaroonbakery==1.3.1
Mako==1.1.3
-e git+https://github.com/trailofbits/manticore.git@85d6389efa147fb67e6f136a6f541e7129f9a9ab#egg=manticore
Markdown==3.3.6
MarkupSafe==2.0.1
monotonic==1.6
more-itertools==8.10.0
netifaces==0.11.0
numpy==1.21.5
oauthlib==3.2.0
olefile==0.46
packaging==21.3
paramiko==2.9.3
pbr==5.9.0
pexpect==4.8.0
Pillow==9.0.1
platformdirs==2.5.2
ply==3.11
prettytable==3.3.0
protobuf==3.20.2
ptyprocess==0.7.0
pycairo==1.20.1
pycups==2.0.1
pyelftools==0.29
pyevmasm==0.2.3
Pygments==2.11.2
PyGObject==3.42.1
PyJWT==2.3.0
pymacaroons==0.13.0
PyNaCl==1.5.0
pyparsing==2.4.7
PyQt5==5.15.6
PyQt5-sip==12.9.1
pyRFC3339==1.1
pysha3==1.0.2
PySocks==1.7.1
python-apt==2.3.0+ubuntu2.1
python-dateutil==2.8.1
python-debian===0.1.43ubuntu1
pytz==2022.1
pyxdg==0.27
PyYAML==5.4.1
reportlab==3.6.8
requests==2.25.1
rlp==3.0.0
SecretStorage==3.3.1
six==1.16.0
 Editable install with no version control (slither-analyzer==0.8.3)
-e /usr/local/lib/python3.10/dist-packages
solc-select==0.2.1
sortedcontainers==2.4.0
stevedore==4.0.0
systemd-python==234
toolz==0.12.0
torbrowser-launcher==0.3.3
ttystatus==0.38
ubuntu-advantage-tools==27.10
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
unicorn==2.0.0
urllib3==1.26.5
usb-creator==0.3.7
virtualenv==20.15.1
virtualenv-clone==0.5.7
virtualenvwrapper==4.8.4
wadllib==1.3.6
wasm==1.2
wcwidth==0.2.5
xdg==5
xdot==1.2
xkit==0.0.0
z3-solver==4.11.2.0
zipp==1.0.0

### Step to reproduce the behavior
Cant use manticore
using this command: manticore xxx.sol

### Expected behavior
a useful output

### Actual behavior
this output:
`Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 33, in <module>
    sys.exit(load_entry_point('manticore', 'console_scripts', 'manticore')())
  File "/usr/local/bin/manticore", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/loki/manticore/manticore/manticore/__main__.py", line 13, in <module>
    from .wasm.cli import wasm_main
  File "/home/loki/manticore/manticore/manticore/wasm/__init__.py", line 1, in <module>
    from .manticore import ManticoreWASM
  File "/home/loki/manticore/manticore/manticore/wasm/manticore.py", line 9, in <module>
    from .types import I32, I64, F32, F64
  File "/home/loki/manticore/manticore/manticore/wasm/types.py", line 5, in <module>
    import wasm
  File "/usr/local/lib/python3.10/dist-packages/wasm/__init__.py", line 5, in <module>
    from .decode import (
  File "/usr/local/lib/python3.10/dist-packages/wasm/decode.py", line 5, in <module>
    from .modtypes import ModuleHeader, Section, SEC_UNK, SEC_NAME, NameSubSection
  File "/usr/local/lib/python3.10/dist-packages/wasm/modtypes.py", line 4, in <module>
    from .wasmtypes import *
  File "/usr/local/lib/python3.10/dist-packages/wasm/wasmtypes.py", line 4, in <module>
    from .types import UIntNField, UnsignedLeb128Field, SignedLeb128Field
  File "/usr/local/lib/python3.10/dist-packages/wasm/types.py", line 296, in <module>
    class Structure(WasmField):
  File "/usr/local/lib/python3.10/dist-packages/wasm/compat.py", line 26, in wrapper
    return metaclass(cls.__name__, cls.__bases__, orig_vars)
  File "/usr/local/lib/python3.10/dist-packages/wasm/types.py", line 264, in __new__
    isinstance(cur_field, collections.Callable) or
AttributeError: module 'collections' has no attribute 'Callable'
`

### Any relevant logs
nope

**Comment by elopez** [comment]
Thanks for the report @Lokizzle! Unfortunately Python 3.10 is not supported yet, see issue #2577.
