### ISSUE TITLE
Still getting the issue of "AttributeError: Can't pickle local object 'ManticoreEVM.finalize.<locals>.worker_finalize'"

### ISSUE THREAD

**Issue by upalchowdhury** [trailofbits/manticore#2642]
### Summary of the problem
getting below error when running on a optimism contract 

manticore contracts/echidna/FuzzBurn.sol --solc-remaps '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/ @openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/ @rari-capital/solmate/=node_modules/@rari-capital/solmate/ forge-std/=node_modules/forge-std/src/ ds-test/=node_modules/ds-test/src/' --exclude naming-convention
WARNING:manticore.core.manticore:Manticore is only supported on Linux. Proceed at your own risk!
2023-06-08 14:27:01,657: [74758] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-06-08 14:27:01,657: [74758] m.main:INFO: Beginning analysis
2023-06-08 14:27:01,659: [74758] m.e.manticore:INFO: Starting symbolic create contract
Traceback (most recent call last):
  File "/Users/upalc/opt/anaconda3/bin/manticore", line 8, in <module>
    sys.exit(main())
  File "/Users/upalc/opt/anaconda3/lib/python3.8/site-packages/manticore/__main__.py", line 43, in main
    ethereum_main(args, logger)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/site-packages/manticore/ethereum/cli.py", line 145, in ethereum_main
    m.finalize(only_alive_states=args.only_alive_testcases)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/site-packages/manticore/core/manticore.py", line 177, in newFunction
    return func(self, *args, **kw)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/site-packages/manticore/ethereum/manticore.py", line 1779, in finalize
    proc.start()
  File "/Users/upalc/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ManticoreEVM.finalize.<locals>.worker_finalize'

### Python version

3.8
### OS / Environment

macOs ventura 13.0.1

### Any relevant logs

ANother issue i am running into is while running the examples given in manticore repo,

python constraint.py > results.txt 
WARNING:manticore.core.manticore:Manticore is only supported on Linux. Proceed at your own risk!
Traceback (most recent call last):
  File "constraint.py", line 10, in <module>
    contract_account = m.solidity_create_contract(f, owner=user_account)
  File "/Users/upalc/opt/anaconda3/lib/python3.8/site-packages/manticore/ethereum/manticore.py", line 585, in solidity_create_contract
    compile_results = self._compile(
  File "/Users/upalc/opt/anaconda3/lib/python3.8/site-packages/manticore/ethereum/manticore.py", line 359, in _compile
    compilation_result = ManticoreEVM._compile_through_crytic_compile(
  File "/Users/upalc/opt/anaconda3/lib/python3.8/site-packages/manticore/ethereum/manticore.py", line 281, in _compile_through_crytic_compile
    if len(compilation_unit.contracts_names_without_libraries) > 1:
AttributeError: 'CompilationUnit' object has no attribute 'contracts_names_without_libraries'

**Comment by upalchowdhury** [comment]
I have tried with latest version as well but no luck.
