### ISSUE TITLE
Unhandled sys_write exception

### ISSUE THREAD

**Issue by yan** [trailofbits/manticore#272]
### OS / Environment
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

### Python version
Python 2.7.12

### Summary of the problem
The Linux platform incorrectly tries to use the `is_full()` method in the `sys_write` implementation, which is only defined on sockets.

```
2017-05-24 13:42:52,455: [83565][0] EXECUTOR:ERROR: Exception: 'File' object has no attribute 'is_full'
Traceback (most recent call last):
  File "/mnt/hgfs/projects/manticore/manticore/core/executor.py", line 672, in run
    if not current_state.execute():
  File "/mnt/hgfs/projects/manticore/manticore/core/state.py", line 88, in execute
    result = self.platform.execute()
  File "/mnt/hgfs/projects/manticore/manticore/platforms/linux.py", line 1628, in execute
    syscallret = self.syscall()
  File "/mnt/hgfs/projects/manticore/manticore/platforms/linux.py", line 1486, in syscall
    return self._syscall_abi.invoke(implementation)
  File "/mnt/hgfs/projects/manticore/manticore/core/cpu/abstractcpu.py", line 263, in invoke
    result = model(*argument_tuple)
  File "/mnt/hgfs/projects/manticore/manticore/platforms/linux.py", line 1973, in sys_write
    return super(SLinux, self).sys_write(fd, buf, count)
  File "/mnt/hgfs/projects/manticore/manticore/platforms/linux.py", line 1055, in sys_write
    if fd > 2 and self.files[fd].is_full():
AttributeError: 'File' object has no attribute 'is_full'
```

**Comment by yan** [comment]
Fixed in PR #289

**Comment by nettrino** [comment]
Still unfixed :/

**Comment by mossberg** [comment]
I get this error when running the above program

```
2017-06-08 16:34:56,414: [13396][21] SMT:WARNING: Found an unknown core, probably a solver timeout
2017-06-08 16:35:12,848: [13396][29] PLATFORM:DEBUG: sys_newfstat(3, ...) -> 120 bytes
2017-06-08 16:35:13,193: [13396][29] EXECUTOR:ERROR: Exception: expected a string or other character buffer object
Traceback (most recent call last):
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 683, in run
    if not current_state.execute():
  File "/mnt/hgfs/code/manticore/manticore/core/state.py", line 89, in execute
    result = self.platform.execute()
  File "/mnt/hgfs/code/manticore/manticore/platforms/linux.py", line 1679, in execute
    syscallret = self.syscall()
  File "/mnt/hgfs/code/manticore/manticore/platforms/linux.py", line 1533, in syscall
    return self._syscall_abi.invoke(implementation)
  File "/mnt/hgfs/code/manticore/manticore/core/cpu/abstractcpu.py", line 256, in invoke
    result = model(*argument_tuple)
  File "/mnt/hgfs/code/manticore/manticore/platforms/linux.py", line 2031, in sys_write
    return super(SLinux, self).sys_write(fd, buf, count)
  File "/mnt/hgfs/code/manticore/manticore/platforms/linux.py", line 1069, in sys_write
    self.files[fd].write(data)
  File "/mnt/hgfs/code/manticore/manticore/platforms/linux.py", line 56, in write
    self.file.write(c)
TypeError: expected a string or other character buffer object

2017-06-08 16:35:13,193: [13396][29] EXECUTOR:ERROR: Traceback (most recent call last):
2017-06-08 16:35:13,193: [13396][29] EXECUTOR:ERROR:   File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 683
2017-06-08 16:35:13,193: [13396][29] EXECUTOR:ERROR:     if not current_state.execute():

```
