### ISSUE TITLE
Analysis failed - EXECUTOR:ERROR: Exception: 'State' object has no attribute 'PC'

### ISSUE THREAD

**Issue by einret** [trailofbits/manticore#300]
### OS / Environment
$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

### Python version
$ python --version
Python 2.7.12

### Dependencies
$ pip freeze
backports.shutil-get-terminal-size==1.0.0
capstone==3.0.5rc2
decorator==4.0.11
enum34==1.1.6
ipython==5.4.1
ipython-genutils==0.2.0
manticore==0.1.1
pathlib2==2.2.1
pexpect==4.2.1
pickleshare==0.7.4
ply==3.10
prompt-toolkit==1.0.14
ptyprocess==0.5.1
pyelftools==0.24
Pygments==2.2.0
scandir==1.5
simplegeneric==0.8.1
six==1.10.0
traitlets==4.3.2
unicorn==1.0.1
wcwidth==0.1.7

### Summary of the problem

The execution stops and none analysis output are available.

```
2017-06-10 18:11:54,994: [22787][0] EXECUTOR:ERROR: Exception: 'State' object has no attribute 'PC'
Traceback (most recent call last):
  File "/home/xxx/.virtualenvs/manticore/local/lib/python2.7/site-packages/manticore/core/executor.py", line 772, in run
    logger.error('SymbolicMemoryException at PC: 0x%16x. Cause: %s', current_state.PC, e.cause)
AttributeError: 'State' object has no attribute 'PC'
```

it seems that the issue happens on the instruction movzx  eax,BYTE PTR [rax] where RAX contains symbolic buffer. 

### Step to reproduce the behavior
the binary could be found at [https://github.com/angr/angr-doc/raw/master/examples/ais3_crackme/ais3_crackme ](https://github.com/angr/angr-doc/raw/master/examples/ais3_crackme/ais3_crackme )

the python script used is the following 

```
#!/usr/bin/env python
# -*- coding: utf-8 --

from manticore import Manticore

m = Manticore('ais3_crackme')

buffer_addr=0
num_bytes=30

@m.hook(0x4005cd)
def hook(state):
    print("fake 2 args EDI=2")
    state.cpu.EDI=0x2


@m.hook(0x4005f3) 
def hook(state):
    print("retreive buffer from rax")
    global buffer_addr
    solution = state.new_symbolic_buffer(num_bytes)
    state.constrain(solution[0] == ord('a'))
    state.constrain(solution[1] == ord('i'))
    state.constrain(solution[2] == ord('s'))
    state.constrain(solution[3] == ord('3'))
    state.constrain(solution[4] == ord('{'))
    buffer_addr=state.cpu.RAX
    print ("buffer addr : %08x " %(buffer_addr))
    state.cpu.write_bytes(buffer_addr, solution)

@m.hook(0x40060e)
def hook(state):
    print("fail path ....")
    state.abandon()

@m.hook(0x4005ae)
def hook(state):
    print ("++++ hook @0x4005ae <+142>: movzx  eax,BYTE PTR [rax] .....")
    print (state.cpu.RAX)

@m.hook(0x4005b1)
def hook(state):
    print ("++++ hook @0x4005b1 <+145>: test   al,al .....")

@m.hook(0x400602)
def hook(state):
    print("it is a win path")
    res = ''.join(map(chr, state.solve_buffer(buffer_addr,num_bytes)))
    #res=''
    #for i in xrange (num_bytes):
    #    res+=res+''.join(chr(state.solve_one(i)))
    print("flag is : %s"%(res))
    m.terminate()

m.verbosity =1 
m.run(procs=10)


```
just run it

### Expected behavior
The analysis should correctly terminate and dumps results in mcore_* directory

### Actual behavior
The analysis is not completed and no results are dumped 

### Any relevant logs

the following output of the execution of the script
```
$ python psol_ais3.py 
fake 2 args EDI=2
retreive buffer from rax
buffer addr : 7ffffffffec6 
++++ hook @0x4005ae <+142>: movzx  eax,BYTE PTR [rax] .....
<manticore.core.smtlib.expression.BitVecAnd object at 0x7f10db757290>
2017-06-10 18:57:27,158: [26265][0] MEMORY:INFO: Reading 1 bytes from symbolic address <manticore.core.smtlib.expression.BitVecAnd object at 0x7f10db7b2990>
2017-06-10 18:58:22,266: [26265][0] MEMORY:INFO: Got TooManySolutions on a symbolic read. Range [7b33736961, ffffff7b33736961]. Not crashing!
2017-06-10 18:58:22,267: [26265][0] MEMORY:INFO: Memory:0000000000400000-0000000000401000  r x 00000000 ais3_crackme
0000000000600000-0000000000601000  r   00000000 
0000000000601000-0000000000602000  rw  00000000 
00007fffff9ee000-00007fffffbad000  r x 00000000 
00007fffffbad000-00007fffffdad000      00000000 
00007fffffdad000-00007fffffdb1000  r   00000000 
00007fffffdb1000-00007fffffdb3000  rw  00000000 
00007fffffdb3000-00007fffffdb7000  rw  00000000 
00007fffffdb7000-00007fffffddd000  r x 00000000 /lib64/ld-linux-x86-64.so.2
00007ffffffb7000-00007ffffffb8000  rw  00000000 
00007ffffffb8000-00007ffffffb9000  rw  00000000 
00007ffffffb9000-00007ffffffba000  rw  00000000 
00007ffffffda000-00007ffffffdc000  rw  00000000 
00007ffffffdc000-00007ffffffdd000  r   00000000 
00007ffffffdd000-00007ffffffdf000  rw  00000000 
00007ffffffdf000-0000800000000000  rwx 00000000 
2017-06-10 18:58:22,290: [26265][0] EXECUTOR:ERROR: Exception: 'State' object has no attribute 'PC'
Traceback (most recent call last):
  File "/home/xxx/.virtualenvs/manticore/local/lib/python2.7/site-packages/manticore/core/executor.py", line 772, in run
    logger.error('SymbolicMemoryException at PC: 0x%16x. Cause: %s', current_state.PC, e.cause)
AttributeError: 'State' object has no attribute 'PC'

2017-06-10 18:58:22,297: [26265][0] EXECUTOR:ERROR: Traceback (most recent call last):
2017-06-10 18:58:22,297: [26265][0] EXECUTOR:ERROR:   File "/home/xxx/.virtualenvs/manticore/local/lib/python2.7/site-packages/manticore/core/executor.py", line 772, in run
2017-06-10 18:58:22,299: [26265][0] EXECUTOR:ERROR:     logger.error('SymbolicMemoryException at PC: 0x%16x. Cause: %s', current_state.PC, e.cause)
2017-06-10 18:58:22,299: [26265][0] EXECUTOR:ERROR: AttributeError: 'State' object has no attribute 'PC'


```

**Comment by einret** [comment]
hi, the exception works fine now, but the symbolic execution error still occurs, the instruction crash is not  `movzx eax,BYTE PTR [rax]` but the next one` test al,al` with rax a symbolic buffer 

`0x00000000004005b1 <+145>:	test   al,al`

you will find below the whole error message

```
$ python psol_ais3.py
fake 2 args EDI=2
retreive buffer from rax
buffer addr : 7ffffffffec6 
++++ hook @0x4005ae <+142>: movzx  eax,BYTE PTR [rax] .... 
manticore.core.smtlib.expression.BitVecAnd object at 0x7ff2b5d2a390>
2017-06-12 21:32:03,125: [31578][0] MEMORY:INFO: Reading 1 bytes from symbolic address <manticore.core.smtlib.expression.BitVecAnd object at 0x7ff2b6d02e10>
2017-06-12 21:32:57,665: [31578][0] MEMORY:INFO: Got TooManySolutions on a symbolic read. Range [7b33736961, ffffff7b33736961]. Not crashing!
2017-06-12 21:32:57,668: [31578][0] MEMORY:INFO: Memory:0000000000400000-0000000000401000  r x 00000000 ais3_crackme
0000000000600000-0000000000601000  r   00000000 
0000000000601000-0000000000602000  rw  00000000 
00007fffff9ee000-00007fffffbad000  r x 00000000 
00007fffffbad000-00007fffffdad000      00000000 
00007fffffdad000-00007fffffdb1000  r   00000000 
00007fffffdb1000-00007fffffdb3000  rw  00000000 
00007fffffdb3000-00007fffffdb7000  rw  00000000 
00007fffffdb7000-00007fffffddd000  r x 00000000 /lib64/ld-linux-x86-64.so.2
00007ffffffb7000-00007ffffffb8000  rw  00000000 
00007ffffffb8000-00007ffffffb9000  rw  00000000 
00007ffffffb9000-00007ffffffba000  rw  00000000 
00007ffffffda000-00007ffffffdc000  rw  00000000 
00007ffffffdc000-00007ffffffdd000  r   00000000 
00007ffffffdd000-00007ffffffdf000  rw  00000000 
00007ffffffdf000-0000800000000000  rwx 00000000 
2017-06-12 21:32:57,689: [31578][0] EXECUTOR:ERROR: SymbolicMemoryException at PC: 0x          4005b1. Cause: No access reading symbolic
2017-06-12 21:32:57,692: [31578][0] EXECUTOR:INFO: Constraint for crashing! <manticore.core.smtlib.expression.BoolAnd object at 0x7ff2b69de710>
2017-06-12 21:32:57,733: [31578][0] EXECUTOR:INFO: Generating testcase No. 1 for state No.5 - Symbolic Memory Exception: No access reading symbolic <<manticore.core.smtlib.expression.BitVecAnd object at 0x7ff2b6d02e10>>
2017-06-12 21:32:58,007: [31578][0] EXECUTOR:INFO: Forking state 0 into states [5]
```

**Comment by mossberg** [comment]
This should be very easy to fix! When Manticore detects a memory violation, it raises an exception internally, however this exception is never caught.

**Comment by mossberg** [comment]
As for why it did not solve the challenge, the issue is actually related to the script (which caused a MemoryException) and not a bug in Manticore itself. 

One mistake with the script was the use of a global variable to hold buffer_addr, instead of using `m.context` (or the recently added `state.context`).  Because multiprocessing was enabled, the process that executed the "win" hook may not be the one where buffer_addr was assigned in! The other issue with the script was an incorrect understanding of what RAX points to.

See below for a working solution script (works on manticore master):


```
#!/usr/bin/env python
# -*- coding: utf-8 --

from manticore import Manticore


m = Manticore('ais3_crackme', ['a'*30])

buffer_addr=0
num_bytes=30

@m.hook(0x4005cd)
def hook(state):
    print("fake 2 args EDI=2")
    state.cpu.EDI=0x2


@m.hook(0x4005f3)
def hook(state):
    print("retreive buffer from rax")
    global buffer_addr
    # print state.cpu.read_int(state.cpu.RAX), 'yoo'
    # assert 0
    solution = state.new_symbolic_buffer(num_bytes)
    state.constrain(solution[0] == ord('a'))
    state.constrain(solution[1] == ord('i'))
    state.constrain(solution[2] == ord('s'))
    state.constrain(solution[3] == ord('3'))
    state.constrain(solution[4] == ord('{'))
    buffer_addr=state.cpu.read_int(state.cpu.RAX)
    state.context[1] = buffer_addr
    print 'yo buff addr', hex(buffer_addr)
    print state.cpu.read_bytes(buffer_addr, 8)
    print ("buffer addr : %08x " %(buffer_addr))
    state.cpu.write_bytes(buffer_addr, solution)

@m.hook(0x40060e)
def hook(state):
    print("fail path ....")
    state.abandon()

@m.hook(0x4005ae)
def hook(state):
    print ("++++ hook @0x4005ae <+142>: movzx  eax,BYTE PTR [rax] .....")
    print (state.cpu.RAX)

@m.hook(0x4005b1)
def hook(state):
    print ("++++ hook @0x4005b1 <+145>: test   al,al .....")

@m.hook(0x400602)
def hook(state):
    print("it is a win path")
    buffer_addr = state.context[1]
    print 'yo buff addr', hex(buffer_addr)
    print state.cpu.read_bytes(buffer_addr, 8)
    res = ''.join(map(chr, state.solve_buffer(buffer_addr,num_bytes)))
    #res=''
    #for i in xrange (num_bytes):
    #    res+=res+''.join(chr(state.solve_one(i)))
    print("flag is : %s"%(res))
    m.terminate()

m.verbosity =1
m.run(procs=10)
```
