### ISSUE TITLE
Error: "MOV() takes exactly 3 arguments (4 given)"

### ISSUE THREAD

**Issue by montyly** [trailofbits/manticore#309]
### OS / Environment

Ubuntu 16.04

### Python version

2.7.12

### Dependencies

capstone==3.0.5rc2
manticore==0.1.2
ply==3.10
pyelftools==0.24
unicorn==1.0.1

### Summary of the problem
Manticore crashes on the instruction `mov [X], ax` (32 bits).
I tested with some variants (`mov [X], bx`, `mov BYTE [X], al`, or in 64 bits) and manticore works fine on them.

### Step to reproduce the behavior
``` asm
; small asm program which tests the mov instruction and exits
; nasm -f elf32 test.asm
; ld -m elf_i386 test.o -o test

global main
section .data
buf: db "A",1

section .text

main:
    mov eax, 0x1
    mov ebx, 0x0
    mov WORD [buf],ax
    int 0x80
```
`python -m manticore ./test`

### Expected behavior
```
2017-06-16 17:12:07,094: [8406] MAIN:INFO: Loading program: ['/tmp/test'] 
2017-06-16 17:12:07,095: [8406] MAIN:INFO: Workspace: /tmp/tests/mcore_tDmYuF
2017-06-16 17:12:07,894: [8456][0] EXECUTOR:INFO: Generating testcase No. 1 for state No.0 - Program finished correctly
```

### Actual behavior
```
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR: Traceback (most recent call last):
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:   File "/path/virtualenv/local/lib/python2.7/site-packages/manticore/core/executor.py", line 694, in run
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:     if not current_state.execute():
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:   File "/path/virtualenv/local/lib/python2.7/site-packages/manticore/core/state.py", line 89, in execute
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:     result = self.platform.execute()
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:   File "/path/virtualenv/local/lib/python2.7/site-packages/manticore/platforms/linux.py", line 1703, in execute
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:     self.current.execute()
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:   File "/path/virtualenv/local/lib/python2.7/site-packages/manticore/core/cpu/abstractcpu.py", line 652, in execute
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:     implementation(*instruction.operands)
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:   File "/path/virtualenv/local/lib/python2.7/site-packages/manticore/core/cpu/abstractcpu.py", line 811, in new_method
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR:     return old_method(cpu,*args,**kw_args)
2017-06-16 17:11:00,402: [8221][0] EXECUTOR:ERROR: TypeError: MOV() takes exactly 3 arguments (4 given)
```

### Any relevant logs

**Comment by japesinator** [comment]
https://github.com/aquynh/capstone/issues/950
