### ISSUE TITLE
`state.generate_inputs()` broken

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#378]
`state.generate_inputs` crashes because there is no `state.co` for the state id anymore.

```
2017-07-10 16:42:02,835: [85802] EXECUTOR:ERROR: Exception: 'State' object has no attribute 'co'
Traceback (most recent call last):
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 463, in run
    if not current_state.execute():
  File "/mnt/hgfs/code/manticore/manticore/core/state.py", line 119, in execute
    result = self.platform.execute()
  File "/mnt/hgfs/code/manticore/manticore/platforms/linux.py", line 1803, in execute
    self.current.execute()
  File "/mnt/hgfs/code/manticore/manticore/core/cpu/abstractcpu.py", line 735, in execute
    self.will_execute_instruction(instruction)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 77, in __call__
    return self.emit(*args, **kwargs)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 99, in emit
    results.append(f(obj, *args, **kwargs))
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 99, in emit
    results.append(f(obj, *args, **kwargs))
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 99, in emit
    results.append(f(obj, *args, **kwargs))
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 138, in <lambda>
    method = MethodType(lambda *args, **kwargs: self.emit(*args, **kwargs), obj)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 99, in emit
    results.append(f(obj, *args, **kwargs))
  File "/mnt/hgfs/code/manticore/manticore/manticore.py", line 898, in _hook_callback
    cb(state)
  File "lads-baby-re.py", line 27, in myhook
    state.generate_inputs(m.workspace)
  File "/mnt/hgfs/code/manticore/manticore/core/state.py", line 323, in generate_inputs
    smtfile = 'state_{:08x}.smt'.format(self.co)
AttributeError: 'State' object has no attribute 'co'

```

**Comment by mossberg** [comment]
More discussion about this in #373

**Comment by japesinator** [comment]
`get_inputs` is deprecated in favor of the new `ManticoreOutput` features as of #385

**Comment by mossberg** [comment]
how would one use `ManticoreOutput` instead of `state.generate_inputs`? is there an external interface defined?

**Comment by feliam** [comment]
ManticoreOutput should be mostly dismantled and all of the platform specific functionality in there should be moved to each platform. Or plugin or somewhere else.

**Comment by japesinator** [comment]
Right now a user would do something like `m._output.save_testcase(state)`, but I'm definitely open to adding a more convenient API

**Comment by feliam** [comment]
Maybe state should have a "generate_testcase/make_report" that takes a workspace/output object and generates all the files they want ?

**Comment by mossberg** [comment]
#438
