### ISSUE TITLE
32 bit ELF not parsed correctly

### ISSUE THREAD

**Issue by sinaelgl** [trailofbits/manticore#379]
### OS / Environment

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (n/a)
Release:	9.0
Codename:	n/a

### Python version

Python 2.7.12+

### Summary of the problem
Some 32 bit binaries crash manticore. I compiled the same source for 32 and 64 and the 64 version generates correct input under manticore but the 32 version just errors out.

[binary.zip](https://github.com/trailofbits/manticore/files/1138196/binary.zip)

### Step to reproduce the behavior
unzip binary.zip
manticore ./hash1_gcc49_32

### Expected behavior
$ manticore ./hash1_gcc6_64 
2017-07-11 11:26:51,840: [14851] MANTICORE:INFO: Loading program ./hash1_gcc6_64
2017-07-11 11:26:52,951: [14851] MANTICORE:INFO: Starting 1 processes.
2017-07-11 11:27:51,550: [14882] EXECUTOR:INFO: Generating testcase No. 1 - Program finished with exit status: 0L
2017-07-11 11:27:52,913: [14882] EXECUTOR:INFO: Generating testcase No. 2 - Program finished with exit status: 0L
2017-07-11 11:28:31,458: [14882] EXECUTOR:INFO: Generating testcase No. 3 - Program finished with exit status: 0L
2017-07-11 11:28:32,067: [14851] MANTICORE:WARNING: Using shared context without a lock
2017-07-11 11:28:32,081: [14851] MANTICORE:INFO: Results in example/mcore_EBOvrw
2017-07-11 11:28:32,081: [14851] MANTICORE:INFO: Instructions executed: 308358
2017-07-11 11:28:32,081: [14851] MANTICORE:INFO: Coverage: 8549 different instructions executed
2017-07-11 11:28:32,081: [14851] MANTICORE:INFO: Total time: 99.1297779083
2017-07-11 11:28:32,082: [14851] MANTICORE:INFO: IPS: 3110

### Actual behavior
$ manticore ./hash1_gcc49_32
2017-07-11 11:30:21,265: [15023] MANTICORE:INFO: Loading program ./hash1_gcc49_32
2017-07-11 11:30:22,344: [15023] MANTICORE:INFO: Starting 1 processes.
2017-07-11 11:30:26,051: [15054] EXECUTOR:ERROR: Exception: 'NoneType' object has no attribute 'stat'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.2-py2.7.egg/manticore/core/executor.py", line 463, in run
    if not current_state.execute():
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.2-py2.7.egg/manticore/core/state.py", line 119, in execute
    result = self.platform.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.2-py2.7.egg/manticore/platforms/linux.py", line 1810, in execute
    self.syscall()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.2-py2.7.egg/manticore/platforms/linux.py", line 1655, in syscall
    return self._syscall_abi.invoke(implementation)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.2-py2.7.egg/manticore/core/cpu/abstractcpu.py", line 312, in invoke
    result = model(*argument_tuple)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.2-py2.7.egg/manticore/platforms/linux.py", line 1955, in sys_stat64
    return self._stat(path, buf, True)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.2-py2.7.egg/manticore/platforms/linux.py", line 1963, in _stat
    ret = self.sys_fstat64(fd, buf)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.2-py2.7.egg/manticore/platforms/linux.py", line 1909, in sys_fstat64
    stat = self.files[fd].stat()
AttributeError: 'NoneType' object has no attribute 'stat'

2017-07-11 11:30:26,065: [15023] MANTICORE:WARNING: Using shared context without a lock
2017-07-11 11:30:26,069: [15023] MANTICORE:INFO: Results in example/mcore_JjHBRQ
2017-07-11 11:30:26,070: [15023] MANTICORE:INFO: Instructions executed: 3979
2017-07-11 11:30:26,070: [15023] MANTICORE:INFO: Coverage: 2504 different instructions executed
2017-07-11 11:30:26,070: [15023] MANTICORE:INFO: Total time: 3.7251329422
2017-07-11 11:30:26,070: [15023] MANTICORE:INFO: IPS: 1068

**Comment by japesinator** [comment]
As of #384, we've at least fixed the crash when trying to `fstat`

**Comment by sinaelgl** [comment]
Yup. All good now.
