### ISSUE TITLE
Scripting with DECREE binaries is broken

### ISSUE THREAD

**Issue by japesinator** [trailofbits/manticore#401]
```
from manticore import Manticore

m = Manticore('binaries/CADET_00001') # Any DECREE binary will work here
m.run()

...

Traceback (most recent call last):
  File "cb.py", line 4, in <module>
    m.run()
  File "/home/jp/manticore/manticore/manticore.py", line 695, in run
    initial_state = self._make_state(self._binary)
  File "/home/jp/manticore/manticore/manticore.py", line 393, in _make_state
    state = makeDecree(self._args)
  File "/home/jp/manticore/manticore/manticore.py", line 33, in makeDecree
    platform = decree.SDecree(constraints, ','.join(args.programs))
AttributeError: 'list' object has no attribute 'programs'
```

**Comment by japesinator** [comment]
Worth noting: `manticore binaries/CADET_00001` from the CLI works fine, it's just the API that doesn't work
