### ISSUE TITLE
workspace._create_store error message bug

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#435]
This is the output from using an invalid workspace string; 

```
[I] mark ubuntu /m/h/c/m/e/linux (dev-s) ❯ manticore --workspace mexm: basic
2017-08-04 18:04:07,511: [117829] MANTICORE:INFO: Loading program basic
Traceback (most recent call last):
  File "/home/mark/.local/bin/manticore", line 9, in <module>
    load_entry_point('manticore', 'console_scripts', 'manticore')()
  File "/mnt/hgfs/code/manticore/manticore/__main__.py", line 115, in main
    m.run(args.procs, args.timeout)
  File "/mnt/hgfs/code/manticore/manticore/manticore.py", line 708, in run
    self._output = ManticoreOutput(ws_path)
  File "/mnt/hgfs/code/manticore/manticore/core/workspace.py", line 403, in __init__
    self._store = _create_store(desc)
  File "/mnt/hgfs/code/manticore/manticore/core/workspace.py", line 312, in _create_store
    raise NotImplementedError("Storage type '%s' not supported.", type)
NotImplementedError: ("Storage type '%s' not supported.", <type 'type'>)
```

`NotImplementedError: ("Storage type '%s' not supported.", <type 'type'>)` should be something like `NotImplementedError: ("Storage type 'memx' not supported.")`

It's due to `workspace.py:_create_store` having a typo where `type` was used instead of `type_`, and also `NotImplementedError` not doing string interpolation with its arguments

https://github.com/trailofbits/manticore/blob/af3020db957ff83b66e1474498bdb6be060ddab9/manticore/core/workspace.py#L312

**Comment by mossberg** [comment]
#437
