### ISSUE TITLE
cPickle not installed for python3

### ISSUE THREAD

**Issue by lucasduffey** [trailofbits/manticore#470]
### OS / Environment
Ubuntu 16 LTS

Instructions @ https://github.com/trailofbits/manticore/blob/master/README.md say to get manicore using pip, the following error happens when running `manticore basic`. I think you're supposed to use the `six` library for python3 code.

```
> manticore basic
Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 9, in <module>
    load_entry_point('manticore==0.1.4', 'console_scripts', 'manticore')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/manticore/__init__.py", line 1, in <module>
    from .manticore import Manticore
  File "/usr/local/lib/python3.5/dist-packages/manticore/manticore.py", line 19, in <module>
    from .core.executor import Executor
  File "/usr/local/lib/python3.5/dist-packages/manticore/core/executor.py", line 3, in <module>
    import cPickle
ImportError: No module named 'cPickle'

```

**Comment by lucasduffey** [comment]
This doesn't apply to the master github, but it might be helpful to push the fix to pip

**Comment by mossberg** [comment]
hey! thanks a lot for filing the issue, it looks like you're using python 3.5 but manticore is unfortunately python 2.7 only at the moment :(
