### ISSUE TITLE
Assertion fails: assert brk > self.elf_brk

### ISSUE THREAD

**Issue by 251** [trailofbits/manticore#479]
### OS / Environment
Docker: Ubuntu 16.04

Compiler:
gcc 6.4.0
glibc 2.25

**(works for default glibc and gcc 5.4)**

### Manticore version
Version: 0.1.4

### Python version
Python 2.7.12

### Dependencies
capstone==3.0.5rc2
manticore==0.1.4
ply==3.10
pyelftools==0.24
unicorn==1.0.1

### Summary of the problem
Manticore throws assertion:
```
2017-09-06 10:47:17,757: [305] MANTICORE:INFO: Starting 1 processes.
2017-09-06 10:47:17,766: [343] MANTICORE:INFO: load state 0
2017-09-06 10:47:20,770: [343] EXECUTOR:ERROR: Exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 451, in run
    if not current_state.execute():
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/state.py", line 129, in execute
    result = self._platform.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore/platforms/linux.py", line 1935, in execute
    self.syscall()
  File "/usr/local/lib/python2.7/dist-packages/manticore/platforms/linux.py", line 1780, in syscall
    return self._syscall_abi.invoke(implementation)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/cpu/abstractcpu.py", line 314, in invoke
    result = model(*argument_tuple)
  File "/usr/local/lib/python2.7/dist-packages/manticore/platforms/linux.py", line 1199, in sys_brk
    assert brk > self.elf_brk
AssertionError
```

### Step to reproduce the behavior
Run the following statically linked program with manticore (see attached file).

```C
#include <stdio.h>

int main(int argc, char * argv[]) {
	if (argc != 2) return 1;

	FILE * fp = fopen(argv[1], "r");
	if (fp == NULL) return 2;

	char c;
	if (fread(&c, 1, 1, fp) != 1) return 3;
	if (fclose(fp)) return 4;

	if (c == '7') {
		puts("Found a 7!");
	} else {
		puts("No luck today...");
		return 5;
	}
}
```

```bash
> manticore --file input.sym symfile input.sym
```

### Expected behavior
Run successfully and create 2 test cases.

### Actual behavior
Fails with assertion.

[src.zip](https://github.com/trailofbits/manticore/files/1280821/src.zip)

**Comment by mossberg** [comment]
I think we've refactored the linux elf loader more recently than the sys_brk syscall, so I wonder if those two got out of sync in the refactor. Perhaps this assert is no longer sensical, I wonder what simply commenting it out would do...
