### ISSUE TITLE
AttributeError: 'BoolConstant' object has no attribute 'operands'

### ISSUE THREAD

**Issue by 251** [trailofbits/manticore#485]
### OS / Environment
Docker: Ubuntu 16.04

### Manticore version
Version: 0.1.4

### Python version
Python 2.7.12

### Dependencies
capstone==3.0.5rc2
manticore==0.1.4
ply==3.10
pyelftools==0.24
unicorn==1.0.1### OS / Environment

### Summary of the problem
Manticore fails with exception:
```
EXECUTOR:ERROR: Exception: 'BoolConstant' object has no attribute 'operands'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 466, in run
    self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 379, in fork
    solutions = state.concretize(expression, policy)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/state.py", line 292, in concretize
    silent=False)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/solver.py", line 346, in get_all_values
    temp_cs.add(var==expression)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/constraints.py", line 51, in add
    constraint = arithmetic_simplifier(constraint)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 472, in arithmetic_simplifier
    simp.visit(expression, use_fixed_point=True)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 90, in visit
    value = self._method(new_node, *operands)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 58, in _method
    value = getattr(self, methodname)(expression, *args)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 316, in visit_Operation
    if self._changed(expression, operands):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 310, in _changed
    return any( operands[i] is not expression.operands[i] for i in range(arity))
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 310, in <genexpr>
    return any( operands[i] is not expression.operands[i] for i in range(arity))
AttributeError: 'BoolConstant' object has no attribute 'operands'
```
`expression` is `True` in:
```Python
    @staticmethod
    def _changed(expression, operands):
        arity = len(operands)
        return any( operands[i] is not expression.operands[i] for i in range(arity))
```

**Comment by mossberg** [comment]
Hm, this is an interesting bug, thanks for reporting 👍  any chance you could provide the binary?

**Comment by 251** [comment]
Sure, you can find the Docker image here https://hub.docker.com/r/0251/reports/tags/ (manticore-485). The manticore and Z3 sources are in `/src`. This bug gets my personal wtf-of-the-month award. It fails after copying the binary (again linking related?) during the constraint optimisation?!

```
> docker run --cap-add SYS_PTRACE -it manticore-485 bash
# mkdir test
# cd test
# /data/x86_64-unknown-linux-gnu/secret-g3-O0-s0-d mysecret
Found "secret"!
# /data/x86_64-unknown-linux-gnu/secret-g3-O0-s0-d foo
# manticore /data/x86_64-unknown-linux-gnu/secret-g3-O0-s0-d ++++++++
[works]
# cp /data/x86_64-unknown-linux-gnu/secret-g3-O0-s0-d .
# ./secret-g3-O0-s0-d mysecret
Found "secret"!
# manticore ./secret-g3-O0-s0-d ++++++++
2017-09-08 12:46:28,304: [230] MANTICORE:INFO: Loading program ./secret-g3-O0-s0-d (platform: Linux)
2017-09-08 12:46:29,044: [230] MANTICORE:INFO: Starting 1 processes.
2017-09-08 12:46:29,054: [268] MANTICORE:INFO: load state 0
2017-09-08 12:47:24,184: [268] MANTICORE:INFO: load state 1
2017-09-08 12:47:24,452: [268] MANTICORE:INFO: load state 2
2017-09-08 12:47:25,484: [268] MANTICORE:INFO: load state 3
2017-09-08 12:47:25,710: [268] MANTICORE:INFO: load state 4
2017-09-08 12:47:25,945: [268] MANTICORE:INFO: load state 5
2017-09-08 12:47:25,957: [268] EXECUTOR:ERROR: Exception: 'BoolConstant' object has no attribute 'operands'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 466, in run
    self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 379, in fork
    solutions = state.concretize(expression, policy)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/state.py", line 292, in concretize
    silent=False)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/solver.py", line 346, in get_all_values
    temp_cs.add(var==expression)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/constraints.py", line 51, in add
    constraint = arithmetic_simplifier(constraint)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 472, in arithmetic_simplifier
    simp.visit(expression, use_fixed_point=True)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 90, in visit
    value = self._method(new_node, *operands)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 58, in _method
    value = getattr(self, methodname)(expression, *args)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 316, in visit_Operation
    if self._changed(expression, operands):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 310, in _changed
    return any( operands[i] is not expression.operands[i] for i in range(arity))
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/visitors.py", line 310, in <genexpr>
    return any( operands[i] is not expression.operands[i] for i in range(arity))
AttributeError: 'BoolConstant' object has no attribute 'operands'

2017-09-08 12:47:26,024: [230] MANTICORE:INFO: Results in /test/mcore_eHloyI
2017-09-08 12:47:26,024: [230] MANTICORE:INFO: Instructions executed: 149551
2017-09-08 12:47:26,024: [230] MANTICORE:INFO: Coverage: 7058 different instructions executed
2017-09-08 12:47:26,024: [230] MANTICORE:INFO: Total time: 56.9794631004
2017-09-08 12:47:26,024: [230] MANTICORE:INFO: IPS: 2624
```
