### ISSUE TITLE
Fix pdb support in hooks

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#49]
It would be useful to be able to drop into pdb inside a hook, especially for a new user. Right now, we get an error. It's related to our use of multiprocessing somehow. 

```
2017-03-06 12:02:25,464: [94843][0] EXECUTOR:ERROR: THIS SHOULD NOT REACHABLE! Exception in user code:
Traceback (most recent call last):
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 875, in run
    self.will_execute_pc(current_state, current_state.cpu.PC)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 31, in __call__
    return self.emit(*args, **kwargs)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 48, in emit
    results.append(f(obj, *args, **kwargs))
  File "/mnt/hgfs/code/manticore/manticore/manticore.py", line 617, in _hook_callback
    cb(state)
  File "statemachine_eval.py", line 35, in check_tainted_cmp
    insn = state.cpu.instruction
  File "statemachine_eval.py", line 35, in check_tainted_cmp
    insn = state.cpu.instruction
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit

```

**Comment by yan** [comment]
This works if running with `procs=1`. I say we document this on the wiki and close the issue.

**Comment by mossberg** [comment]
Agreed, feel free to do that @yan!

**Comment by yan** [comment]
Documented here: https://github.com/trailofbits/manticore/wiki/Hacking-on-Manticore#using-pdb
