### ISSUE TITLE
missing system dependency

### ISSUE THREAD

**Issue by niph** [trailofbits/manticore#496]
### OS / Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

### Manticore version
Version: 0.1.4

### Python version
Python 2.7.12

### Summary of the problem
When installing manticore on a fresh ubuntu server via pip the following error is encountered:
```python 
root@ubuntu $ manticore
Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 7, in <module>
    from manticore.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/manticore/__init__.py", line 1, in <module>
    from .manticore import Manticore
  File "/usr/local/lib/python2.7/dist-packages/manticore/manticore.py", line 19, in <module>
    from .core.executor import Executor
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 14, in <module>
    from .smtlib import solver, Expression, SolverException
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/__init__.py", line 4, in <module>
    from solver import *
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/solver.py", line 500, in <module>
    solver = Z3Solver()
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/solver.py", line 122, in __init__
    self.version = self._solver_version()
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/solver.py", line 155, in _solver_version
    raise Z3NotFoundError
manticore.core.smtlib.solver.Z3NotFoundError
```

### Solution
install z3 via 
`sudo apt install z3`

please add z3 to the system dependencies.

**Comment by mossberg** [comment]
Hi niph, we recently updated our install so z3 will also get installed by pip. What was the exact command you used to install manticore? Thanks for reporting!

**Comment by niph** [comment]
Hi,

I installed it as described under the "Quick Start" section of the readme and without virtual env. 
I tried it again with virtualenv as described in the readme. 

Heres the output of `pip freeze`
```
capstone==3.0.5rc2
manticore==0.1.4
ply==3.10
pyelftools==0.24
unicorn==1.0.1
```

**Comment by mossberg** [comment]
Ah, I see. We've updated master such that z3 will get auto installed, but those changes have not yet made it to pypi (and the quick start instruction say to install from pypi). We're planning to push to pypi this friday, though. So in summary, the quick start is very briefly out of date until friday, since until then separate z3 install is required. Sorry you ran into this and thanks again for trying manticore!

**Comment by niph** [comment]
Unfortunate timing but not too much of an issue at all. Thanks anyway for the awesome work and the quick response.
