### ISSUE TITLE
Unhandled exception: need more than 2 values to unpack

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#516]
### OS / Environment

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

### Manticore version

Last revision (1edee15)

### Python version

Python 2.7.12

### Summary of the problem

Unhandled exception: need more than 2 values to unpack

### Step to reproduce the behavior

$ timeout 600 manticore --policy uncovered --procs 10 CROMU_00070

### Expected behavior

It shouldn't crash.

### Actual behavior

2017-10-04 03:48:44,445: [7853] m.c.executor:ERROR: Exception: need more than 2 values to unpack Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/core/executor.py", line 497, in run
    self.generate_testcase(current_state, current_state_id, str(e))
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/core/executor.py", line 363, in generate_testcase
    self.publish('will_generate_testcase', state, 'test', message)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/utils/event.py", line 54, in publish
    callback(robj(), *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/manticore.py", line 544, in _generate_testcase_callback
    testcase_id = self._output.save_testcase(state, name, message)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/core/workspace.py", line 463, in save_testcase
    self.save_fds(state)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/core/workspace.py", line 540, in save_fds
    for name, fd, data in state.platform.syscall_trace:
ValueError: need more than 2 values to unpack

**Comment by ggrieco-tob** [comment]
This was my fault. I did a commit in my branch that changed how the syscall traces are created.
