### ISSUE TITLE
Unhandled exception: Set_brk can never work. avoid overflows

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#517]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (e84c0513a2d850e3fe63bd23425d7ba67a88c7dc)

### Python version

Python 2.7.13

### Summary of the problem

Unhandled exception: Set_brk can never work. avoid overflows

### Step to reproduce the behavior

$ ./examples/script/count_instructions.py KPRCA_00091

using the pre-compiled CGC binary.

### Expected behavior

It shouldn't crash.

### Actual behavior

```
Traceback (most recent call last):
  File "./examples/script/count_instructions.py", line 19, in <module>
    m = Manticore(sys.argv[1])
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/manticore.py", line 203, in __init__
    self._initial_state = make_initial_state(path_or_state, argv=argv, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/manticore.py", line 162, in make_initial_state
    state = make_decree(binary_path, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/manticore.py", line 63, in make_decree
    platform = decree.SDecree(constraints, program)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/platforms/decree.py", line 901, in __init__
    super(SDecree, self).__init__(programs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/platforms/decree.py", line 129, in __init__
    self.procs += self.load(program)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.4-py2.7.egg/manticore/platforms/decree.py", line 265, in load
    raise Exception("Set_brk can never work. avoid overflows")
Exception: Set_brk can never work. avoid overflows
```

**Comment by yan** [comment]
Hasn't been repeated since and issue is in infrequently used code; closing for now.
