### ISSUE TITLE
NotEnoughGas() error

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#539]
### OS / Environment
ArchLinux

### Manticore version

baf2d769a624306f91fcca44bcff0b087f1bba69

### Python version

2.7

### Summary of the problem

OverflowError: range() result has too many items

### Step to reproduce the behavior

I'm using [this script](https://gist.github.com/ggrieco-tob/3f3491956197e8ba19f88694af803bab) to test manticore.

$ ./evm.py [QuickFuzz.77531397969.8.2584411545759619119.8.evm.txt](https://github.com/trailofbits/manticore/files/1423541/QuickFuzz.77531397969.8.2584411545759619119.8.evm.txt)

### Expected behavior

It shouldn't crash.

### Actual behavior

Traceback (most recent call last):
  File "./evm.py", line 27, in <module>
    evm.execute() 
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 841, in execute
    result = implementation(*arguments)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 1272, in LOG
    for i in range(size):
OverflowError: range() result has too many items

**Comment by mossberg** [comment]
I had to modify the script to remove the decoder variable, and with that I get a different error now. the very very large number is the gas fee, so maybe have a bug in gas computation now

```
('gass', 999999999999999994501L, 1125)
('gass', 999999999999999993376L, 2973045232150670200470240862555434337053822967392598187923008654603230507261251822123788090559402886947795738993426183159707836886250726928660037668L)
Traceback (most recent call last):
  File "xx.py", line 27, in <module>
    evm.execute()
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1374, in execute
    result = implementation(*arguments)
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1104, in wrapper
    return func(*args, **kwargs)
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1820, in LOG
    memlog = self.read_buffer(address, size)
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1829, in read_buffer
    self._allocate(offset + size)
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1242, in _allocate
    self._consume(fee)
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1325, in _consume
    raise NotEnoughGas()
manticore.platforms.evm.NotEnoughGas
```

```
#!/usr/bin/env python2

from sys import argv
from manticore.core.smtlib.constraints import ConstraintSet
from manticore.platforms.evm import *

# decoder = EVMDecoder()
bytecode = open(argv[1]).read()

address=0x414141414141
origin=0x424242424242
price=1
data='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
sender=0x434343434343
value=1
header={ 'coinbase': 0, 'timestamp': 0,
         'number': 0, 'difficulty': 0, 'gaslimit': 0,}
depth=0
gas=1000000000000000000000

constraints = ConstraintSet()
world = EVMWorld(constraints)

evm = EVM(constraints, address, origin, price, data, sender, value, bytecode, header,  gas=gas, global_storage=world.storage )

while True:
    evm.execute()

```

**Comment by mossberg** [comment]
going to close, we'll make a new issue if it comes up again
