### ISSUE TITLE
IndexError: string index out of range in Operators.ORD 

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#540]
### OS / Environment
ArchLinux

### Manticore version

baf2d769a624306f91fcca44bcff0b087f1bba69

### Python version

2.7

### Summary of the problem

IndexError: string index out of range in Operators.ORD 

### Step to reproduce the behavior

I'm using [this script](https://gist.github.com/ggrieco-tob/3f3491956197e8ba19f88694af803bab) to test manticore.

$ ./evm.py [QuickFuzz.77531397969.93.4960641244607630411.43.evm.txt](https://github.com/trailofbits/manticore/files/1423557/QuickFuzz.77531397969.93.4960641244607630411.43.evm.txt)

### Expected behavior

It shouldn't crash.

### Actual behavior

Traceback (most recent call last):
  File "./evm.py", line 27, in <module>
    evm.execute() 
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 841, in execute
    result = implementation(*arguments)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 1127, in CODECOPY
    self._store(mem_offset+i, Operators.ORD(self.bytecode[code_offset+i]))
IndexError: string index out of range

**Comment by yan** [comment]
This was fixed by #812
