### ISSUE TITLE
TypeError: __init__() takes exactly 4 arguments (3 given) in Create

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#542]
### OS / Environment
ArchLinux

### Manticore version

baf2d769a624306f91fcca44bcff0b087f1bba69

### Python version

2.7

### Summary of the problem

TypeError: __init__() takes exactly 4 arguments (3 given) in Create

### Step to reproduce the behavior

I'm using [this script](https://gist.github.com/ggrieco-tob/3f3491956197e8ba19f88694af803bab) to test manticore.

$ ./evm.py [QuickFuzz.78967239524.248.3345212657083696171.48.evm.txt](https://github.com/trailofbits/manticore/files/1423577/QuickFuzz.78967239524.248.3345212657083696171.48.evm.txt)

### Expected behavior

It shouldn't crash.

### Actual behavior

Traceback (most recent call last):
  File "./evm.py", line 27, in <module>
    evm.execute() 
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 841, in execute
    result = implementation(*arguments)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 1296, in CREATE
    raise Create(value, code)
TypeError: __init__() takes exactly 4 arguments (3 given)

**Comment by mossberg** [comment]
i get this now, and i believe it's correct behavior, so i'll close this
```
Traceback (most recent call last):
  File "542.py", line 26, in <module>
    evm.execute()
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1374, in execute
    result = implementation(*arguments)
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1851, in CREATE
    raise Create(value, code)
manticore.platforms.evm.Create
```
