### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'runtime_bytecode'

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#546]
### OS / Environment
ArchLinux

### Manticore version

baf2d769a624306f91fcca44bcff0b087f1bba69

### Python version

2.7

### Summary of the problem

TypeError: _hook_callback() when you try to hook every instruction executed in a smart contract.

### Step to reproduce the behavior

Execute this script from the examples/evm folder:

```
from seth import *

seth = ManticoreEVM()
seth.verbosity(3)
user_account = seth.create_account(balance=1000)

bytecode = '`'
#Initialize contract
contract_account = seth.create_contract(owner=user_account, 
                                          balance=0, 
                                          init=bytecode)

def explore(state):
    pass

seth.add_hook(None, explore)
seth.transaction(  caller=user_account,
                    address=contract_account,
                    value=None,
                    data='',
                 )
```

### Expected behavior

It shouldn't crash.

### Actual behavior

```2017-11-06 17:01:06,960: [25750] m.manticore:INFO: Starting 1 processes.
2017-11-06 17:01:06,963: [25750] m.c.executor:INFO: load state 0
2017-11-06 17:01:06,969: [25750] m.manticore:INFO: Results in /home/g/Work/Code/manticore/examples/evm/mcore_YLgrYD
2017-11-06 17:01:06,970: [25750] m.manticore:INFO: Total time: 0.00987696647644
2017-11-06 17:01:06,972: [25750] m.manticore:INFO: Starting 1 processes.
2017-11-06 17:01:06,975: [25750] m.c.executor:INFO: load state 2
2017-11-06 17:01:07,016: [25750] m.c.executor:ERROR: Exception: _hook_callback() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 456, in run
    if not current_state.execute():
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 1544, in execute
    self.current.execute()
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 814, in execute
    self._publish( 'will_execute_instruction', current)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 117, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 133, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 133, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 131, in _publish_impl
    sink._publish_impl(_name, self, *args, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 125, in _publish_impl
    callback(robj(), *args, **kwargs)
TypeError: _hook_callback() takes exactly 4 arguments (3 given)

Exception: _hook_callback() takes exactly 4 arguments (3 given)
Traceback (most recent call last):
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 456, in run
    if not current_state.execute():
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 1544, in execute
    self.current.execute()
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 814, in execute
    self._publish( 'will_execute_instruction', current)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 117, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 133, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 133, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 131, in _publish_impl
    sink._publish_impl(_name, self, *args, **kwargs)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 125, in _publish_impl
    callback(robj(), *args, **kwargs)
TypeError: _hook_callback() takes exactly 4 arguments (3 given)

2017-11-06 17:01:07,021: [25750] m.manticore:INFO: Results in /home/g/Work/Code/manticore/examples/evm/mcore_YLgrYD
2017-11-06 17:01:07,021: [25750] m.manticore:INFO: Total time: 0.0484938621521
```

**Comment by mossberg** [comment]
now i get this kind of error

```
2018-03-23 17:55:01,911: [67117] m.c.plugin:INFO: Instructions executed: 7
2018-03-23 17:55:01,913: [67117] m.c.plugin:INFO: Coverage: 2 different instructions executed
Traceback (most recent call last):
  File "546.py", line 20, in <module>
    data='',
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 917, in transaction
    self.completed_transactions, self.global_coverage(address), len(self.terminated_state_ids), len(self.running_state_ids))
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 1452, in global_coverage
    runtime_bytecode = self.get_metadata(account_address).runtime_bytecode
AttributeError: 'NoneType' object has no attribute 'runtime_bytecode'
```

updated script

```
from manticore.ethereum import ManticoreEVM

seth = ManticoreEVM()
seth.verbosity(3)
user_account = seth.create_account(balance=1000)

bytecode = '`'
#Initialize contract
contract_account = seth.create_contract(owner=user_account,
                                          balance=0,
                                          init=bytecode)

def explore(state):
    pass

seth.add_hook(None, explore)
seth.transaction(  caller=user_account,
                    address=contract_account,
                    value=None,
                    data='',
                 )
```

**Comment by defunctio** [comment]
Updated script for python3, appears this issue is resolved. 

```
from manticore.ethereum import ManticoreEVM

seth = ManticoreEVM()
seth.verbosity(3)
user_account = seth.create_account(balance=1000)

bytecode = b'`'
# Initialize contract
contract_account = seth.create_contract(owner=user_account,
                                        balance=0,
                                        init=bytecode)


def explore(state):
    pass


seth.add_hook(None, explore)
seth.transaction(caller=user_account,
                 address=contract_account,
                 value=seth.constraints.new_bitvec(256),
                 data=b'',
                 )
```
