### ISSUE TITLE
Exception: MOV() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#548]
### OS / Environment
ArchLinux

### Manticore version

baf2d769a624306f91fcca44bcff0b087f1bba69

### Python version

2.7

### Summary of the problem

ERROR: Exception: MOV() takes at least 3 arguments (2 given)

### Step to reproduce the behavior

```
manticore KPRCA_00015
```

where KPRCA_00015 is the corresponding CGC binary

### Expected behavior

It shouldn't crash.

### Actual behavior

```
2017-11-07 16:29:44,188: [28417] m.manticore:INFO: Loading program /home/gustavo/data/challenges/KPRCA_00015
2017-11-07 16:29:44,216: [28417] m.manticore:INFO: Starting 1 processes.
2017-11-07 16:29:44,272: [28417] m.c.executor:ERROR: Exception: MOV() takes at least 3 arguments (2 given)
Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 456, in run
    if not current_state.execute():
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/decree.py", line 875, in execute
    self.current.execute()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/cpu/abstractcpu.py", line 767, in execute
    implementation(*insn.operands)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/cpu/abstractcpu.py", line 841, in new_method
    return old_method(cpu, *args, **kw_args)
TypeError: MOV() takes at least 3 arguments (2 given)

Exception: MOV() takes at least 3 arguments (2 given)
Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 456, in run
    if not current_state.execute():
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/decree.py", line 875, in execute
    self.current.execute()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/cpu/abstractcpu.py", line 767, in execute
    implementation(*insn.operands)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/cpu/abstractcpu.py", line 841, in new_method
    return old_method(cpu, *args, **kw_args)
TypeError: MOV() takes at least 3 arguments (2 given)

2017-11-07 16:29:44,274: [28417] m.manticore:INFO: Results in /home/gustavo/mcore_3CxmG2
2017-11-07 16:29:44,275: [28417] m.manticore:INFO: Total time: 0.0582880973816
```

**Comment by ggrieco-tob** [comment]
This issues seems to be caused by a capstone bug where it reports that:

```
mov	al, byte ptr [0x805e240]
```

contains only one operand. To reproduce it:

```
from capstone import *
md = Cs(CS_ARCH_X86, CS_MODE_32)
md.detail = True
insn = md.disasm(b"\xa0@\xe2\x05\x08", 0x1000).next()
print insn.op_str
print len(insn.operands)
```
and it outputs:

```
al, byte ptr [0x805e240]
1
```

Related issues are:
* https://github.com/aquynh/capstone/issues/950
* https://github.com/trailofbits/manticore/issues/309

**Comment by ggrieco-tob** [comment]
https://github.com/zardus/cgc-bins/blob/master/all_unpatched/KPRCA_00015?raw=true

**Comment by catenacyber** [comment]
@ggrieco-tob thanks

I confirm that the bug is no longer present with capstone next branch (4.0.0rc1)

So, should a workaround be done for this case ? Or support capstone next branch ? Or just wait for capstone 4.0.0 package release ?
see #852 for the discussion so far

**Comment by mossberg** [comment]
closing for now. we have some stuff in the faq for easily installing capstone's next version which will help with this
