### ISSUE TITLE
Issue with storing symbols in context dictionary.

### ISSUE THREAD

**Issue by pgoodman** [trailofbits/manticore#566]
### OS / Environment
Ubuntu 16.04

### Manticore version
master

### Python version
2.7

### Issue
Running DeepState's Manticore program raises several exception which shouldn't happen. One of the problems is somehow related to storing symbols in the `context` dictionary, and perhaps improper deep copying of these values. If the usage is actually improper then my use case deserves a "gotcha" message on Manticore's docs.

```
pag@sloth:~/Code/deepstate/build$ deepstate ./examples/IntegerArtihmetic 
2017-11-06 13:57:48,362: [28658] m.manticore:INFO: Starting 1 processes.
2017-11-06 14:02:35,897: [28658] m.c.c.x86:WARNING: CPUID with EAX=80000000 not implemented @ 7fffff821c18
2017-11-06 14:02:45,696: [28658] deepstate.mcore:INFO: Running 3 tests across 1 workers
2017-11-06 14:02:45,970: [29017] m.manticore:INFO: Starting 1 processes.
2017-11-06 14:02:47,020: [29017] m.c.executor:ERROR: Exception: Error in smtlib: (error "line 377 column 43: invalid declaration, constant 'DEEP_INPUT_0_2' (with the given signature) already declared")

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 476, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 119, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 135, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 127, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/deepstate/main_manticore.py", line 218, in done_test
    mc.report()
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 345, in report
    b = self.concretize(symbols[i], constrain=True)
  File "build/bdist.linux-x86_64/egg/deepstate/main_manticore.py", line 91, in concretize
    concrete_val = self.state.solve_one(val)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 309, in solve_one
    return self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 490, in get_value
    if self._check() != 'sat':
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 262, in _check
    _status = self._recv()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 253, in _recv
    raise Exception("Error in smtlib: {}".format(bufl[0]))
Exception: Error in smtlib: (error "line 377 column 43: invalid declaration, constant 'DEEP_INPUT_0_2' (with the given signature) already declared")


Exception: Error in smtlib: (error "line 377 column 43: invalid declaration, constant 'DEEP_INPUT_0_2' (with the given signature) already declared")

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 476, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 119, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 135, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/utils/event.py", line 127, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/deepstate/main_manticore.py", line 218, in done_test
    mc.report()
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 345, in report
    b = self.concretize(symbols[i], constrain=True)
  File "build/bdist.linux-x86_64/egg/deepstate/main_manticore.py", line 91, in concretize
    concrete_val = self.state.solve_one(val)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 309, in solve_one
    return self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 490, in get_value
    if self._check() != 'sat':
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 262, in _check
    _status = self._recv()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 253, in _recv
    raise Exception("Error in smtlib: {}".format(bufl[0]))
Exception: Error in smtlib: (error "line 377 column 43: invalid declaration, constant 'DEEP_INPUT_0_2' (with the given signature) already declared")


2017-11-06 14:02:47,021: [29017] deepstate.mcore:ERROR: State 2 terminated for unknown reason: Error in smtlib: (error "line 377 column 43: invalid declaration, constant 'DEEP_INPUT_0_2' (with the given signature) already declared")

2017-11-06 14:02:47,023: [29017] m.manticore:INFO: Results in /home/pag/Code/deepstate/build/mcore_7mKg5l
2017-11-06 14:02:47,023: [29017] m.manticore:INFO: Total time: 1.052973032
2017-11-06 14:02:47,345: [29017] m.manticore:INFO: Starting 1 processes.
2017-11-06 14:02:47,530: [29017] m.c.executor:ERROR: Exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 471, in run
    self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 381, in fork
    solutions = state.concretize(expression, policy)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 291, in concretize
    silent=False)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 354, in get_all_values
    value = self._getvalue(var)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 293, in _getvalue
    assert ret.startswith('((') and ret.endswith('))')
AssertionError

Exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 471, in run
    self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 381, in fork
    solutions = state.concretize(expression, policy)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 291, in concretize
    silent=False)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 354, in get_all_values
    value = self._getvalue(var)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 293, in _getvalue
    assert ret.startswith('((') and ret.endswith('))')
AssertionError

2017-11-06 14:02:47,531: [29017] deepstate.mcore:ERROR: State 0 terminated for unknown reason: 
2017-11-06 14:02:47,532: [29017] m.manticore:INFO: Results in /home/pag/Code/deepstate/build/mcore_yUsodU
2017-11-06 14:02:47,532: [29017] m.manticore:INFO: Total time: 0.187195062637
2017-11-06 14:02:47,790: [29017] m.manticore:INFO: Starting 1 processes.
2017-11-06 14:02:47,952: [29017] m.c.executor:ERROR: Exception: ((V_8194 #x0000000000402040))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 471, in run
    self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 381, in fork
    solutions = state.concretize(expression, policy)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 291, in concretize
    silent=False)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 353, in get_all_values
    while self._check() == 'sat':
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 265, in _check
    raise SolverException(_status)
SolverException: ((V_8194 #x0000000000402040))

Exception: ((V_8194 #x0000000000402040))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 471, in run
    self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 381, in fork
    solutions = state.concretize(expression, policy)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 291, in concretize
    silent=False)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 353, in get_all_values
    while self._check() == 'sat':
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.5-py2.7.egg/manticore/core/smtlib/solver.py", line 265, in _check
    raise SolverException(_status)
SolverException: ((V_8194 #x0000000000402040))

2017-11-06 14:02:47,952: [29017] deepstate.mcore:ERROR: State 0 terminated for unknown reason: ((V_8194 #x0000000000402040))
2017-11-06 14:02:47,953: [29017] m.manticore:INFO: Results in /home/pag/Code/deepstate/build/mcore_BkGWlh
2017-11-06 14:02:47,953: [29017] m.manticore:INFO: Total time: 0.162762880325
```

**Comment by mossberg** [comment]
I believe this is related to #189 , referring to the double declaration SMT error above:

```
Exception: Error in smtlib: (error "line 377 column 43: invalid declaration, constant 'DEEP_INPUT_0_2' (with the given signature) already declared")

```

**Comment by pgoodman** [comment]
This may be have been resolved by @feliam's change that used `deepcopy` on `state.context`. :-)

**Comment by mossberg** [comment]
ah, right, thanks! @pgoodman can you describe to us how we can reproduce this to test if it's fixed?once we have that, @feliam can you please verify and close this issue if it's fixed? can you also check #189?

**Comment by feliam** [comment]
I'll try to make an unittest for it. Meanwhile one could test it adding this:
```
    def __deepcopy__(self, memo):
        cls = self.__class__
        memo[id(self)] = self
        return self
```
to smtlib/expression/Variable

**Comment by pgoodman** [comment]
So I created a list of symbols with `state.new_symbolic_value`, then I stored them in `state.context['symbols']`. I also wrote the symbols into memory. Then stuff runs, forking happens, and each state should constrain the symbols differently. At the end, I iterate over `state.context['symbols']` in each state and get solutions for them :-)
