### ISSUE TITLE
Memory exception during fallback emu should be handled like normal memory exception

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#592]
If the program crashes during mcore's normal emulator, we detect it, and generate a testcase with an input triggering the crash.

Currently, if the program crashes on an instruction that is handled by the fallback emu (we didn't implement the insn), pending #591 , it would be treated as an `InstructionEmulationError`, which in reality, it should be handled just the case above, and a testcase should be generated.

```
2017-11-22 15:51:07,147: [123423] m.manticore:INFO: Starting 1 processes.
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/mark/.local/lib/python2.7/site-packages/unicorn/unicorn.py", line 401, in _hook_mem_access_cb
    cb(self, access, address, size, value, data)
  File "/mnt/hgfs/code/manticore/manticore/utils/emulate.py", line 98, in _hook_xfer_mem
    self._cpu.write_int(address, value, size*8)
  File "/mnt/hgfs/code/manticore/manticore/core/cpu/abstractcpu.py", line 512, in write_int
    self.memory[where:where+size/8] = [Operators.CHR(Operators.EXTRACT(expression, offset, 8)) for offset in xrange(0, size, 8)]
  File "/mnt/hgfs/code/manticore/manticore/core/memory.py", line 852, in __setitem__
    self.write(index.start, value)
  File "/mnt/hgfs/code/manticore/manticore/core/memory.py", line 1039, in write
    super(SMemory, self).write(address+offset, [value[offset]])
  File "/mnt/hgfs/code/manticore/manticore/core/memory.py", line 830, in write
    raise InvalidMemoryAccess(addr, 'w')
manticore.core.memory.InvalidMemoryAccess: Invalid memory access (mode:w) <fffffff8>
2017-11-22 15:51:09,754: [123423] m.c.executor:ERROR: Exception: global name 'e' is not defined
Traceback (most recent call last):
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 460, in run
    if not current_state.execute():
  File "/mnt/hgfs/code/manticore/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/mnt/hgfs/code/manticore/manticore/platforms/linux.py", line 2058, in execute
    self.current.execute()
  File "/mnt/hgfs/code/manticore/manticore/core/cpu/abstractcpu.py", line 764, in execute
```

[fallback_emu_crash.zip](https://github.com/trailofbits/manticore/files/1497440/fallback_emu_crash.zip)

todo
- first, fix #591 
- not entirely sure, but i think this is what needs to happen: here, https://github.com/trailofbits/manticore/blob/master/manticore/core/cpu/abstractcpu.py#L792, catch the exceptions that emu.emulate() can raise related to bad memory accesses () (as opposed to `Exception`). since these exceptions will ultimately stem from `memory.py` (see trace above), it should be fine to let them bubble up, which should trigger the testcase generation code

**Comment by mossberg** [comment]
this is a bit old and somewhat niche edge case. also not sure how to reproduce anymore, running the binary in manticore seems to work ok. closing.
