### ISSUE TITLE
Unhandled Exception: list index out of range

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#607]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (77b0542b83bce9695aa79d7447aa58f5c056b111)

### Python version

Python 2.7.13

### Summary of the problem

Unhandled exception: list index out of range while manticore executes a CGC binary.

### Step to reproduce the behavior

```
$ manticore all_unpatched/CROMU_00093_4                                                                               
```

using [this pre-compiled CGC binary](https://github.com/zardus/cgc-bins/blob/master/all_unpatched/CROMU_00093_4?raw=true).

### Expected behavior

It shouldn't crash.

### Actual behavior

```
2017-11-30 16:26:14,993: [11929] m.manticore:INFO: Loading program all_unpatched/CROMU_00093_4
2017-11-30 16:26:15,026: [11929] m.manticore:INFO: Starting 1 processes.
2017-11-30 16:26:15,298: [11929] m.c.executor:ERROR: Exception: list index out of range
Traceback (most recent call last):
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 460, in run
    if not current_state.execute():
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/decree.py", line 884, in execute
    self.int80(self.current)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/decree.py", line 749, in int80
    cpu.EAX = func(*args[:nargs-1])
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/decree.py", line 687, in sys_fdwait
    if self.files[fd].is_empty():
IndexError: list index out of range
```

**Comment by bradlarsen** [comment]
This is nearly 3 years old now, and was applicable to Python 2 when reported, which Manticore no longer supports.

I'm closing this issue.  If this problematic behavior still occurs, let's open a new issue for it.
