### ISSUE TITLE
Passing a symbolic value to sys_exit() raises an Exception

### ISSUE THREAD

**Issue by yan** [trailofbits/manticore#613]
### OS / Environment
Ubuntu 16.04

### Manticore version
`master`

### Python version
2.7

### Step to reproduce the behavior
2017-12-01 07:29:11,901: [6492] m.c.executor:ERROR: Exception: an integer is required
Traceback (most recent call last):
  File "/mnt/hgfs/projects/manticore/manticore/core/executor.py", line 460, in run
    if not current_state.execute():
  File "/mnt/hgfs/projects/manticore/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/mnt/hgfs/projects/manticore/manticore/platforms/linux.py", line 2014, in execute
    self.syscall()
  File "/mnt/hgfs/projects/manticore/manticore/platforms/linux.py", line 1859, in syscall
    return self._syscall_abi.invoke(implementation)
  File "/mnt/hgfs/projects/manticore/manticore/core/cpu/abstractcpu.py", line 384, in invoke
    ret = super(SyscallAbi, self).invoke(model, prefix_args)
  File "/mnt/hgfs/projects/manticore/manticore/core/cpu/abstractcpu.py", line 337, in invoke
    result = model(*arguments)
  File "/mnt/hgfs/projects/manticore/manticore/platforms/linux.py", line 1724, in sys_exit_group
    raise TerminateState("Program finished with exit status: %r" % ctypes.c_int32(error_code).value, testcase=True)
TypeError: an integer is required

### Expected behavior
Output suggesting the return value is symbolic; or solve for an exit code.

### Actual behavior
TypeError is raised

**Comment by mossberg** [comment]
imo we should output that the ret value is symbolic. we shouldn't solve for an exit code; this will be somewhat misleading about how the program exited.

**Comment by yan** [comment]
Why not solve at all? Producing a warning that it's symbolic and providing a solution is an option. (If we were to keep it symbolic, we'd have to change how TerminateState is handled). Other system calls like read(2) are more important imho, and we just solve for their arguments.

What benefits will a Manticore user see from maintaining it as an Expression and not solving?

**Comment by mossberg** [comment]
#616
