### ISSUE TITLE
Support EVM in CLI mode

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#630]
The manticore cli mode should support Ethereum smart contracts, written in solidity.

todo
- [x] merge #629 
- [x] implement various analysis plugins corresponding to these issues: https://github.com/trailofbits/not-so-smart-contracts
  - [x] int overflow
  - ~[ ] reentrancy~
  - ~[ ] unchecked external call~
- [x] [UI](https://github.com/orgs/trailofbits/teams/manticore/discussions/3): accept solidity/evm files
- [x] [UI](https://github.com/orgs/trailofbits/teams/manticore/discussions/3): implement workspace files
- [ ] make workspace filenames compatible with ethersplay
- [ ] generate testcase when detectors detect a failure. right now that path will generate a testcase, but it will not specifically trigger the failure condition

**Comment by mossberg** [comment]
currently, the evm cli has enough core functionality for the release. it is unclear if we will have reentrancy or uncheck external call analyses in time, but i think it's fine. since the functionality is there, the remaining required work is related to UI polish and cosmetics

- [ ] show human readable log messsage bytes in ascii (vs hexpair). because you can log a string to conveniently see if a certain contract path was hit
- [ ] clean up stdout output
  - the multiple "Starting 1 processes" thing looks odd. may not be possible to remove this without significant refactoring.
  - it would be nice to print out the statuses of the states as the analysis proceeds
  - we should attempt to make things look as similar as possible to how manticore looks for linux binaries

```
2017-12-15 16:18:53,989: [34451] m.manticore:INFO: Starting 1 processes.
2017-12-15 16:18:54,068: [34451] m.manticore:INFO: Starting 1 processes.
[+] Coverage after 1 transactions: 54%
[+] There are 4 reverted states now
[+] There are 1 alive states now
2017-12-15 16:19:09,978: [34451] m.manticore:INFO: Starting 1 processes.
[+] Coverage after 2 transactions: 100%
[+] There are 8 reverted states now
[+] There are 2 alive states now
[+] Look for results in /mnt/hgfs/code/manticore/examples/evm/mcore_548qV5
```

**Comment by mossberg** [comment]
elaborating on stdout cleanup work:
- we should aim to use logging instead of `print '[+]'`. we can easily move [this code](https://github.com/trailofbits/manticore/blob/master/manticore/__main__.py#L78-L108) into `seth.py` as a method on `ManticoreEVM` in order to have access to the seth logger
- currently logging evm stuff seems a little broken. for example, changing the `logging.info` to `logging.warning` [here](https://github.com/trailofbits/manticore/blob/master/manticore/seth.py#L999) to force it to log shows this error

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 469, in format
    s = self._fmt % record.__dict__
KeyError: 'stateid'
```
- additionally it would be great for the `-vvv` semantics to apply to evm also. (default: testcase messages only basically, -v: state forking info, and platform info, -vv: evm cpu insn info, etc)

**Comment by mossberg** [comment]
added another task above, we should make sure the filenames for the bytecode files are compatible with ethersplay (they must end in .bytecode, rather than .runtime_bytecode)

**Comment by mossberg** [comment]
i'd say we've achieved an mvp. will close and future improvements will be new issues
