### ISSUE TITLE
AssertionError: No forking yet

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#673]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (4c0f4bc6cf7509eb0f3399327fb494188b137671)

### Python version

Python 2.7.13

### Summary of the problem

Loading a simple contract triggers an assertion error: No forking yet

### Step to reproduce the behavior

This is a small solidity contract to reproduce this issue:

```
contract C {

    function C(address[] x) {
        throw;
    }
}
```

You can trigger this assertion using the manticore cli:

```
$ manticore error.sol                                                                
```

### Expected behavior

It shouldn't fail.

### Actual behavior

```
2017-12-27 12:36:06,314: [11125] m.main:INFO: Beginning analysis
2017-12-27 12:36:06,342: [11125] m.ethereum:INFO: Generated testcase No. 0 - REVERT
Traceback (most recent call last):
  File "/home/g/.local/bin/manticore", line 11, in <module>
    load_entry_point('manticore==0.1.6', 'console_scripts', 'manticore')()
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/__main__.py", line 104, in main
    ethereum_cli(args)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/__main__.py", line 94, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.txlimit)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 850, in multi_tx_analysis
    attacker_account = self.create_account(balance=1000)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 804, in create_account
    assert len(self.running_state_ids) == 1, "No forking yet"
AssertionError: No forking yet
```

**Comment by lght** [comment]
After repro on my box, started digging around in the source. 

Found this concretizing step in the `log()` [function](https://github.com/trailofbits/manticore/blob/master/manticore/platforms/evm.py#L1735), which led me to [ConcretizeStack()](https://github.com/trailofbits/manticore/blob/master/manticore/platforms/evm.py#L966), and the base [Concretize()](https://github.com/trailofbits/manticore/blob/master/manticore/core/state.py#L30).

The `ForkState()` directly below looks like a good candidate. I'm new to z3, so currently reading up on docs and source. Will keep digging at this problem.

**Comment by feliam** [comment]
I'm unable to repro. 
address[] is supported (WIP) in branch ..
git checkout dev-evm-dynamicarguments

**Comment by lght** [comment]
@feliam, I just checked out `dev-evm-dynamicarguments`, and reinstalled manticore from that branch.

Got no errors when I ran the following code:
```
### no-forking.py
from manticore.ethereum import ManticoreEVM

m = ManticoreEVM()
m.verbosity(3)
#And now make the contract account to analyze
source_code = file('no-forking.sol').read()
user_account = m.create_account(balance=1000)

bytecode = m.compile(source_code)
```
---
```
### no-forking.sol
pragma solidity ^ 0.4.18;

contract C { 

    function C(address[] x) {
        throw;
    }   
}
```

**Comment by feliam** [comment]
Awesome! Thank you. This helps.  
We are in the process of reviewing that branch.

**Comment by mossberg** [comment]
I'm getting a slightly different error for this on master now, it's due to manticore seemingly hitting a revert in the init bytecode. this causes it to try to generate a test case, and access the runtime trace, which doesn't exist yet.

maybe an emulation bug?

```
[I] mark ubuntu /m/h/c/m/zzz ❯ manticore  673.sol
2018-03-23 18:10:59,514: [73258] m.main:INFO: Beginning analysis
2018-03-23 18:10:59,561: [73258] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-03-23 18:10:59,569: [73258] m.c.executor:ERROR: Exception: 'seth.rt.trace'
Traceback (most recent call last):
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 481, in run
    self.generate_testcase(current_state, str(e))
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 353, in generate_testcase
    self._publish('will_generate_testcase', state, 'test', message)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 134, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 1168, in _generate_testcase_callback
    address, offset = state.context['seth.rt.trace'][-1]
KeyError: 'seth.rt.trace'

2018-03-23 18:10:59,578: [73258] m.ethereum:INFO: Starting symbolic transaction: 1
2018-03-23 18:10:59,734: [73258] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 16% | Terminated States: 2 | Alive States: 1
2018-03-23 18:10:59,737: [73258] m.ethereum:INFO: Starting symbolic transaction: 2
2018-03-23 18:11:00,096: [73258] m.ethereum:INFO: Finished symbolic transaction: 2 | Code Coverage: 16% | Terminated States: 3 | Alive States: 1
2018-03-23 18:11:00,112: [73328] m.ethereum:INFO: Generated testcase No. 1 - STOP
2018-03-23 18:11:01,662: [73258] m.ethereum:INFO: Results in /mnt/hgfs/code/manticore-play/zzz/mcore_NA_SPT
```
