### ISSUE TITLE
SolverException: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by teknogeek** [trailofbits/manticore#68]
```
(manticore) root@kali:~/CTF/HackTheVote/pwn# manticore ./irs 
2017-03-13 16:17:59,590: [48618] MAIN:INFO: Loading program: ['./irs']
2017-03-13 16:17:59,591: [48618] MAIN:INFO: Workspace: ./mcore_LV0KP1
2017-03-13 16:18:01,437: [48668] CPU:ERROR: CPUID with EAX=d not implemented @ f7ff4826
 
2017-03-13 16:22:56,061: [48668] SMT:WARNING: Found an unknown core, probably a solver timeout
2017-03-13 16:24:29,324: [48668] MEMORY:INFO: Reading 4 bytes from symbolic address <manticore.core.smtlib.expression.BitVecAnd object at 0x7f4a32aed750>
2017-03-13 16:25:00,200: [48668] SMT:WARNING: Found an unknown core, probably a solver timeout
2017-03-13 16:25:35,299: [48668] SMT:WARNING: Found an unknown core, probably a solver timeout
2017-03-13 16:26:07,874: [48668] SMT:WARNING: Found an unknown core, probably a solver timeout
2017-03-13 16:26:40,069: [48668] EXECUTOR:ERROR: Failed an internal assertion: 
Traceback (most recent call last):
  File "/root/.envs/manticore/local/lib/python2.7/site-packages/manticore/core/executor.py", line 923, in run
    assert se.message == 'Max number of different solutions hit'
AssertionError

2017-03-13 16:26:40,100: [48668] EXECUTOR:ERROR: Traceback (most recent call last):
2017-03-13 16:26:40,100: [48668] EXECUTOR:ERROR:   File "/root/.envs/manticore/local/lib/python2.7/site-packages/manticore/core/executor.py", line 923, in run
2017-03-13 16:26:40,101: [48668] EXECUTOR:ERROR:     assert se.message == 'Max number of different solutions hit'
2017-03-13 16:26:40,101: [48668] EXECUTOR:ERROR: AssertionError
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.envs/manticore/local/lib/python2.7/site-packages/manticore/core/executor.py", line 1018, in run
    if solver.check(current_state.constraints):
  File "/root/.envs/manticore/local/lib/python2.7/site-packages/manticore/core/smtlib/solver.py", line 58, in check
    return self.can_be_true(constraints, True)
  File "/root/.envs/manticore/local/lib/python2.7/site-packages/manticore/core/smtlib/solver.py", line 319, in can_be_true
    self._reset(temp_cs.related_to(expression))
  File "/root/.envs/manticore/local/lib/python2.7/site-packages/manticore/core/smtlib/solver.py", line 206, in _reset
    self._stop_proc()
  File "/root/.envs/manticore/local/lib/python2.7/site-packages/manticore/core/smtlib/solver.py", line 172, in _stop_proc
    self._send("(exit)")
  File "/root/.envs/manticore/local/lib/python2.7/site-packages/manticore/core/smtlib/solver.py", line 222, in _send
    raise SolverException(e)
SolverException: [Errno 32] Broken pipe
```

And attached is the binary
[ultrababy.zip](https://github.com/trailofbits/manticore/files/839539/ultrababy.zip)

Note: This is using the `dev-fix-cpuid` branch

**Comment by japesinator** [comment]
This now returns a much more sensible error message, so I'm going to mark this as closed
```
➜  ~ manticore ultrababy      
2017-06-09 10:24:39,888: [10042] MAIN:INFO: Loading program: ['ultrababy']
2017-06-09 10:24:39,889: [10042] MAIN:INFO: Workspace: ./mcore_HN7pC_
2017-06-09 10:25:39,046: [10092][0] EXECUTOR:INFO: Generating testcase No. 1 for state No.0 - SolverException: Max number of different solutions hit
Solver Exception: Dangling PC: PC
```

**Comment by rickbeeloo** [comment]
Any way to check what is going wrong here? Got the same error with 0.3.7 when running [the EVM example](https://github.com/trailofbits/manticore#evm-1)
