### ISSUE TITLE
ecrecover is not supported

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#682]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (4c0f4bc6cf7509eb0f3399327fb494188b137671)

### Python version

Python 2.7.13

### Summary of the problem

Executing a contract with ecrecover fails because it is not implemented.

### Step to reproduce the behavior

This is a small solidity contract to reproduce this issue:

```
contract EcRecovered {
    address public a0;
    
    bytes32 hash0 = 0xf3d4f028f907391acab0fd4894af4b9c5fc9a7a7c8e8a1e52e301c58319effc2;
    bytes32 r0= 0xbade6e6dd120768fda79be6445960fd1258a85abe7d742c63c3739be01886b9e;
    bytes32 s0 = 0x7cb999638196f099d42e09e60f6f4ed4f73aa6a77f8293bdc604cd95be4f4772;
    uint8 v0 = 27;
    
    function recover(bytes32 h0, bytes32 r0, bytes32 s0, uint8 v0) {
        a0 = ecrecover(hash0, v0, r0, s0);
    }

}
```

You can trigger this exception using the manticore cli:

```
$ manticore error.sol                                                                
```

### Expected behavior

I expect manticore to implement ecrecover.

### Actual behavior

```
2017-12-29 09:56:48,631: [20205] m.main:INFO: Beginning analysis
2017-12-29 09:56:48,742: [20205] m.ethereum:INFO: Starting symbolic transaction: 1
2017-12-29 09:56:49,741: [20205] m.c.executor:ERROR: Exception: 1L
Traceback (most recent call last):
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/core/executor.py", line 463, in run
    if not current_state.execute():
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/platforms/evm.py", line 2121, in execute
    self.CALL(ex.gas, ex.to, ex.value, ex.data)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/platforms/evm.py", line 2339, in CALL
    bytecode = self.get_code(to)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/platforms/evm.py", line 2021, in get_code
    return self.storage[address]['code']
KeyError: 1L
...
```

**Comment by feliam** [comment]
related? https://github.com/trailofbits/manticore/issues/527#issuecomment-338140982

**Comment by montyly** [comment]
A bit of context: ecrecover is one of the 4 precompiled smart contracts (described in Appendix E in the yellow paper).
These four contracts are:
- address 0x1: ecrecover
- address 0x2: sha2 256
- address 0x3: ripdemd 160
- address 0x4: identity function
