### ISSUE TITLE
Manticore does not support contracts with imports

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#705]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (465c926a2e39d5daf1405711dac61b6ddd0a2527)

### Python version

Python 2.7.13

### Summary of the problem

Loading a contract with imports fails to compile.

### Step to reproduce the behavior

Use these two small solidity contracts to reproduce this issue:

* C.sol:

```
contract C {
}
```

* imp.sol 

```
import "C.sol";
```

Manticore works correctly if we use C.sol directly:

```
2018-01-12 07:32:53,997: [7335] m.main:INFO: Beginning analysis
2018-01-12 07:32:54,018: [7335] m.ethereum:INFO: Starting symbolic transaction: 1
2018-01-12 07:32:54,149: [7335] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-01-12 07:32:55,053: [7335] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-01-12 07:32:56,828: [7335] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 100% | Terminated States: 2 | Alive States: 0
2018-01-12 07:32:56,848: [7335] m.ethereum:INFO: Results in /home/gustavo/projects/gemini-wallets/manticore/mcore_n5WljI
```

But it fails to compile if we use imp.sol.

### Expected behavior

Manticore should be able to handle contracts with imports.

### Actual behavior

```
2018-01-12 07:37:08,889: [7458] m.main:INFO: Beginning analysis
Traceback (most recent call last):
  File "/home/gustavo/.local/bin/manticore", line 9, in <module>
    load_entry_point('manticore==0.1.6', 'console_scripts', 'manticore')()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/__main__.py", line 104, in main
    ethereum_cli(args)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/__main__.py", line 94, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.txlimit)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 872, in multi_tx_analysis
    contract_account = self.solidity_create_contract(source_code, owner=user_account)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 775, in solidity_create_contract
    compile_results = self._compile(source_code)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 587, in _compile
    raise Exception('Solidity compilation error')
Exception: Solidity compilation error
```

**Comment by MohamedLEGH** [comment]
Even if you try to put all contracts in one file (like with solidity_flattener) it raise an error : 
```
  File "/usr/bin/manticore", line 11, in <module>
    load_entry_point('manticore==0.1.6', 'console_scripts', 'manticore')()
  File "/usr/lib/python2.7/site-packages/manticore/__main__.py", line 104, in main
    ethereum_cli(args)
  File "/usr/lib/python2.7/site-packages/manticore/__main__.py", line 94, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.txlimit)
  File "/usr/lib/python2.7/site-packages/manticore/ethereum.py", line 853, in multi_tx_analysis
    contract_account = self.solidity_create_contract(source_code, owner=user_account)
  File "/usr/lib/python2.7/site-packages/manticore/ethereum.py", line 759, in solidity_create_contract
    compile_results = self._compile(source_code)
  File "/usr/lib/python2.7/site-packages/manticore/ethereum.py", line 571, in _compile
    raise Exception('Solidity file must contain exactly one contract')
Exception: Solidity file must contain exactly one contract
```
What can I do to test my contract with manticore right now ?

**Comment by lsaether** [comment]
Same question

**Comment by feliam** [comment]
Check out this PR https://github.com/trailofbits/manticore/pull/712
When a solidity source code file has more than one contract the default analysis does not know which contract you want to check. So you have to specify it via command line. Something like this: 

multi.sol:

```
contract C1 { }
contract C2 { }
```

and the manticore cli:

```
$ manticore multi.sol --contract C1
2018-01-15 09:08:23,503: [17455] m.main:INFO: Beginning analysis
2018-01-15 09:08:23,523: [17455] m.ethereum:INFO: Starting symbolic transaction: 1
2018-01-15 09:08:23,654: [17455] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-01-15 09:08:24,945: [17455] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-01-15 09:08:27,154: [17455] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 100% | Terminated States: 2 | Alive States: 0
2018-01-15 09:08:27,170: [17455] m.ethereum:INFO: Results in /home/gustavo/projects/DevContest/mcore_QWzfbr
$ manticore multi.sol --contract C2
2018-01-15 09:08:30,541: [17566] m.main:INFO: Beginning analysis
2018-01-15 09:08:30,562: [17566] m.ethereum:INFO: Starting symbolic transaction: 1
2018-01-15 09:08:30,707: [17566] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-01-15 09:08:31,774: [17566] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-01-15 09:08:33,852: [17566] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 100% | Terminated States: 2 | Alive States: 0
2018-01-15 09:08:33,858: [17566] m.ethereum:INFO: Results in /home/gustavo/projects/DevContest/mcore_dfhEPI
```

**Comment by dguido** [comment]
Hey all, we know this is an important issue and we're working on a permanent fix. Please avoid making "me too" type comments, it just clutters up the Github project. The best way to make sure we know it's important to you is giving the issue a Thumbs Up! We pay attention to everything on here, we swear!

**Comment by ggrieco-tob** [comment]
Fixed in f1d16b99e9a5ecf842b0dce07a2c0873c66ea4.

**Comment by ggrieco-tob** [comment]
This is still an issue if the imp.sol file is: 

```
import "./C.sol";
```

It compiles fine using solc, but it fails in manticore:

```
Exception: Solidity compilation error:

/tmp/tmp7PUTls:1:1: Error: Source "/tmp/imp.sol" not found: Unknown exception in read callback.
import "./imp.sol";
^-----------------^
```

**Comment by dwhjames** [comment]
@ggrieco-tob, I tackled this in https://github.com/trailofbits/manticore/pull/873

**Comment by ggrieco-tob** [comment]
Great! Can you add one more little change in your PR and modify [multi_tx_analysis](https://github.com/dwhjames/manticore/blob/dd0b0408691bd16c783918ee7eb3012c06e7eeb4/manticore/ethereum.py#L1002-L1007) to use this new feature? (so the manticore CLI will work out-of-the-box).

Thanks a lot!

**Comment by dwhjames** [comment]
@ggrieco-tob, added in https://github.com/trailofbits/manticore/pull/873/commits/862ccec2794a313fa1c14557f12ad337acf6c89e

**Comment by VeraBE** [comment]
I'm still having issues with imports.

If I have these contracts in the same folder:

```
contract ManticoreImportError0 { }
```

```
import "./ManticoreImportError0.sol";

contract ManticoreImportError1 is ManticoreImportError0 { }
```

And I try to analyze ManticoreImportError1 using `solidity_create_contract` it outputs:

```
Solidity compilation error:

/tmp/tmpvwh6_1ug:1:1: Error: Source "/tmp/ManticoreImportError0.sol" not found: File not found.
import "./ManticoreImportError0.sol";
^-----------------------------------^
```

**Comment by Pentestr5044** [comment]
Same issue as above
