### ISSUE TITLE
SyscallNotImplemented: Syscall index "257" (sys_openat) not implemented.

### ISSUE THREAD

**Issue by vanhauser-thc** [trailofbits/manticore#707]
### OS / Environment
kali-current

### Manticore version
Version: 0.1.6

### Python version
Python 2.7.14+

I have the most simplest program:

```
#include <stdio.h>
void main(int argc, char *argv[]) {
  char buf[8];
  strcpy(buf, argv[1]);
  if (strlen(buf) > 12)
    printf("done\n");
  return 0;
}
````

but when run with manticore I get:
````
# manticore ./strcpy +++
2018-01-14 15:20:54,228: [6828] m.manticore:INFO: Loading program ./strcpy
2018-01-14 15:20:58,744: [6828] m.c.executor:ERROR: Exception: Syscall index "257" (sys_openat) not implemented.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 463, in run
    if not current_state.execute():
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore/platforms/linux.py", line 2015, in execute
    self.syscall()
  File "/usr/local/lib/python2.7/dist-packages/manticore/platforms/linux.py", line 1856, in syscall
    raise SyscallNotImplemented(index, name)
SyscallNotImplemented: Syscall index "257" (sys_openat) not implemented.

2018-01-14 15:20:58,749: [6828] m.manticore:INFO: Results in /prg/misc/vulndev/mcore_9ivqcB
2018-01-14 15:20:58,750: [6828] m.manticore:INFO: Total time: 3.67245984077
````

on the examples its working though

**Comment by mossberg** [comment]
thanks for reporting! that's really odd to see that the "sys_openat" error, since that program does not call open/openat. perhaps the openat is coming from libc init code. if you can share the binary with us, that would be helpful!

**Comment by vanhauser-thc** [comment]
here you go, .c and compiled version in a zip file.

thanks for looking into this!

I do not have this issue when I compile it with -static so I guess its libc causing this.
But on the other hand manticore should work with normally compiled files.

[strcpy.zip](https://github.com/trailofbits/manticore/files/1632619/strcpy.zip)

**Comment by mossberg** [comment]
relevant: #640
