### ISSUE TITLE
Manticore does not support (un)serialization of address[] parameters

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#711]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (465c926a2e39d5daf1405711dac61b6ddd0a2527)

### Python version

Python 2.7.13

### Summary of the problem

Manticore does not support (un)serialization of `address[]` parameters.

### Step to reproduce the behavior

This is a small solidity contract to reproduce this issue:

```
contract C {

  function f(address[] x) returns (address[]) {
    return x;
  }
}
```

You can trigger this issue using the manticore cli:

```
$ manticore error.sol                                                                
```

### Expected behavior

It shouldn't fail.

### Actual behavior

```
2018-01-15 07:46:30,270: [16648] m.main:INFO: Beginning analysis
2018-01-15 07:46:30,330: [16648] m.ethereum:INFO: Starting symbolic transaction: 1
2018-01-15 07:46:30,723: [16648] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-01-15 07:46:31,632: [16648] m.c.executor:ERROR: Exception: address[]
Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/core/executor.py", line 486, in run
    self.generate_testcase(current_state, str(e))
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/core/executor.py", line 354, in generate_testcase
    self._publish('will_generate_testcase', state, 'test', message)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/utils/event.py", line 117, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/utils/event.py", line 133, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/utils/event.py", line 125, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 1198, in _generate_testcase_callback
    function_name, arguments = ABI.parse(signature, tx.data)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 411, in parse
    val, off = ABI._consume_type(ty, data, off)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 389, in _consume_type
    raise NotImplementedError(ty)
NotImplementedError: address[]

2018-01-15 07:46:31,921: [16648] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-01-15 07:46:33,778: [16648] m.ethereum:INFO: Generated testcase No. 2 - REVERT
2018-01-15 07:46:34,704: [16648] m.c.executor:ERROR: Exception: address[]
Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/core/executor.py", line 486, in run
    self.generate_testcase(current_state, str(e))
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/core/executor.py", line 354, in generate_testcase
    self._publish('will_generate_testcase', state, 'test', message)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/utils/event.py", line 117, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/utils/event.py", line 133, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/utils/event.py", line 125, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 1198, in _generate_testcase_callback
    function_name, arguments = ABI.parse(signature, tx.data)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 411, in parse
    val, off = ABI._consume_type(ty, data, off)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 389, in _consume_type
    raise NotImplementedError(ty)
NotImplementedError: address[]

2018-01-15 07:46:34,725: [16648] m.ethereum:INFO: Generated testcase No. 3 - REVERT
2018-01-15 07:46:35,889: [16648] m.ethereum:WARNING: Integer overflow at ADD instruction
2018-01-15 07:46:35,895: [16648] m.c.executor:ERROR: Exception: %d format: a number is required, not BitVecAdd
Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/core/executor.py", line 463, in run
    if not current_state.execute():
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/platforms/evm.py", line 2115, in execute
    self.current.execute()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/platforms/evm.py", line 1304, in execute
    result = implementation(*arguments)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/platforms/evm.py", line 1548, in CALLDATALOAD
    bytes = list(self.data[offset:offset+32])
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/core/smtlib/expression.py", line 676, in __getitem__
    new_array = ArrayVariable(self.index_bits, size, name='%s_b%d_e%d'%(self.name, start, stop), taint=self.taint)
TypeError: %d format: a number is required, not BitVecAdd
...
```

**Comment by defunctio** [comment]
Verified this is resolved in master; https://github.com/trailofbits/manticore/commit/1f74f0fa84a1aa3911c68df1b9cf20800dd7c778.
Closing.
