### ISSUE TITLE
Manticore fails to generate a test case when a parameter in an event is declared with the indexed keyword.

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#713]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (465c926a2e39d5daf1405711dac61b6ddd0a2527)

### Python version

Python 2.7.13

### Summary of the problem

Manticore fails to generate a test case when a parameter in an event is declared with the [indexed keyword](https://ethereum.stackexchange.com/questions/8658/what-does-the-indexed-keyword-do).

### Step to reproduce the behavior

This is a small solidity contract to reproduce this issue:

```
contract C {
    event E (address indexed x);
    function f(address x) {
      E(x);
    }
}
```

You can trigger this issue using the manticore cli:

```
$ manticore error.sol                                                                
```

### Expected behavior

It shouldn't fail.

### Actual behavior

```
2018-01-15 14:27:46,208: [24901] m.main:INFO: Beginning analysis
2018-01-15 14:27:46,249: [24901] m.ethereum:INFO: Starting symbolic transaction: 1
2018-01-15 14:27:46,581: [24901] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-01-15 14:27:48,840: [24901] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-01-15 14:27:51,981: [24901] m.ethereum:INFO: Generated testcase No. 2 - REVERT
2018-01-15 14:27:54,994: [24901] m.ethereum:INFO: Generated testcase No. 3 - REVERT
2018-01-15 14:27:57,232: [24901] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 100% | Terminated States: 4 | Alive States: 1
2018-01-15 14:27:57,233: [24901] m.ethereum:INFO: Generated testcase No. 4 - STOP
Traceback (most recent call last):
  File "/home/gustavo/.local/bin/manticore", line 9, in <module>
    load_entry_point('manticore==0.1.6', 'console_scripts', 'manticore')()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/__main__.py", line 104, in main
    ethereum_cli(args)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/__main__.py", line 94, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.txlimit)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 895, in multi_tx_analysis
    self.finalize()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 1232, in finalize
    self.terminate_state_id(state_id)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 707, in terminate_state_id
    self._generate_testcase_callback(state, 'test', last_exc.message)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.6-py2.7.egg/manticore/ethereum.py", line 1208, in _generate_testcase_callback
    logs_summary.write("Memlog: %s (%s) %s\n" % (solved_memlog.encode('hex'), printable_bytes, flagged(is_log_symbolic)))
AttributeError: 'list' object has no attribute 'encode'
```

**Comment by ggrieco-tob** [comment]
I cannot reproduce this issue in b9a515c. It was (probably) fixed in #739.
