### ISSUE TITLE
ethereum: manticore crashes in codecopy

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#718]
### OS / Environment
Ubuntu 16.04.1
solc 0.4.19

### Manticore version
60d2b61fb36ddb1c0079647a3ceebfb6f9d0c84f

### Python version
2.7

### Summary of the problem
manticore crashes when trying to analyze a smart contract

### Step to reproduce the behavior

https://ethernaut.zeppelin.solutions/level/0x6545df87f57d21cb096a0bfcc53a70464d062512

```
pragma solidity ^0.4.18;

contract Token {

  mapping(address => uint) balances;
  uint public totalSupply;

  function Token(uint _initialSupply) {
    balances[msg.sender] = totalSupply = _initialSupply;
  }

  function transfer(address _to, uint _value) public returns (bool) {
    require(balances[msg.sender] - _value >= 0);
    balances[msg.sender] -= _value;
    balances[_to] += _value;
    return true;
  }

  function balanceOf(address _owner) public constant returns (uint balance) {
    return balances[_owner];
  }
}
```
```
$ manticore token.sol
```

### Expected behavior
manticore should detect an integer underflow in transfer

### Actual behavior
```
$ manticore token.sol                                               
2018-01-29 16:11:54,238: [31924] m.main:INFO: Beginning analysis
2018-01-29 16:11:54,322: [31924] m.c.executor:ERROR: Exception: string index out of range
Traceback (most recent call last):
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 463, in run
    if not current_state.execute():
  File "/mnt/hgfs/code/manticore/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 2112, in execute
    self.current.execute()
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1302, in execute
    result = implementation(*arguments)
  File "/mnt/hgfs/code/manticore/manticore/platforms/evm.py", line 1589, in CODECOPY
    self._store(mem_offset+i, Operators.ORD(self.bytecode[code_offset+i]))
IndexError: string index out of range

Traceback (most recent call last):
  File "/home/mark/.local/bin/manticore", line 9, in <module>
    load_entry_point('manticore', 'console_scripts', 'manticore')()
  File "/mnt/hgfs/code/manticore/manticore/__main__.py", line 105, in main
    ethereum_cli(args)
  File "/mnt/hgfs/code/manticore/manticore/__main__.py", line 95, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit)
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 878, in multi_tx_analysis
    contract_account = self.solidity_create_contract(source_code, contract_name=contract_name, owner=user_account)
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 794, in solidity_create_contract
    init=tuple(init_bytecode)+tuple(ABI.make_function_arguments(*args)))
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 818, in create_contract
    self.run(procs=self._config_procs)
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 931, in run
    self._initial_state = self._executor._workspace.load_state(context['_saved_states'][0], delete=True)
  File "/mnt/hgfs/code/manticore/manticore/core/workspace.py", line 382, in load_state
    return self._store.load_state('{}{:08x}{}'.format(self._prefix, state_id, self._suffix), delete=delete)
  File "/mnt/hgfs/code/manticore/manticore/core/workspace.py", line 163, in load_state
    state = self._serializer.deserialize(f)
  File "/mnt/hgfs/code/manticore/manticore/core/workspace.py", line 51, in deserialize
    return cPickle.load(f)
TypeError: ('__init__() takes exactly 4 arguments (7 given)', <class 'manticore.platforms.evm.Create'>, (None, None, None, '', None, None))

```

**Comment by mossberg** [comment]
This is fixed by #812 

```
[I] mark ubuntu /m/h/c/manticore-play ❯ manticore token.sol
2018-03-15 16:37:38,923: [123426] m.main:INFO: Beginning analysis
2018-03-15 16:37:39,805: [123426] m.ethereum:INFO: Starting symbolic transaction: 1
2018-03-15 16:37:40,234: [123426] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-03-15 16:37:41,170: [123426] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-03-15 16:37:41,877: [123426] m.ethereum:INFO: Generated testcase No. 2 - REVERT
2018-03-15 16:37:42,792: [123426] m.ethereum:INFO: Generated testcase No. 3 - REVERT
2018-03-15 16:37:43,981: [123426] m.ethereum:WARNING: Integer underflow at SUB instruction
2018-03-15 16:37:44,249: [123426] m.ethereum:WARNING: Integer underflow at SUB instruction
2018-03-15 16:37:45,211: [123426] m.ethereum:WARNING: Potentially reading uninitialized storage
2018-03-15 16:37:45,302: [123426] m.ethereum:WARNING: Integer overflow at ADD instruction
2018-03-15 16:37:47,994: [123426] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 76
2018-03-15 16:37:48,002: [123426] m.ethereum:INFO: Starting symbolic transaction: 2
2018-03-15 16:37:51,802: [123426] m.ethereum:WARNING: Potentially reading uninitialized storage

```
