### ISSUE TITLE
Assertion failed when manticore runs a multi-contract solidity file

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#776]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (39370ccf3c9f74c3bb67eb7413b41993377a0948)

### Python version

Python 2.7.14

### Summary of the problem

Assertion failed when manticore runs a multi-contract solidity file.

### Step to reproduce the behavior

This is a small solidity contract to reproduce this issue:

```
contract Alice { 
   function ping(uint x) {
       return;
   } 
}

contract Bob { 
    function pong(Alice c){ 
        c.ping(42); 
    } 
}

```

You can trigger this issue using the manticore cli:

```
$ manticore error.sol --contract Bob                                                                
```

### Expected behavior

It shouldn't crash.

### Actual behavior

```
2018-02-27 15:39:18,066: [17114] m.main:INFO: Beginning analysis
2018-02-27 15:39:18,278: [17114] m.ethereum:INFO: Starting symbolic transaction: 1
2018-02-27 15:39:18,584: [17114] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-02-27 15:39:19,814: [17114] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-02-27 15:39:20,734: [17114] m.ethereum:INFO: Generated testcase No. 2 - REVERT
2018-02-27 15:39:21,821: [17114] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 82% | Terminated States: 4 | Alive States: 0
2018-02-27 15:39:21,830: [17114] m.ethereum:INFO: Starting symbolic transaction: 2
Traceback (most recent call last):
  File "/home/gustavo/.local/bin/manticore", line 11, in <module>
    load_entry_point('manticore==0.1.7', 'console_scripts', 'manticore')()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/__main__.py", line 105, in main
    ethereum_cli(args)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/__main__.py", line 95, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 916, in multi_tx_analysis
    run_symbolic_tx()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 910, in run_symbolic_tx
    value=symbolic_value )
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 887, in transaction
    status = self.run(procs=self._config_procs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 940, in run
    assert context['_saved_states'] or self.initial_state is not None
AssertionError
```

**Comment by feliam** [comment]
So the Bob.pong expects the address of a recently created Alice ?
We are not creating Alice. Though it should not crash.
This is solved here: 
https://github.com/trailofbits/manticore/pull/715#discussion-diff-164883644R935 (I think)
