### ISSUE TITLE
Assertion failed: context['_saved_states'] or self.initial_state is not None

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#795]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (fbf0823cb61aa7f3b417839a4e2e7e3f58352f10)

### Python version

Python 2.7.14

### Summary of the problem

Manticore crashes with a failed assertion when there is no more live state to run.

### Step to reproduce the behavior

This is a small python script to reproduce this issue:

```python
from manticore.ethereum import ManticoreEVM

# initiate the blockchain
m = ManticoreEVM()
source_code = '''
contract Simple {
    function f(uint a) payable public {
        if (a == 65) {
            revert();
        }
    }
}
'''

# Initiate the accounts
user_account = m.create_account(balance=1000)
contract_account = m.solidity_create_contract(source_code, owner=user_account, balance=0)

contract_account.f(1)   # it works
contract_account.f(65) # it works
contract_account.f(m.SValue) # fails with assert context['_saved_states'] or self.initial_state is not None                                                  
```

### Expected behavior

It shouldn't crash. 

### Actual behavior

```
Traceback (most recent call last):
  File "work.py", line 22, in <module>
    contract_account.f(m.SValue)
  File "/home/gustavo/repos/manticore-vanilla/manticore/ethereum.py", line 508, in f
    data=tx_data
  File "/home/gustavo/repos/manticore-vanilla/manticore/ethereum.py", line 887, in transaction
    status = self.run(procs=self._config_procs)
  File "/home/gustavo/repos/manticore-vanilla/manticore/ethereum.py", line 940, in run
    assert context['_saved_states'] or self.initial_state is not None
AssertionError
```

**Comment by feliam** [comment]
We should keep REVERTED states unless in automatic mode?

**Comment by ggrieco-tob** [comment]
I think we should have a proper exception in this case, but this requires to take some decisions (that's why is labeled as "decision-needed").
