### ISSUE TITLE
assertion error in simple contract

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#814]
### Manticore version
eaa0e524b44cbdb4a7bcf3ba6808bbd86c2a16c3

### Step to reproduce the behavior

```
contract Simple {
    function f(uint a) payable public {
        if (a == 65) {
            revert();
        }
    }
}

```
### Actual behavior
```
[I] mark ubuntu /tmp ❯ manticore x.sol

7
2018-03-15 18:27:46,590: [130634] m.main:INFO: Beginning analysis
Traceback (most recent call last):
  File "/home/mark/.local/bin/manticore", line 9, in <module>
    load_entry_point('manticore', 'console_scripts', 'manticore')()
  File "/mnt/hgfs/code/manticore/manticore/__main__.py", line 106, in main
    ethereum_cli(args)
  File "/mnt/hgfs/code/manticore/manticore/__main__.py", line 95, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit)
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 914, in multi_tx_analysis
    attacker_account = self.create_account(balance=1000)
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 869, in create_account
    assert context['_pending_transaction'] is None
AssertionError
```

**Comment by mossberg** [comment]
This is a follow up from #795

**Comment by mossberg** [comment]
sorry, my mistake; i thought i was on master, but was on another branch
