### ISSUE TITLE
KeyError: 214 in srcmap[asm_offset]

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#832]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (d1051f6)

### Python version

Python 2.7.14

### Summary of the problem

Manticore fails with a KeyError when exploring a small contract.

### Step to reproduce the behavior

This is a small solidity contract to reproduce this issue:

```solidity
contract BasicToken {

  function transfer(address _to, uint256 _value) public returns (bool) {
    require(_to != address(0));
    return true;
  }

}

contract C  {
    BasicToken public token;
    function C() public {
        token = new BasicToken();
    }

    function withdraw(address _to, uint _amount) external {
        token.transfer(_to, _amount);
    }

}
```

You can trigger this issue using the manticore cli:

```
$ manticore error.sol --contract C --txlimit 1                                                       
```

### Expected behavior

It should explore all the code without failing. There is an easy workaround commenting the line:

```python
summary.write(metadata.get_source_for(offset, at_runtime))
```
in manticore/ethereum.py

### Actual behavior

```
2018-03-21 09:04:05,239: [25780] m.main:INFO: Beginning analysis
2018-03-21 09:04:06,216: [25780] m.ethereum:INFO: Starting symbolic transaction: 1
2018-03-21 09:04:07,698: [25780] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-03-21 09:04:08,924: [25780] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-03-21 09:04:08,925: [25780] m.c.executor:ERROR: Exception: 214
Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/core/executor.py", line 481, in run
    self.generate_testcase(current_state, str(e))
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/core/executor.py", line 353, in generate_testcase
    self._publish('will_generate_testcase', state, 'test', message)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/utils/event.py", line 134, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 1175, in _generate_testcase_callback
    summary.write(metadata.get_source_for(offset, at_runtime))
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 233, in get_source_for
    beg, size, _, _ = srcmap[asm_offset]
KeyError: 214
...
```

**Comment by ggrieco-tob** [comment]
I cannot reproduce this issue in b9a515c. It was fixed in #839.
