### ISSUE TITLE
Exception: Not enough data for decoding

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#844]
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (03af65e55f7db8b418f79ab250b3a10a7fee668c)

### Python version

Python 2.7.14

### Summary of the problem

Manticore fails (sometimes) to parse the metadata generated by the compilation of a smart contract. 

### Step to reproduce the behavior

This is a small solidity contract to reproduce this issue:

To reproduce this issue:

```bash
$ git clone https://github.com/golemfactory/golem-contracts
$ cd golem-contracts
```

Then apply this patch:

```
diff --git a/contracts/GolemNetworkTokenBatching.sol b/contracts/GolemNetworkTokenBatching.sol
index fd36ba0..1eb9d22 100644
--- a/contracts/GolemNetworkTokenBatching.sol
+++ b/contracts/GolemNetworkTokenBatching.sol
@@ -3,8 +3,8 @@
 
 pragma solidity ^0.4.19;
 
-import "./ReceivingContract.sol";
-import "./TokenProxy.sol";
+import "ReceivingContract.sol";
+import "TokenProxy.sol";
 
 
 /// GolemNetworkTokenBatching can be treated as an upgraded GolemNetworkToken.
```

Then:
```bash
$ cd contracts
```
Finally, you can trigger this issue using this python script:

```python
from manticore.ethereum import ManticoreEVM

m = ManticoreEVM()
m.verbosity(3)

for _ in range(100):
  source_code = open("GolemNetworkTokenBatching.sol","r").read()
  gntb_contract_account = m.solidity_create_contract(source_code, contract_name="GolemNetworkTokenBatching", owner=m.create_account(balance=1), args=[0x0])
```

### Expected behavior

It shouldn't crash.

### Actual behavior

```
2018-03-23 18:00:06,773: [28999] m.c.executor:INFO: load state 0
2018-03-23 18:00:07,389: [28999] m.c.plugin:INFO: Coverage: 61 different instructions executed
2018-03-23 18:00:07,389: [28999] m.c.plugin:INFO: Instructions executed: 61
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    gntb_contract_account = m.solidity_create_contract(source_code, contract_name="GolemNetworkTokenBatching", owner=m.create_account(balance=1), args=[0x0])
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 830, in solidity_create_contract
    self.metadata[address] = SolidityMetadata(*compile_results)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 167, in __init__
    self.srcmap_runtime = self.__build_source_map(self.runtime_bytecode, srcmap_runtime)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 186, in __build_source_map
    for i in evm.EVMAsm.disassemble_all(bytecode[:end]):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 875, in disassemble_all
    instr = EVMAsm.disassemble_one(bytecode, offset=offset)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 840, in disassemble_one
    instruction.parse_operand(bytecode)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 448, in parse_operand
    raise Exception("Not enough data for decoding")
Exception: Not enough data for decoding
```

**Comment by ggrieco-tob** [comment]
I cannot reproduce this issue in b9a515c. It was (probably) fixed in #848.
