### ISSUE TITLE
Can not log when not in run()

### ISSUE THREAD

**Issue by feliam** [trailofbits/manticore#847]
If there is not a state_id set we can not log?

Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 469, in format
    s = self._fmt % record.__dict__
KeyError: 'stateid'

**Comment by mossberg** [comment]
can you please provide instructions to reproduce?

**Comment by mossberg** [comment]
that code snip works now
