### ISSUE TITLE
KeyError: 'seth.rt.trace'

### ISSUE THREAD

**Issue by suhabe** [trailofbits/manticore#879]
### OS / Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

### Manticore version
Development version from git repo at commit 4a98110f4a74916305231a0a2fabc076e6218462

### Python version
Python 2.7.12

### Dependencies
capstone==3.0.5rc2
manticore==0.1.8
ply==3.11
pyelftools==0.24
pysha3==1.0.2
unicorn==1.0.1
z3-solver==4.5.1.0.post2

### Summary of the problem
Exception thrown:
``KeyError: 'seth.rt.trace'``

### Step to reproduce the behavior
`manticore benchmark.sol`

```
pragma solidity ^0.4.18;

contract Benchmark {

    function Benchmark(uint256 x) public {
        require(x != 0);
    }
}
```

### Expected behavior
No exception thrown.

### Actual behavior
Exception thrown:
``KeyError: 'seth.rt.trace'``

### Any relevant logs
Manticore output is
```
$ manticore ~/host/benchmarks/benchmark.sol 
2018-04-23 15:08:41,647: [23888] m.main:INFO: Beginning analysis
2018-04-23 15:08:41,695: [23888] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-04-23 15:08:41,696: [23888] m.c.executor:ERROR: Exception: 'seth.rt.trace'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 481, in run
    self.generate_testcase(current_state, str(e))
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 353, in generate_testcase
    self._publish('will_generate_testcase', state, 'test', message)
  File "/usr/local/lib/python2.7/dist-packages/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/utils/event.py", line 134, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1270, in _generate_testcase_callback
    address, offset = state.context['seth.rt.trace'][-1]
KeyError: 'seth.rt.trace'

2018-04-23 15:08:41,701: [23888] m.ethereum:INFO: Starting symbolic transaction: 1
2018-04-23 15:08:41,862: [23888] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 14% | Terminated States: 2 | Alive States: 1
2018-04-23 15:08:41,863: [23888] m.ethereum:INFO: Starting symbolic transaction: 2
2018-04-23 15:08:42,322: [23888] m.ethereum:INFO: Finished symbolic transaction: 2 | Code Coverage: 14% | Terminated States: 3 | Alive States: 1
2018-04-23 15:08:42,329: [23951] m.ethereum:INFO: Generated testcase No. 1 - STOP
2018-04-23 15:08:43,800: [23888] m.ethereum:INFO: Results in /home/vagrant/host/manticore/mcore_kNkFrU
```

**Comment by astudnev** [comment]
I get this error on all my contracts. Example contracts do not generate this error however

**Comment by feliam** [comment]
Thanks! That issue emerges when mcore tries to report on states that have no runtime trace. Those would be the states in which the constructor failed in your example.

Looks like it is fixed in master.
```
felipe@localhost ~/Projects/manticore/examples/evm $ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
felipe@localhost ~/Projects/manticore/examples/evm $ cat failing.sol 
pragma solidity ^0.4.18;

contract Benchmark {

    function Benchmark(uint256 x) public {
        require(x != 0);
    }
}

felipe@localhost ~/Projects/manticore/examples/evm $ python -m manticore failing.sol 
2018-06-05 09:20:14,367: [1011] m.main:INFO: Beginning analysis
2018-06-05 09:20:14,663: [1011] m.ethereum:INFO: Starting symbolic transaction: 1
2018-06-05 09:20:15,150: [1011] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 85% | Terminated States: 3 | Alive States: 0
2018-06-05 09:20:15,350: [1077] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-06-05 09:20:15,752: [1077] m.ethereum:INFO: Generated testcase No. 1 - RETURN
2018-06-05 09:20:16,573: [1077] m.ethereum:INFO: Generated testcase No. 2 - REVERT
2018-06-05 09:20:18,084: [1011] m.ethereum:INFO: Results in /home/felipe/Projects/manticore/examples/evm/mcore_kLAmiZ

```

**Comment by astudnev** [comment]
How to build/run manticore from master? Have not found any guides

**Comment by feliam** [comment]
Let see. For a developer copy in which you can modify the code in place what I do is something like this ...
git clone https://github.com/trailofbits/manticore.git
cd manticore
python setup.py develop --user

We should put this in a wiki. (If it works)

**Comment by astudnev** [comment]
Yes, it now does not generate this error, but hangs forever on: 

manticore --contract VestingTrustee VestingTrustee.sol
2018-06-05 21:14:09,026: [35871] m.main:INFO: Beginning analysis
2018-06-05 21:14:20,568: [35871] m.ethereum:INFO: Starting symbolic transaction: 1

**Comment by feliam** [comment]
Does that contract have functions with dynamic arguments? 
Dynamic arguments ar hard to explore as their serialization in the calldata arguments contain offsets and sizes. So mcore will try to explore/solve all possible offsets/sizes of them. 
We are working in a mitigation for that. (That is pre-constraint dynamic arguments to user expected values and do not explore compiler injected ABI parsing code)

If that's not the case. define "forever" :) Eventually our goal is to run manticore for a few days in a given contract. 

You have ways to enable more verbosity so you can tell if it is progressing or diverging.

**Comment by astudnev** [comment]
No, the contract has no dynamic args

This is the end of trace where it hangs:

```
-------------------------------------------------------------------------------------------
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L: 0x04a0: CALLDATACOPY  Copy input data in current environment to memory.

0x67518339e369ab3d591d3569ab0a0d83b2ff5198L: Stack                                                                      Memory
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L: top>  0x0000000000000000000000000000000000000000000000000000000000000080   0000  ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??   ................
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L:       <BitVecConcat at 7f330ffdd390>                                       0010  ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??   ................
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L:       <BitVecAdd at 7f330ff8a450>                                          0020  ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??   ................
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L:       0x0000000000000000000000000000000000000000000000000000000000000002   0030  ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??   ................
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L:       0x0000000000000000000000000000000000000000000000000000000000000000   0040  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L:       <BitVecConcat at 7f3310f1cc50>                                       0050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80   ................
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L:       <BitVecAdd at 7f33106f1a10>                                          0060  ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??   ................
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L:       0x000000000000000000000000000000000000000000000000000000000000013e   0070  ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??   ................
0x67518339e369ab3d591d3569ab0a0d83b2ff5198L:       <BitVecAnd at 7f331019a690>                                          



^C2018-06-05 23:14:27,137: [38342] m.c.s.solver:WARNING: Found an unknown core, probably a solver timeout
^C2018-06-05 23:14:35,069: [38342] m.c.s.solver:WARNING: Found an unknown core, probably a solver timeout
^C^CTraceback (most recent call last):
  File "/usr/local/bin/manticore", line 11, in <module>
    sys.exit(main())
  File "/home/studnev/manticore-head/manticore/manticore/__main__.py", line 150, in main
    ethereum_cli(args)
  File "/home/studnev/manticore-head/manticore/manticore/__main__.py", line 135, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit, not args.txnocoverage, args.txaccount)
  File "/home/studnev/manticore-head/manticore/manticore/ethereum.py", line 1330, in multi_tx_analysis
    run_symbolic_tx()
  File "/home/studnev/manticore-head/manticore/manticore/ethereum.py", line 1318, in run_symbolic_tx
    value=symbolic_value)
  File "/home/studnev/manticore-head/manticore/manticore/ethereum.py", line 1291, in transaction
    status = self.run(procs=self._config_procs)
  File "/home/studnev/manticore-head/manticore/manticore/ethereum.py", line 1361, in run
    super(ManticoreEVM, self).run(**kwargs)
  File "/home/studnev/manticore-head/manticore/manticore/manticore.py", line 638, in run
    self._start_workers(procs, profiling=should_profile)
  File "/home/studnev/manticore-head/manticore/manticore/manticore.py", line 419, in _start_workers
    target()
  File "/home/studnev/manticore-head/manticore/manticore/core/executor.py", line 475, in run
    current_state = self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/home/studnev/manticore-head/manticore/manticore/core/executor.py", line 382, in fork
    solutions = state.concretize(expression, policy)
  File "/home/studnev/manticore-head/manticore/manticore/core/state.py", line 282, in concretize
    if self._solver.can_be_true(self._constraints, symbolic == (m + M) / 2):
  File "/home/studnev/manticore-head/manticore/manticore/core/smtlib/solver.py", line 335, in can_be_true
    return self._check() == 'sat'
  File "/home/studnev/manticore-head/manticore/manticore/core/smtlib/solver.py", line 269, in _check
    _status = self._recv()
  File "/home/studnev/manticore-head/manticore/manticore/core/smtlib/solver.py", line 248, in _recv
    buf, l, r = readline()
  File "/home/studnev/manticore-head/manticore/manticore/core/smtlib/solver.py", line 243, in readline
    buf = self._proc.stdout.readline()
  File "/home/studnev/manticore-head/manticore/manticore/utils/nointerrupt.py", line 19, in handler
    self.old_handler(sig, frame)
KeyboardInterrupt

```

**Comment by feliam** [comment]
I run this https://github.com/kinecosystem/kin-token/tree/master/contracts for 4 hours now. I'd say it's running kind of successfully so far. Found 127 paths to a REVERT and 36 to STOP/RETURN/etc. 39% coverage. Though depends highly on the amount of dead code.

2018-06-05 18:00:27,898: [30304] m.ethereum:INFO: Finished symbolic transaction: 2 | Code Coverage: 39% | Terminated States: 127 | Alive States: 36
2018-06-05 18:02:31,111: [3647] m.ethereum:INFO: Generated testcase No. 0 - RETURN
2018-06-05 18:07:37,167: [3647] m.ethereum:INFO: Generated testcase No. 1 - RETURN
2018-06-05 18:12:30,383: [3647] m.ethereum:INFO: Generated testcase No. 2 - RETURN
...

**Comment by mossberg** [comment]
for what it's worth, developer install instructions can be found here: https://github.com/trailofbits/manticore/wiki/Hacking-on-Manticore (linked in the readme too) :)
