### ISSUE TITLE
Running multicore example fails with error 'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by astudnev** [trailofbits/manticore#916]
### OS / Environment

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch

### Manticore version

Version: 0.1.9

### Python version

Python 2.7.13

### Dependencies

capstone==3.0.5rc2
cryptography==1.7.1
enum34==1.1.6
idna==2.2
ipaddress==1.0.17
keyring==10.1
keyrings.alt==1.3
manticore==0.1.9
ply==3.11
pyasn1==0.1.9
pycrypto==2.6.1
pyelftools==0.24
pygobject==3.22.0
pysha3==1.0.2
Pyste==0.9.10
python-apt==1.4.0b3
pyxdg==0.25
SecretStorage==2.3.1
six==1.10.0
unicorn==1.0.1
z3-solver==4.5.1.0.post2

### Summary of the problem

Running manticore umd_example.sol fails with error:

Version of solidity is:

solc --version
solc, the solidity compiler commandline interface
Version: 0.4.25-develop.2018.6.4+commit.4073c02c.Linux.g++

### Step to reproduce the behavior

cd ~/manticore/examples/evm
manticore umd_example.sol 

### Expected behavior

Run test

### Actual behavior

Fail with error

### Any relevant logs

2018-06-04 21:44:01,209: [18079] m.main:INFO: Beginning analysis
Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/manticore/__main__.py", line 113, in main
    ethereum_cli(args)
  File "/usr/local/lib/python2.7/dist-packages/manticore/__main__.py", line 102, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit, not args.txnocoverage, args.txaccount)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1031, in multi_tx_analysis
    contract_account = self.solidity_create_contract(f, contract_name=contract_name, owner=owner_account)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 928, in solidity_create_contract
    compile_results = self._compile(source_code, contract_name)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 718, in _compile
    output, warnings = ManticoreEVM._run_solc(source_code)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 679, in _run_solc
    installed_version = m.groupdict()['version']
AttributeError: 'NoneType' object has no attribute 'groupdict'

**Comment by feliam** [comment]
Hi @astudnev thank you for reporting this!
It looks like this problem is already solved in master. Current master wont crash when it ca not parse strange solce version strings.

**Comment by mossberg** [comment]
since this looks like it's solved in master, i'll close it. thanks for the issue @astudnev!
