### ISSUE TITLE
Manticore fails to emulate exponentiation operation with symbolic base

### ISSUE THREAD

**Issue by noobdoesre** [trailofbits/manticore#921]
### OS / Environment
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:    16.04
Codename:   xenial

### Manticore version
Version: 0.1.9

### Python version
Python 2.7.12

### Dependencies
capstone==3.0.5rc2
cryptography==1.7.1
enum34==1.1.6
idna==2.2
ipaddress==1.0.17
keyring==10.1
keyrings.alt==1.3
manticore==0.1.9
ply==3.11
pyasn1==0.1.9
pycrypto==2.6.1
pyelftools==0.24
pygobject==3.22.0
pysha3==1.0.2
Pyste==0.9.10
python-apt==1.4.0b3
pyxdg==0.25
SecretStorage==2.3.1
six==1.10.0
unicorn==1.0.1
z3-solver==4.5.1.0.post2

### Summary of the problem
Manticora hangs, python reports errors.

### Step to reproduce the behavior
```
from manticore.ethereum import ManticoreEVM

m = ManticoreEVM()
m.verbosity(0)
contract_source_code = '''
contract meh {  
  function foobar(uint x) payable {
    if (x ** 4 == 0x20) {
      revert();
    }
  }
}
'''

user_account = m.create_account(balance=100000000000000000)
m.world.set_balance(user_account, 1000000000000000000)

contract_account = m.solidity_create_contract(contract_source_code, owner=user_account)
print "[+] Creating a contract account", contract_account


symbolic_data = m.make_symbolic_buffer(36)
m.transaction(caller=user_account,
                address=contract_account,
                data=symbolic_data,
                value=1000000000000000000)
```

### Expected behavior
Successful emulation.

### Actual behavior
Python error is reported and manticore hangs.
Looks like power operation has not been implemented for symbolic inputs.

### Any relevant logs
```
[+] Creating a contract account 159725171979439281175487293058222017669144629231
2018-06-07 00:00:37,434: [75770] m.c.executor:ERROR: Exception: unsupported operand type(s) for pow(): 'BitVecConcat', 'long', 'long'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/core/executor.py", line 461, in run
    if not current_state.execute():
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/core/state.py", line 127, in execute
    result = self._platform.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 2475, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 1341, in execute
    result = self._handler(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 1307, in _handler
    return implementation(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 1507, in EXP
    return pow(base, exponent, TT256)
TypeError: unsupported operand type(s) for pow(): 'BitVecConcat', 'long', 'long'
```

**Comment by feliam** [comment]
Woooohooooooooo! Thank you for testing this! Expect a fix soon.

**Comment by mossberg** [comment]
i expect this might be fixed now, we just need to test

**Comment by mossberg** [comment]
still an issue

**Comment by feliam** [comment]
2018-12-11 23:50:51,145: [14829] m.c.executor:^[[31mERROR:^[[0m Exception: unsupported operand type(s) for pow(): 'int', 'BitVecSub', 'int'
Traceback (most recent call last):
  File "manticore/manticore/core/executor.py", line 467, in run
    if not current_state.execute():
  File "manticore/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "manticore/manticore/platforms/evm.py", line 2200, in execute
    self.current_vm.execute()
  File "manticore/manticore/platforms/evm.py", line 916, in execute
    result = self._handler(*arguments)
  File "manticore/manticore/platforms/evm.py", line 821, in _handler
    return implementation(*arguments)
  File "manticore/manticore/platforms/evm.py", line 1084, in EXP
    return pow(base, exponent, TT256)
TypeError: unsupported operand type(s) for pow(): 'int', 'BitVecSub', 'int'
