### ISSUE TITLE
AssertionError tx.result in {'SELFDESTRUCT', 'RETURN', 'STOP'}

### ISSUE THREAD

**Issue by evanpjensen** [trailofbits/manticore#927]
### OS / Environment

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

### Manticore version

b4b4bb7

### Python version

Python 2.7.12

### Summary of the problem
When a symbolic address is used in an evm call, manticore crashes.

### Step to reproduce the behavior
run checker.py in the attached zip.
[assert_error.zip](https://github.com/trailofbits/manticore/files/2103050/assert_error.zip)

### Expected behavior
Warning

### Actual behavior
Crash

### Any relevant logs

```
2018-06-14 08:40:20,128: [4159] m.c.executor:ERROR: Exception: Policy (ACCOUNTS) must be one of: MINMAX, ALL, SAMPLED, ONE
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/core/executor.py", line 461, in run
    if not current_state.execute():
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/core/state.py", line 127, in execute
    result = self._platform.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 2468, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 1346, in execute
    policy=ex.policy)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/core/state.py", line 41, in __init__
    raise Exception("Policy (%s) must be one of: %s" % (policy, ', '.join(self._ValidPolicies),))
Exception: Policy (ACCOUNTS) must be one of: MINMAX, ALL, SAMPLED, ONE

Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/core/executor.py", line 503, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/ethereum.py", line 1589, in _terminate_state_callback
    assert tx.result in {'SELFDESTRUCT', 'RETURN', 'STOP'}
AssertionError
```

**Comment by feliam** [comment]
Thank you. We'll try to reproduce this soon.
Send more!

**Comment by mossberg** [comment]
this doesn't crash on b86395eca6033b42ad75e94878578a428dc56f62, will close now

```
from manticore.ethereum import ManticoreEVM

m = ManticoreEVM()

contract='contract.sol'
with open(contract,'r') as f:
    contract_src=f.read()

user_account=m.create_account()

contract_account=m.solidity_create_contract(contract_src,
                                            owner=user_account)

# contract_account.something_somewhere(m.SValue, m.SValue)

contract_account.something_somewhere(m.make_symbolic_value(), m.make_symbolic_value(160))

m.finalize()
```
