### ISSUE TITLE
TypeError: bad operand type for abs(): 'BitVecITE' in SDIV

### ISSUE THREAD

**Issue by evanpjensen** [trailofbits/manticore#930]
### OS / Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

### Manticore version
e12b57b

### Python version
Python 2.7.12

### Summary of the problem
Manticore crashes when executing an SDIV instruction with symbolic input. 

### Step to reproduce the behavior
Run plain.py in the zip attached
[bug.zip](https://github.com/trailofbits/manticore/files/2108338/bug.zip)

### Expected behavior
No crash, SDIV behaves like any other instruction. 

### Actual behavior
Crash

### Any relevant logs
```
2018-06-16 09:34:18,248: [21405] m.c.executor:ERROR: Exception: bad operand type for abs(): 'BitVecITE'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/core/executor.py", line 461, in run
    if not current_state.execute():
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/core/state.py", line 127, in execute
    result = self._platform.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 2506, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 1334, in execute
    result = self._handler(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 1300, in _handler
    return implementation(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/platforms/evm.py", line 1446, in SDIV
    result = (abs(s0) // abs(s1) * (-1 if s0 * s1 < 0 else 1))
TypeError: bad operand type for abs(): 'BitVecITE'

Process Process-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/core/executor.py", line 503, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.9-py2.7.egg/manticore/ethereum.py", line 1590, in _terminate_state_callback
    assert tx.result in {'SELFDESTRUCT', 'RETURN', 'STOP'}
AssertionError
```

**Comment by evanpjensen** [comment]
Also likely to be present in the SMOD instruction https://github.com/trailofbits/manticore/blob/master/manticore/platforms/evm.py#L1464
