### ISSUE TITLE
Unable to run a simple analysis right after installation

### ISSUE THREAD

**Issue by unboxedtype** [trailofbits/manticore#936]
### OS / Environment
Linux oberon 4.16.12-300.fc28.x86_64 #1 SMP Fri May 25 21:13:28 UTC 2018 
Fedora 28 Workstation Edition

### Manticore version
Version: 0.1.9

### Python version
Python 2.7.14

### Dependencies
capstone==3.0.5rc2
manticore==0.1.9
ply==3.11
pyelftools==0.24
pysha3==1.0.2
unicorn==1.0.1
z3-solver==4.5.1.0.post2

### Summary of the problem
Right after installation, I'm trying to analyze a simple smart contract written in Solidity.
I'm getting strange errors as a result.

### Step to reproduce the behavior
```
$ python -m virtualenv manticore_env
$ source manticore_env/bin/activate
$ pip install manticore
```
...
(installation succeeds)

```
`$ cat ./Wallet.sol`
pragma solidity ^0.4.23;                                                           
contract Wallet {
  mapping(address => uint) private userBalances; 
  address private owner = address(0);       
  event Sent(address to, uint amount);
  constructor() public payable {
    owner = msg.sender;
  }
  function () external payable {  }
  function deposit(address to, uint val) public {
      userBalances[to] = val;
  }
  function withdrawBalance() public {
    uint amountToWithdraw = userBalances[msg.sender];
    if (amountToWithdraw > 0) {
      emit Sent(msg.sender, amountToWithdraw);
      msg.sender.call.value(amountToWithdraw)();
      userBalances[msg.sender] = 0;
    }}}
```

```
`$ manticore ./Wallet.sol `
2018-06-18 18:42:56,285: [24148] m.main:INFO: Beginning analysis
Traceback (most recent call last):
  File "/home/shishkin/src/manticore_env/bin/manticore", line 11, in <module>
    sys.exit(main())
  File "/home/shishkin/src/manticore_env/lib/python2.7/site-packages/manticore/__main__.py", line 113, in main
    ethereum_cli(args)
  File "/home/shishkin/src/manticore_env/lib/python2.7/site-packages/manticore/__main__.py", line 102, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit, not args.txnocoverage, args.txaccount)
  File "/home/shishkin/src/manticore_env/lib/python2.7/site-packages/manticore/ethereum.py", line 1031, in multi_tx_analysis
    contract_account = self.solidity_create_contract(f, contract_name=contract_name, owner=owner_account)
  File "/home/shishkin/src/manticore_env/lib/python2.7/site-packages/manticore/ethereum.py", line 928, in solidity_create_contract
    compile_results = self._compile(source_code, contract_name)
  File "/home/shishkin/src/manticore_env/lib/python2.7/site-packages/manticore/ethereum.py", line 718, in _compile
    output, warnings = ManticoreEVM._run_solc(source_code)
  File "/home/shishkin/src/manticore_env/lib/python2.7/site-packages/manticore/ethereum.py", line 679, in _run_solc
    installed_version = m.groupdict()['version']
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

### Expected behavior
Some meaningful output about the reentrancy bug in the contract.

### Actual behavior
Some errors showing up. See above.

### Any relevant logs
None.

**Comment by mossberg** [comment]
thank you very much for reporting this to us!

**Comment by feliam** [comment]
thnks, this is fixed on master. 

I think that was because the installed solidity compiler printed out an odd version string.
Or because it was not installed at all.

**Comment by unboxedtype** [comment]
```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.25-develop.2018.6.5+commit.4073c02c.mod.Linux.g++
```
Ok, thanks. When will the fixed version be available on PyPI?

**Comment by mossberg** [comment]
We have a released planned for this friday :) i will close this issue now
