### ISSUE TITLE
[Errno 13] Permission denied in docker

### ISSUE THREAD

**Issue by JsHuang** [trailofbits/manticore#991]
### OS / Environment

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

### Manticore version
Manticore 0.1.10

### Python version
Python 2.7.12

### Dependencies

capstone==3.0.5rc2
functools32==3.2.3.post2
manticore==0.1.10
ply==3.11
pyelftools==0.24
pysha3==1.0.2
unicorn==1.0.1
z3-solver==4.5.1.0.post2

### Summary of the pro
using manticore in the official docker , got permission error
### Step to reproduce the behavior
```
docker pull trailofbits/manticore
docker run -d -P --name manti trailofbits/manticore
docker exec -it manti bash
manticore@6d010fe70146:~$ manticore 0x762569.sol --contract RatScam  --txaccount attacker
WARNING: Couldn't open 'parser.out'. [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/manticore/parser.out'
Generating LALR tables
WARNING: Couldn't create 'manticore.parsetab'. [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/manticore/parsetab.py'
...
```
### Expected behavior
manticore works and no error or exceptions

### Actual behavior
got error warnings and manticore throw exceptions  

### Any relevant logs
```
WARNING: Couldn't open 'parser.out'. [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/manticore/parser.out'
Generating LALR tables
WARNING: Couldn't create 'manticore.parsetab'. [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/manticore/parsetab.py'
2018-07-26 02:15:46,022: [143] m.main:INFO: Beginning analysis
2018-07-26 02:15:46,024: [143] m.ethereum:INFO: Starting symbolic create contract
2018-07-26 02:16:26,364: [143] m.ethereum:INFO: Starting symbolic transaction: 0
2018-07-26 03:21:49,546: [143] m.c.s.solver:WARNING: Found an unknown core, probably a solver timeout
(error "out of memory")
2018-07-26 03:29:14,092: [143] m.c.executor:ERROR: Exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 475, in run
    current_state = self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 382, in fork
    solutions = state.concretize(expression, policy)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/state.py", line 292, in concretize
    silent=False)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/solver.py", line 366, in get_all_values
    while self._check() == 'sat':
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/solver.py", line 279, in _check
    raise SolverException(_status)
SolverException

Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 9, in <module>
    load_entry_point('manticore==0.1.10', 'console_scripts', 'manticore')()
  File "/usr/local/lib/python2.7/dist-packages/manticore/__main__.py", line 149, in main
    ethereum_cli(args)
  File "/usr/local/lib/python2.7/dist-packages/manticore/__main__.py", line 135, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit, not args.txnocoverage, args.txaccount)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1735, in multi_tx_analysis
    value=symbolic_value)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1526, in transaction
    self._transaction('CALL', caller, value=value, address=address, data=data)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1694, in _transaction
    self.run(procs=self._config_procs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1767, in run
    super(ManticoreEVM, self).run(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/manticore.py", line 638, in run
    self._start_workers(procs, profiling=should_profile)
  File "/usr/local/lib/python2.7/dist-packages/manticore/manticore.py", line 419, in _start_workers
    target()
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 503, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/usr/local/lib/python2.7/dist-packages/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1875, in _terminate_state_callback
    assert tx.result in {'SELFDESTRUCT', 'RETURN', 'STOP'}
AssertionError
```

**Comment by mossberg** [comment]
thank you for reporting this!
